#region Copyright Syncfusion Inc. 2001 - 2014
// Copyright Syncfusion Inc. 2001 - 2014. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.UI.Xaml.Schedule
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_Schedule_Silverlight {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_Schedule_Silverlight() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.UI.Xaml.Schedule.Resources.Syncfusion.Schedule.Silverlight", typeof(Syncfusion_Schedule_Silverlight).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AppointmentEdit
        {
            get
            {
                return ResourceManager.GetString("AppointmentEdit", resourceCulture);
            }
        }
        internal static string ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        internal static string AllDay
        {
            get
            {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        internal static string April
        {
            get
            {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        internal static string August
        {
            get
            {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        internal static string Busy
        {
            get
            {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }

        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        internal static string ChooseDate
        {
            get
            {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        internal static string Daily
        {
            get
            {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        internal static string Day
        {
            get
            {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }

        internal static string Days
        {
            get
            {
                return ResourceManager.GetString("Day(s)", resourceCulture);
            }
        }
        internal static string December
        {
            get
            {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        internal static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        internal static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        internal static string Copy
        {
            get
            {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        internal static string Paste
        {
            get
            {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        internal static string Resize
        {
            get
            {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        internal static string EighteenHours
        {
            get
            {
                return ResourceManager.GetString("EighteenHours", resourceCulture);
            }
        }

        internal static string EightHours
        {
            get
            {
                return ResourceManager.GetString("EightHours", resourceCulture);
            }
        }
        internal static string ElevenHours
        {
            get
            {
                return ResourceManager.GetString("ElevenHours", resourceCulture);
            }
        }
        internal static string End
        {
            get
            {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        internal static string EndAfter
        {
            get
            {
                return ResourceManager.GetString("EndAfter", resourceCulture);
            }
        }

        internal static string EndBy
        {
            get
            {
                return ResourceManager.GetString("EndBy", resourceCulture);
            }
        }
        internal static string Every
        {
            get
            {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        internal static string EveryDay
        {
            get
            {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        internal static string EveryMonth
        {
            get
            {
                return ResourceManager.GetString("EveryMonth", resourceCulture);
            }
        }
        internal static string EveryWeek
        {
            get
            {
                return ResourceManager.GetString("EveryWeek", resourceCulture);
            }
        }
        internal static string EveryWeekday
        {
            get
            {
                return ResourceManager.GetString("EveryWeekday", resourceCulture);
            }
        }
        internal static string EveryWeekDays
        {
            get
            {
                return ResourceManager.GetString("EveryWeekDays", resourceCulture);
            }
        }
        internal static string EveryYear
        {
            get
            {
                return ResourceManager.GetString("EveryYear", resourceCulture);
            }
        }

        internal static string February
        {
            get
            {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        internal static string FifteenMin
        {
            get
            {
                return ResourceManager.GetString("FifteenMin", resourceCulture);
            }
        }
        internal static string First
        {
            get
            {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        internal static string FiveHours
        {
            get
            {
                return ResourceManager.GetString("FiveHours", resourceCulture);
            }
        }
        internal static string FiveMin
        {
            get
            {
                return ResourceManager.GetString("FiveMin", resourceCulture);
            }
        }
        internal static string FourDays
        {
            get
            {
                return ResourceManager.GetString("FourDays", resourceCulture);
            }
        }
        internal static string FourHours
        {
            get
            {
                return ResourceManager.GetString("FourHours", resourceCulture);
            }
        }
        internal static string Fourth
        {
            get
            {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        internal static string Free
        {
            get
            {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        internal static string Friday
        {
            get
            {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        internal static string HalfDay
        {
            get
            {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        internal static string HowOften
        {
            get
            {
                return ResourceManager.GetString("HowOften", resourceCulture);
            }
        }
        internal static string July
        {
            get
            {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        internal static string June
        {
            get
            {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        internal static string Location
        {
            get
            {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        internal static string March
        {
            get
            {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }

        internal static string May
        {
            get
            {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        internal static string Monday
        {
            get
            {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        internal static string Monthson
        {
            get
            {
                return ResourceManager.GetString("Month(s)on", resourceCulture);
            }
        }
        internal static string Monthly
        {
            get
            {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }

        internal static string NineHours
        {
            get
            {
                return ResourceManager.GetString("NineHours", resourceCulture);
            }
        }
        internal static string NoEndDate
        {
            get
            {
                return ResourceManager.GetString("NoEndDate", resourceCulture);
            }
        }
        internal static string None
        {
            get
            {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        internal static string Notes
        {
            get
            {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        internal static string November
        {
            get
            {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        internal static string October
        {
            get
            {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        internal static string of
        {
            get
            {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        internal static string on
        {
            get
            {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }

        internal static string Once
        {
            get
            {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        internal static string OneDay
        {
            get
            {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        internal static string OneHour
        {
            get
            {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        internal static string OneWeek
        {
            get
            {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }

        internal static string OutOfOffice
        {
            get
            {
                return ResourceManager.GetString("OutOfOffice", resourceCulture);
            }
        }
        internal static string RangeOfRecurrence
        {
            get
            {
                return ResourceManager.GetString("RangeOfRecurrence", resourceCulture);
            }
        }
        internal static string ReadOnly
        {
            get
            {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        internal static string ReadOnlyOff
        {
            get
            {
                return ResourceManager.GetString("ReadOnlyOff", resourceCulture);
            }
        }

        internal static string ReadOnlyOn
        {
            get
            {
                return ResourceManager.GetString("ReadOnlyOn", resourceCulture);
            }
        }
        internal static string RecurEvery
        {
            get
            {
                return ResourceManager.GetString("RecurEvery", resourceCulture);
            }
        }
        internal static string Recurrence
        {
            get
            {
                return ResourceManager.GetString("Recurrence", resourceCulture);
            }
        }
        internal static string RecurrenceDisabled
        {
            get
            {
                return ResourceManager.GetString("RecurrenceDisabled", resourceCulture);
            }
        }

        internal static string RecurrenceEnabled
        {
            get
            {
                return ResourceManager.GetString("RecurrenceEnabled", resourceCulture);
            }
        }
        internal static string Reminder
        {
            get
            {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        internal static string Saturday
        {
            get
            {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        internal static string Second
        {
            get
            {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        internal static string SevenHours
        {
            get
            {
                return ResourceManager.GetString("SevenHours", resourceCulture);
            }
        }
        internal static string ShowMore
        {
            get
            {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        internal static string SixHours
        {
            get
            {
                return ResourceManager.GetString("SixHours", resourceCulture);
            }
        }

        internal static string Start
        {
            get
            {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        internal static string StartDate
        {
            get
            {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        internal static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        internal static string Subject
        {
            get
            {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        internal static string Sunday
        {
            get
            {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        internal static string TenHours
        {
            get
            {
                return ResourceManager.GetString("TenHours", resourceCulture);
            }
        }
        internal static string TenMin
        {
            get
            {
                return ResourceManager.GetString("TenMin", resourceCulture);
            }
        }
        internal static string Tentative
        {
            get
            {
                return ResourceManager.GetString("Tentative", resourceCulture);
            }
        }

        internal static string The
        {
            get
            {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        internal static string Third
        {
            get
            {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        internal static string ThirtyMin
        {
            get
            {
                return ResourceManager.GetString("ThirtyMin", resourceCulture);
            }
        }
        internal static string ThreeDays
        {
            get
            {
                return ResourceManager.GetString("ThreeDays", resourceCulture);
            }
        }

        internal static string ThreeHours
        {
            get
            {
                return ResourceManager.GetString("ThreeHours", resourceCulture);
            }
        }
        internal static string Thursday
        {
            get
            {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        internal static string Tuesday
        {
            get
            {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        internal static string TweleveHours
        {
            get
            {
                return ResourceManager.GetString("TweleveHours", resourceCulture);
            }
        }

        internal static string TwoDays
        {
            get
            {
                return ResourceManager.GetString("TwoDays", resourceCulture);
            }
        }
        internal static string TwoHours
        {
            get
            {
                return ResourceManager.GetString("TwoHours", resourceCulture);
            }
        }
        internal static string TwoWeeks
        {
            get
            {
                return ResourceManager.GetString("TwoWeeks", resourceCulture);
            }
        }
        internal static string Wednesday
        {
            get
            {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }

        internal static string Weekson
        {
            get
            {
                return ResourceManager.GetString("Week(s)on", resourceCulture);
            }
        }
        internal static string Weekly
        {
            get
            {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        internal static string Where
        {
            get
            {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        internal static string Yearson
        {
            get
            {
                return ResourceManager.GetString("Year(s)on", resourceCulture);
            }
        }

        internal static string Yearly
        {
            get
            {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        internal static string ZeroMin
        {
            get
            {
                return ResourceManager.GetString("ZeroMin", resourceCulture);
            }
        }
        internal static string EditRecurrence
        {
            get
            {
                return ResourceManager.GetString("EditRecurrence", resourceCulture);
            }
        }
        internal static string RecurrencePattern
        {
            get
            {
                return ResourceManager.GetString("RecurrencePattern", resourceCulture);
            }
        }

        internal static string OK
        {
            get
            {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        internal static string RemoveRecurrence
        {
            get
            {
                return ResourceManager.GetString("RemoveRecurrence", resourceCulture);
            }
        }
    }
}
