//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendRealTimeSlim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrendRealTimeSlim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual setting:.
        /// </summary>
        public static string ActualSettings {
            get {
                return ResourceManager.GetString("ActualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AddDockManager {
            get {
                return ResourceManager.GetString("AddDockManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pen.
        /// </summary>
        public static string AddPen {
            get {
                return ResourceManager.GetString("AddPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point Setting.
        /// </summary>
        public static string AddPointSettingButtonTitle {
            get {
                return ResourceManager.GetString("AddPointSettingButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddSettings {
            get {
                return ResourceManager.GetString("AddSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Aggregation Type.
        /// </summary>
        public static string AggregationType {
            get {
                return ResourceManager.GetString("AggregationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Values.
        /// </summary>
        public static string AllTitle {
            get {
                return ResourceManager.GetString("AllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Full Stacked.
        /// </summary>
        public static string AreaFullStackedSerieTitle {
            get {
                return ResourceManager.GetString("AreaFullStackedSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaSerie {
            get {
                return ResourceManager.GetString("AreaSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaSerieTitle {
            get {
                return ResourceManager.GetString("AreaSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Stacked.
        /// </summary>
        public static string AreaStackedSerieTitle {
            get {
                return ResourceManager.GetString("AreaStackedSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Step.
        /// </summary>
        public static string AreaStepSerieTitle {
            get {
                return ResourceManager.GetString("AreaStepSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument.
        /// </summary>
        public static string ArgumentTitle {
            get {
                return ResourceManager.GetString("ArgumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Index.
        /// </summary>
        public static string ArrayIndex {
            get {
                return ResourceManager.GetString("ArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authomatic Scale.
        /// </summary>
        public static string AutomaticScale {
            get {
                return ResourceManager.GetString("AutomaticScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Unexpected Error: check historical settings and database services (for more details refer to the system log).
        /// </summary>
        public static string BadUnexpectedError {
            get {
                return ResourceManager.GetString("BadUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Side.
        /// </summary>
        public static string BarSideSerieTitle {
            get {
                return ResourceManager.GetString("BarSideSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Fit.
        /// </summary>
        public static string BestFit {
            get {
                return ResourceManager.GetString("BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush Editor.
        /// </summary>
        public static string BrushEditor {
            get {
                return ResourceManager.GetString("BrushEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Area.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string ChartArgPointTooltip {
            get {
                return ResourceManager.GetString("ChartArgPointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Control.
        /// </summary>
        public static string ChartControlLog {
            get {
                return ResourceManager.GetString("ChartControlLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ChartValuePointTooltip {
            get {
                return ResourceManager.GetString("ChartValuePointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart XY Control.
        /// </summary>
        public static string ChartXYControlLog {
            get {
                return ResourceManager.GetString("ChartXYControlLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all details.
        /// </summary>
        public static string CollapseAllButtonTitle {
            get {
                return ResourceManager.GetString("CollapseAllButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorTitle {
            get {
                return ResourceManager.GetString("ColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalogger Column Selection.
        /// </summary>
        public static string ColumnListSelection {
            get {
                return ResourceManager.GetString("ColumnListSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string ColumnSerie {
            get {
                return ResourceManager.GetString("ColumnSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string ConfigBaseName {
            get {
                return ResourceManager.GetString("ConfigBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Server.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealTime Trend.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string ControlViewModel {
            get {
                return ResourceManager.GetString("ControlViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or Hide Cross Hair Cursors.
        /// </summary>
        public static string CrossHairTitle {
            get {
                return ResourceManager.GetString("CrossHairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Logger Name.
        /// </summary>
        public static string DataLoggerTreeViewName {
            get {
                return ResourceManager.GetString("DataLoggerTreeViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Day Values.
        /// </summary>
        public static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *na.
        /// </summary>
        public static string DeadBandResult {
            get {
                return ResourceManager.GetString("DeadBandResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string DefaultPenName {
            get {
                return ResourceManager.GetString("DefaultPenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Point Setting.
        /// </summary>
        public static string DeletePointSettingButtonTitle {
            get {
                return ResourceManager.GetString("DeletePointSettingButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove settings.
        /// </summary>
        public static string DeleteSettings {
            get {
                return ResourceManager.GetString("DeleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Values.
        /// </summary>
        public static string DemoValues {
            get {
                return ResourceManager.GetString("DemoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Tag.
        /// </summary>
        public static string DroppedTag {
            get {
                return ResourceManager.GetString("DroppedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Value.
        /// </summary>
        public static string DValue {
            get {
                return ResourceManager.GetString("DValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout.
        /// </summary>
        public static string EditLayoutPopupTitle {
            get {
                return ResourceManager.GetString("EditLayoutPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string EditSettings {
            get {
                return ResourceManager.GetString("EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditWindow {
            get {
                return ResourceManager.GetString("EditWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date: .
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTimeTitle {
            get {
                return ResourceManager.GetString("EndTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error drawing values: {0}.
        /// </summary>
        public static string ErrorDrawingValues {
            get {
                return ResourceManager.GetString("ErrorDrawingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading values: {0}.
        /// </summary>
        public static string ErrorLoadingValues {
            get {
                return ResourceManager.GetString("ErrorLoadingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on pushing:.
        /// </summary>
        public static string ErrorOnPushing {
            get {
                return ResourceManager.GetString("ErrorOnPushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on reset:.
        /// </summary>
        public static string ErrorOnReset {
            get {
                return ResourceManager.GetString("ErrorOnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on zooming:.
        /// </summary>
        public static string ErrorOnZooming {
            get {
                return ResourceManager.GetString("ErrorOnZooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported tag format.
        /// </summary>
        public static string ErrTagFormat {
            get {
                return ResourceManager.GetString("ErrTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUnit.
        /// </summary>
        public static string EUnit {
            get {
                return ResourceManager.GetString("EUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all details.
        /// </summary>
        public static string ExpandAllButtonTitle {
            get {
                return ResourceManager.GetString("ExpandAllButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand or Collapse.
        /// </summary>
        public static string ExpandTitle {
            get {
                return ResourceManager.GetString("ExpandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        public static string Fetch {
            get {
                return ResourceManager.GetString("Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Last Step.
        /// </summary>
        public static string GoEnd {
            get {
                return ResourceManager.GetString("GoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Step.
        /// </summary>
        public static string GoNext {
            get {
                return ResourceManager.GetString("GoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Two Steps.
        /// </summary>
        public static string GoNextTwo {
            get {
                return ResourceManager.GetString("GoNextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Next Step.
        /// </summary>
        public static string GoPrev {
            get {
                return ResourceManager.GetString("GoPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Next Two Steps.
        /// </summary>
        public static string GoPrevTwo {
            get {
                return ResourceManager.GetString("GoPrevTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to First Step.
        /// </summary>
        public static string GoStart {
            get {
                return ResourceManager.GetString("GoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop chart and select a serie from legend to display data in the grid.
        /// </summary>
        public static string GridDataTooltip {
            get {
                return ResourceManager.GetString("GridDataTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag: .
        /// </summary>
        public static string GridTagName {
            get {
                return ResourceManager.GetString("GridTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Hour Values.
        /// </summary>
        public static string HourTitle {
            get {
                return ResourceManager.GetString("HourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have NOT the authorization to read this node.
        /// </summary>
        public static string ItemNotReadable {
            get {
                return ResourceManager.GetString("ItemNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have NOT the authorization to write this node.
        /// </summary>
        public static string ItemNotWritable {
            get {
                return ResourceManager.GetString("ItemNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pens.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Label Color.
        /// </summary>
        public static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or Hide Labels.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend Area.
        /// </summary>
        public static string LegendArea {
            get {
                return ResourceManager.GetString("LegendArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend area visible.
        /// </summary>
        public static string LegendAreaVisible {
            get {
                return ResourceManager.GetString("LegendAreaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string LegendTitle {
            get {
                return ResourceManager.GetString("LegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Full Stacked.
        /// </summary>
        public static string LineFullStackedTitle {
            get {
                return ResourceManager.GetString("LineFullStackedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LineSerie {
            get {
                return ResourceManager.GetString("LineSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Stacked.
        /// </summary>
        public static string LineStackedSerieTitle {
            get {
                return ResourceManager.GetString("LineStackedSerieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Step.
        /// </summary>
        public static string LineStepTitle {
            get {
                return ResourceManager.GetString("LineStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pens.
        /// </summary>
        public static string ManagePenList {
            get {
                return ResourceManager.GetString("ManagePenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Max Return Values.
        /// </summary>
        public static string MaxReturnValues {
            get {
                return ResourceManager.GetString("MaxReturnValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Minute Values.
        /// </summary>
        public static string MinTitle {
            get {
                return ResourceManager.GetString("MinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Month Values.
        /// </summary>
        public static string MonthTitle {
            get {
                return ResourceManager.GetString("MonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDownButtonTitle {
            get {
                return ResourceManager.GetString("MoveDownButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUpButtonTitle {
            get {
                return ResourceManager.GetString("MoveUpButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameTitle {
            get {
                return ResourceManager.GetString("NameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Next Buffer.
        /// </summary>
        public static string NextBuffer {
            get {
                return ResourceManager.GetString("NextBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please: Tag selection is mandatory!.
        /// </summary>
        public static string NullTagReference {
            get {
                return ResourceManager.GetString("NullTagReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC UA Browser.
        /// </summary>
        public static string OPCUABrowser {
            get {
                return ResourceManager.GetString("OPCUABrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading some historical values: The index &apos;{0}&apos; was out of range..
        /// </summary>
        public static string OutOfRangeIndexOnLoadingHistoricalValues {
            get {
                return ResourceManager.GetString("OutOfRangeIndexOnLoadingHistoricalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Area.
        /// </summary>
        public static string PenArea {
            get {
                return ResourceManager.GetString("PenArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen area visible.
        /// </summary>
        public static string PenAreaVisible {
            get {
                return ResourceManager.GetString("PenAreaVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string PenBaseName {
            get {
                return ResourceManager.GetString("PenBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Color.
        /// </summary>
        public static string PenColor {
            get {
                return ResourceManager.GetString("PenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen List.
        /// </summary>
        public static string PenList {
            get {
                return ResourceManager.GetString("PenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Name.
        /// </summary>
        public static string PenName {
            get {
                return ResourceManager.GetString("PenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Properties.
        /// </summary>
        public static string PenProperties {
            get {
                return ResourceManager.GetString("PenProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Style.
        /// </summary>
        public static string PenStyle {
            get {
                return ResourceManager.GetString("PenStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Color.
        /// </summary>
        public static string PointColor {
            get {
                return ResourceManager.GetString("PointColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Point Date.
        /// </summary>
        public static string PointDate {
            get {
                return ResourceManager.GetString("PointDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string PointItem {
            get {
                return ResourceManager.GetString("PointItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string PointItems {
            get {
                return ResourceManager.GetString("PointItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Name.
        /// </summary>
        public static string PointName {
            get {
                return ResourceManager.GetString("PointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Color Settings.
        /// </summary>
        public static string PointSettingsEditor {
            get {
                return ResourceManager.GetString("PointSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Point Value.
        /// </summary>
        public static string PointValue {
            get {
                return ResourceManager.GetString("PointValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string PredefinedPenKinds_seriesAreaStyle {
            get {
                return ResourceManager.GetString("PredefinedPenKinds_seriesAreaStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string PredefinedPenKinds_seriesColumnStyle {
            get {
                return ResourceManager.GetString("PredefinedPenKinds_seriesColumnStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string PredefinedPenKinds_seriesLineStyle {
            get {
                return ResourceManager.GetString("PredefinedPenKinds_seriesLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter.
        /// </summary>
        public static string PredefinedPenKinds_seriesScatterStyle {
            get {
                return ResourceManager.GetString("PredefinedPenKinds_seriesScatterStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Line.
        /// </summary>
        public static string PredefinedPenKinds_seriesStepLineStyle {
            get {
                return ResourceManager.GetString("PredefinedPenKinds_seriesStepLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Previous Buffer.
        /// </summary>
        public static string PrevBuffer {
            get {
                return ResourceManager.GetString("PrevBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintTitle {
            get {
                return ResourceManager.GetString("PrintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string PropertyInspectorPenPrefix {
            get {
                return ResourceManager.GetString("PropertyInspectorPenPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push values.
        /// </summary>
        public static string PushTitle {
            get {
                return ResourceManager.GetString("PushTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low value must be lower than the High Value.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Type.
        /// </summary>
        public static string ReadType {
            get {
                return ResourceManager.GetString("ReadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Every.
        /// </summary>
        public static string RecordEvery {
            get {
                return ResourceManager.GetString("RecordEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload settings.
        /// </summary>
        public static string ReloadConfiguration {
            get {
                return ResourceManager.GetString("ReloadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pen.
        /// </summary>
        public static string RemovePen {
            get {
                return ResourceManager.GetString("RemovePen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveSettings {
            get {
                return ResourceManager.GetString("RemoveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameSettings {
            get {
                return ResourceManager.GetString("RenameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetConfiguration {
            get {
                return ResourceManager.GetString("ResetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the default layout ?.
        /// </summary>
        public static string ResetLayoutAskConfirm {
            get {
                return ResourceManager.GetString("ResetLayoutAskConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetSettingsTooltip {
            get {
                return ResourceManager.GetString("ResetSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset buffer values.
        /// </summary>
        public static string ResetTitle {
            get {
                return ResourceManager.GetString("ResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Rotation3DTitle {
            get {
                return ResourceManager.GetString("Rotation3DTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes before quit?.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving runtime settings.
        /// </summary>
        public static string SavingError {
            get {
                return ResourceManager.GetString("SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select String ID.
        /// </summary>
        public static string SelectStringEditor {
            get {
                return ResourceManager.GetString("SelectStringEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series labels visibile.
        /// </summary>
        public static string SeriesLabelVisibleTitle {
            get {
                return ResourceManager.GetString("SeriesLabelVisibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerHistoryTrend.
        /// </summary>
        public static string ServerHistoryTrendControl {
            get {
                return ResourceManager.GetString("ServerHistoryTrendControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Picoseconds.
        /// </summary>
        public static string ServerPicoseconds {
            get {
                return ResourceManager.GetString("ServerPicoseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Timestamp.
        /// </summary>
        public static string ServerTimestamp {
            get {
                return ResourceManager.GetString("ServerTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealTimeTrend.
        /// </summary>
        public static string SessionName {
            get {
                return ResourceManager.GetString("SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting list:.
        /// </summary>
        public static string SettingList {
            get {
                return ResourceManager.GetString("SettingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Axis.
        /// </summary>
        public static string ShowAxis {
            get {
                return ResourceManager.GetString("ShowAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Diadram.
        /// </summary>
        public static string SimplePie {
            get {
                return ResourceManager.GetString("SimplePie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Properties.
        /// </summary>
        public static string SmartPropertiesPopupTitle {
            get {
                return ResourceManager.GetString("SmartPropertiesPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Picoseconds.
        /// </summary>
        public static string SourcePicoseconds {
            get {
                return ResourceManager.GetString("SourcePicoseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Timestamp.
        /// </summary>
        public static string SourceTimestamp {
            get {
                return ResourceManager.GetString("SourceTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date: .
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTimeTitle {
            get {
                return ResourceManager.GetString("StartTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Statistic.
        /// </summary>
        public static string StatisticMax {
            get {
                return ResourceManager.GetString("StatisticMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Statistic.
        /// </summary>
        public static string StatisticMax1 {
            get {
                return ResourceManager.GetString("StatisticMax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Statistic.
        /// </summary>
        public static string StatisticMin {
            get {
                return ResourceManager.GetString("StatisticMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Statistic.
        /// </summary>
        public static string StatisticMin1 {
            get {
                return ResourceManager.GetString("StatisticMin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string StrokeThickness {
            get {
                return ResourceManager.GetString("StrokeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Style.
        /// </summary>
        public static string Style3D {
            get {
                return ResourceManager.GetString("Style3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Browser.
        /// </summary>
        public static string TagListSelection {
            get {
                return ResourceManager.GetString("TagListSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Name.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string TimeSpanFormatDaysPart {
            get {
                return ResourceManager.GetString("TimeSpanFormatDaysPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeTitle {
            get {
                return ResourceManager.GetString("TimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Control.
        /// </summary>
        public static string TrendControlLog {
            get {
                return ResourceManager.GetString("TrendControlLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use EU Range.
        /// </summary>
        public static string UseEURange {
            get {
                return ResourceManager.GetString("UseEURange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value .
        /// </summary>
        public static string ValueTitle {
            get {
                return ResourceManager.GetString("ValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Time Frame.
        /// </summary>
        public static string ViewTimeFrame {
            get {
                return ResourceManager.GetString("ViewTimeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string VisibleTitle {
            get {
                return ResourceManager.GetString("VisibleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Data....
        /// </summary>
        public static string WaitText {
            get {
                return ResourceManager.GetString("WaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading historical values: please refer to project log for details..
        /// </summary>
        public static string WarnigOnLoadingHistoricalValues {
            get {
                return ResourceManager.GetString("WarnigOnLoadingHistoricalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Week Values.
        /// </summary>
        public static string WeekTitle {
            get {
                return ResourceManager.GetString("WeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalogger.
        /// </summary>
        public static string XHistoricalName {
            get {
                return ResourceManager.GetString("XHistoricalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Tag.
        /// </summary>
        public static string XTagName {
            get {
                return ResourceManager.GetString("XTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Last Year Values.
        /// </summary>
        public static string YearTitle {
            get {
                return ResourceManager.GetString("YearTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalogger.
        /// </summary>
        public static string YHistoricalName {
            get {
                return ResourceManager.GetString("YHistoricalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Tag.
        /// </summary>
        public static string YTagName {
            get {
                return ResourceManager.GetString("YTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom percent.
        /// </summary>
        public static string Zoom3DTitle {
            get {
                return ResourceManager.GetString("Zoom3DTitle", resourceCulture);
            }
        }
    }
}
