<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
        <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data.Linq" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Web" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\wpfutilities\cryptstring\CryptString.cs">
      <Link>CrypString\CryptString.cs</Link>
    </Compile>
    <Compile Include="Documents\UFRecipeDocument.cs" />
    <Compile Include="Documents\RecipeUAServerDocument.cs" />
    <Compile Include="Helpers\DataSetHelper.cs" />
    <Compile Include="Helpers\RecipeEntityHelper.cs" />
    <Compile Include="Properties\Settings.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Include="RecipeModel\ConnectionSourceReference.cs" />
    <Compile Include="RecipeModel\EditValueControlTypeEnum.cs" />
    <Compile Include="RecipeModel\LinkType.cs" />
    <Compile Include="RecipeModel\RecipeUABaseAddress.cs" />
    <Compile Include="RecipeModel\StringEncodingType.cs" />
    <Compile Include="RecipeModel\TransportDefaultPorts.cs" />
    <Compile Include="RecipeModel\UFDataValuesList.cs" />
    <Compile Include="RecipeModel\UFGroupsList.cs" />
    <Compile Include="RecipeModel\UFRecipeEntity.cs" />
    <Compile Include="RecipeModel\UFDataValueEntity.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="RecipeModel\UFGroupEntity.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="RecipeModel\RecipeUAConfiguration.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\CrossReferenceHelper\CrossReferenceHelper.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\VFS\VFS.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Private>False</Private>
    </ProjectReference>
	<ProjectReference Include="..\RecipeServiceCMS\RecipeServiceCMS.csproj">
		<Private>False</Private>
	</ProjectReference>
	<ProjectReference Include="..\UFProcessServiceCMS\UFProcessServiceCMS.csproj">
		<Private>False</Private>
	</ProjectReference>
  </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
	    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
		    <Private>true</Private>
	    </ProjectReference>
    </ItemGroup>
	
    <ItemGroup>
        <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\UFUATag\UFUAModel.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\Utilities\Utilities.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\RecipeUAServerInfo\RecipeUAServerInfo.csproj">
            <Private>False</Private>
        </ProjectReference>
        <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
            <Private>False</Private>
        </ProjectReference>
    </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <Reference Include="System.ServiceModel" />
    <None Update="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>