<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\Managers\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\Managers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
    <PackageReference Include="System.Speech" Version="7.0.0" />
  </ItemGroup>
	
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>

    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="PresentationCore">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="PresentationFramework">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Speech" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="UIAutomationProvider">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="WindowsBase">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="PropertyDataTemplate\CommandSettingsPropertyEditor.xaml.cs">
      <DependentUpon>CommandSettingsPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="ComponentService\CommandManagerComponent.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Executer\CommandsExecuter.cs" />
    <Compile Include="Executer\EntityWeakReference.cs" />
    <Compile Include="Helpers\CommandsViewModel.cs" />
    <Compile Include="Extensions\CommandManagerExtensions.cs" />
    <Compile Include="UserControls\Converters\CommandsValueConverter.cs" />
    <Compile Include="Helpers\CommandsEditObject.cs" />
    <Compile Include="PropertyDataTemplate\CommandsPropertyEditor.xaml.cs">
      <DependentUpon>CommandsPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ScreenParameterUriPropertyEditor.xaml.cs">
      <DependentUpon>ScreenParameterUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\LogicUriPropertyEditor.xaml.cs">
      <DependentUpon>LogicUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\MenuUriPropertyEditor.xaml.cs">
      <DependentUpon>MenuUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\RecipeUriPropertyEditor.xaml.cs">
      <DependentUpon>RecipeUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ChangeCulturePropertyEditor.xaml.cs">
      <DependentUpon>ChangeCulturePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ReportUriPropertyEditor.xaml.cs">
      <DependentUpon>ReportUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ScriptUriPropertyEditor.xaml.cs">
      <DependentUpon>ScriptUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\VoiceNamePropertyEditor.xaml.cs">
      <DependentUpon>VoiceNamePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ScreenUriPropertyEditor.xaml.cs">
      <DependentUpon>ScreenUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\CommonCommandPropertyEditor.xaml.cs">
      <DependentUpon>CommonCommandPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\Converters\ArgumentValueConverter.cs" />
    <Compile Include="UserControls\Converters\DivideDoubleByTwoConverter.cs" />
    <Compile Include="UserControls\Converters\ItemSourceLockedUsersConverter.cs" />
    <Compile Include="UserControls\Converters\NodeIdToTypeConverter.cs" />
    <Compile Include="UserControls\EditMethodCallParameters.xaml.cs">
      <DependentUpon>EditMethodCallParameters.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\ListCultures.xaml.cs">
      <DependentUpon>ListCultures.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\UnlockUser.xaml.cs">
      <DependentUpon>UnlockUser.xaml</DependentUpon>
    </Compile>    
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="AlarmCommand.cs" />
    <Compile Include="CallMethodCommand.cs" />
    <Compile Include="ChangeConverterCommand.cs" />
    <Compile Include="OpenPadCommand.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Include="TTSCommand.cs" />
    <Compile Include="CommandManager.cs" />
    <Compile Include="CommandManagerList.cs" />
    <Compile Include="ChangeCultureCommand.cs" />
    <Compile Include="OpenMapCommand.cs" />
    <Compile Include="Call3DCameraView.cs" />
    <Compile Include="RunLogicCommand.cs" />
    <Compile Include="UserCommand.cs" />
    <Compile Include="SystemCommand.cs" />
    <Compile Include="RecipeCommand.cs" />
    <Compile Include="OpenScreenCommand.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="ReportCommand.cs" />
    <Compile Include="RunScriptCommand.cs" />
    <Compile Include="ValueCommand.cs" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\SampleApplications\SampleLibraries\Client\UA Client Library.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\WPF Ookii Dialogs\src\Ookii.Dialogs.Wpf\Ookii.Dialogs.Wpf.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\AuditTrace\AuditTrace.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommonControls\CommonControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\LightSharedResources\LightSharedResources.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Converters\Converters.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Pads\Pads.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScriptVariableValues\ScriptVariableValues.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Libraries\Opc.Ua.Client\Opc.Ua.Client.csproj" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dynamics\MSZ.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ExpressionManager\ExpressionManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAUtilities\OPCUAUtilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReportAlarmStatisticsExecuter\ReportAlarms.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReportParameters\ReportParameters.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReportSettings\ReportSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslationHelpers\TranslationHelpers.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFRecipeExecutionContext\UFRecipeExecutionContext.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UserModel\UFUserModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Page Include="PropertyDataTemplate\ChangeCulturePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\CommandSettingsPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\CommandsPropertyEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\MenuUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\RecipeUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ReportUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ScreenParameterUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\LogicUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ScriptUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\VoiceNamePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ScreenUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\CommonCommandPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\EditMethodCallParameters.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControls\ListCultures.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControls\UnlockUser.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>