//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtherNetIP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtherNetIP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: {0}, Data Size: {1}, Offset: {2}.
        /// </summary>
        internal static string AddressInfo {
            get {
                return ResourceManager.GetString("AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPUSlot out of Range. Must be between 0 and {0}.
        /// </summary>
        internal static string CPUSlotOutOfRange {
            get {
                return ResourceManager.GetString("CPUSlotOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address is not a valid Allen-Bradley notation.
        /// </summary>
        internal static string ErrorAddressInvalid {
            get {
                return ResourceManager.GetString("ErrorAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address specified not requires a sub-element .
        /// </summary>
        internal static string ErrorAddressSubelemNotRequired {
            get {
                return ResourceManager.GetString("ErrorAddressSubelemNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address specified requires a sub-element (/ACC  or /PRE).
        /// </summary>
        internal static string ErrorAddressSubelemRequired {
            get {
                return ResourceManager.GetString("ErrorAddressSubelemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Address incompatible with AB address.
        /// </summary>
        internal static string ErrorAddressType {
            get {
                return ResourceManager.GetString("ErrorAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type incompatible with the &quot;Plc Type&quot; of the Station.
        /// </summary>
        internal static string ErrorAddressTypeIncompatibleStation {
            get {
                return ResourceManager.GetString("ErrorAddressTypeIncompatibleStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Status information:.
        /// </summary>
        internal static string ErrorAddStsInfo {
            get {
                return ResourceManager.GetString("ErrorAddStsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Analyze the reply header.
        /// </summary>
        internal static string ErrorAnalyzeTheReplyHeader {
            get {
                return ResourceManager.GetString("ErrorAnalyzeTheReplyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean array is not accepted for a Boolean address (Tags: {0}).
        /// </summary>
        internal static string ErrorBooleanArrayIsNotAcceptMicro800 {
            get {
                return ResourceManager.GetString("ErrorBooleanArrayIsNotAcceptMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Check the reply service code.
        /// </summary>
        internal static string ErrorCheckTheReplyServiceCode {
            get {
                return ResourceManager.GetString("ErrorCheckTheReplyServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Check the status.
        /// </summary>
        internal static string ErrorCheckTheStatus {
            get {
                return ResourceManager.GetString("ErrorCheckTheStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: received answer with wrong LRC/CRC..
        /// </summary>
        internal static string ErrorCRCError {
            get {
                return ResourceManager.GetString("ErrorCRCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Data parsing.
        /// </summary>
        internal static string ErrorDataParsing {
            get {
                return ResourceManager.GetString("ErrorDataParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enbedded error Generl status: {0} and Extended Status: {1} Tagname: {2} .
        /// </summary>
        internal static string ErrorEnbeddedError {
            get {
                return ResourceManager.GetString("ErrorEnbeddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enbedded error.
        /// </summary>
        internal static string ErrorEnbeddedStation {
            get {
                return ResourceManager.GetString("ErrorEnbeddedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender issued an invalid or unsupported encapsulation command.
        /// </summary>
        internal static string ErrorEncapStatus1 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory resources in the receiver to handle the command.
        /// </summary>
        internal static string ErrorEncapStatus2 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poorly formed or incorrect data in the data portion of the encapsulation message.
        /// </summary>
        internal static string ErrorEncapStatus3 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An originator used an invalid session handle when sending an encapsulation message to the target.
        /// </summary>
        internal static string ErrorEncapStatus64 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target received a message of invalid length.
        /// </summary>
        internal static string ErrorEncapStatus65 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported encapsulation protocol revision.
        /// </summary>
        internal static string ErrorEncapStatus69 {
            get {
                return ResourceManager.GetString("ErrorEncapStatus69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job exceed the maximum size (Tags: {0}).
        /// </summary>
        internal static string ErrorExcedeJobMicro800 {
            get {
                return ResourceManager.GetString("ErrorExcedeJobMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field has an illegal value.
        /// </summary>
        internal static string ErrorEXTSTS01 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less levels specified in address than minimum for any address.
        /// </summary>
        internal static string ErrorEXTSTS02 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More levels specified in address than system supports.
        /// </summary>
        internal static string ErrorEXTSTS03 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol not found.
        /// </summary>
        internal static string ErrorEXTSTS04 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol is of improper format.
        /// </summary>
        internal static string ErrorEXTSTS05 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address doesn&apos;t point to something usable.
        /// </summary>
        internal static string ErrorEXTSTS06 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is wrong size.
        /// </summary>
        internal static string ErrorEXTSTS07 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete request, situation has changed since the start of the command.
        /// </summary>
        internal static string ErrorEXTSTS08 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data or file is too large.
        /// </summary>
        internal static string ErrorEXTSTS09 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction size plus word address is too large.
        /// </summary>
        internal static string ErrorEXTSTS0A {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied, improper privilege.
        /// </summary>
        internal static string ErrorEXTSTS0B {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition cannot be generated - resource is not available.
        /// </summary>
        internal static string ErrorEXTSTS0C {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition already exists - resource is already available.
        /// </summary>
        internal static string ErrorEXTSTS0D {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command cannot be executed.
        /// </summary>
        internal static string ErrorEXTSTS0E {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram overflow.
        /// </summary>
        internal static string ErrorEXTSTS0F {
            get {
                return ResourceManager.GetString("ErrorEXTSTS0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        internal static string ErrorEXTSTS10 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal data type.
        /// </summary>
        internal static string ErrorEXTSTS11 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter or invalid data.
        /// </summary>
        internal static string ErrorEXTSTS12 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address reference exists to deleted area.
        /// </summary>
        internal static string ErrorEXTSTS13 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command execution failure for unknown reason; possible PLC3 histogram overflow.
        /// </summary>
        internal static string ErrorEXTSTS14 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conversion error.
        /// </summary>
        internal static string ErrorEXTSTS15 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner not able to communicate with 1771 rack adapter.
        /// </summary>
        internal static string ErrorEXTSTS16 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type mismatch.
        /// </summary>
        internal static string ErrorEXTSTS17 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1771 module response was not valid.
        /// </summary>
        internal static string ErrorEXTSTS18 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated label.
        /// </summary>
        internal static string ErrorEXTSTS19 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is open; another node owns it.
        /// </summary>
        internal static string ErrorEXTSTS1A {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another node is the program owner.
        /// </summary>
        internal static string ErrorEXTSTS1B {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ErrorEXTSTS1C {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string ErrorEXTSTS1D {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table element protection violation.
        /// </summary>
        internal static string ErrorEXTSTS1E {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary internal problem.
        /// </summary>
        internal static string ErrorEXTSTS1F {
            get {
                return ResourceManager.GetString("ErrorEXTSTS1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Extended Status code!.
        /// </summary>
        internal static string ErrorEXTSTS20 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Extended Status code!.
        /// </summary>
        internal static string ErrorEXTSTS21 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote rack fault.
        /// </summary>
        internal static string ErrorEXTSTS22 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string ErrorEXTSTS23 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string ErrorEXTSTS24 {
            get {
                return ResourceManager.GetString("ErrorEXTSTS24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device returned an EXT STS error code .
        /// </summary>
        internal static string ErrorEXTSTSCodeExt {
            get {
                return ResourceManager.GetString("ErrorEXTSTSCodeExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of types DataFile is invalid for Micro800 series . (Tag: {0} ).
        /// </summary>
        internal static string ErrorInvalidAddressMicro800 {
            get {
                return ResourceManager.GetString("ErrorInvalidAddressMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag Format is invalid for Micro800 series . (Tag: {0} Data Type: {1}).
        /// </summary>
        internal static string ErrorInvalidFormatMicro800 {
            get {
                return ResourceManager.GetString("ErrorInvalidFormatMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Type is invalid for the selected station. (Tag: {0} File Type: {1}).
        /// </summary>
        internal static string ErrorInvalidStationMicro800 {
            get {
                return ResourceManager.GetString("ErrorInvalidStationMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Type is invalid for the selected station. (Tag: {0} File Type: {1}).
        /// </summary>
        internal static string ErrorInvalidTypeForStation {
            get {
                return ResourceManager.GetString("ErrorInvalidTypeForStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag type is invalid for its Data Type. (Tag: {0} Data Type: {1}).
        /// </summary>
        internal static string ErrorInvalidTypeTagMicro800 {
            get {
                return ResourceManager.GetString("ErrorInvalidTypeTagMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job not contain tag.
        /// </summary>
        internal static string ErrorJobEmptyMicro800 {
            get {
                return ResourceManager.GetString("ErrorJobEmptyMicro800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the driver settings, error &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorLoadingDriverSettings {
            get {
                return ResourceManager.GetString("ErrorLoadingDriverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message Router in the target device returned an error status code: {0}  Hex.
        /// </summary>
        internal static string ErrorMRStatus {
            get {
                return ResourceManager.GetString("ErrorMRStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply  with only header.
        /// </summary>
        internal static string ErrorNoRep {
            get {
                return ResourceManager.GetString("ErrorNoRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More data than expected has been received, communication is out of sync.
        /// </summary>
        internal static string ErrorOutOfSync {
            get {
                return ResourceManager.GetString("ErrorOutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error over run.
        /// </summary>
        internal static string ErrorOverRun {
            get {
                return ResourceManager.GetString("ErrorOverRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Device&apos;s register session failed.
        /// </summary>
        internal static string ErrorRegisterSession {
            get {
                return ResourceManager.GetString("ErrorRegisterSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with Data Type unknown.
        /// </summary>
        internal static string ErrorRepDataType {
            get {
                return ResourceManager.GetString("ErrorRepDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with wrong service code .
        /// </summary>
        internal static string ErrorRepSerCode {
            get {
                return ResourceManager.GetString("ErrorRepSerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with a wrong number of replied services.
        /// </summary>
        internal static string ErrorRepSerNum {
            get {
                return ResourceManager.GetString("ErrorRepSerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error status code..
        /// </summary>
        internal static string ErrorRepStatus {
            get {
                return ResourceManager.GetString("ErrorRepStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received tag size is not correct.
        /// </summary>
        internal static string ErrorRepTagSize {
            get {
                return ResourceManager.GetString("ErrorRepTagSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with over data than expected.
        /// </summary>
        internal static string ErrorRepTooLong {
            get {
                return ResourceManager.GetString("ErrorRepTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with less data than expected.
        /// </summary>
        internal static string ErrorRepTooShort {
            get {
                return ResourceManager.GetString("ErrorRepTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device returned a non-zero status code in the response packet.
        /// </summary>
        internal static string ErrorStatusNotZero {
            get {
                return ResourceManager.GetString("ErrorStatusNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string&apos;s length specified into address exceed the maximum size ({0} chars).
        /// </summary>
        internal static string ErrorStringLengthOutOfRange {
            get {
                return ResourceManager.GetString("ErrorStringLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address specified requires a maximum length of the string.
        /// </summary>
        internal static string ErrorStringLengthRequired {
            get {
                return ResourceManager.GetString("ErrorStringLengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station cannot buffer command!.
        /// </summary>
        internal static string ErrorSTSCode01 {
            get {
                return ResourceManager.GetString("ErrorSTSCode01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link layer timeout or received NAK!.
        /// </summary>
        internal static string ErrorSTSCode02 {
            get {
                return ResourceManager.GetString("ErrorSTSCode02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate token holder detected!.
        /// </summary>
        internal static string ErrorSTSCode03 {
            get {
                return ResourceManager.GetString("ErrorSTSCode03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port is disconnected!.
        /// </summary>
        internal static string ErrorSTSCode04 {
            get {
                return ResourceManager.GetString("ErrorSTSCode04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application layer timeout!.
        /// </summary>
        internal static string ErrorSTSCode05 {
            get {
                return ResourceManager.GetString("ErrorSTSCode05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate node detected!.
        /// </summary>
        internal static string ErrorSTSCode06 {
            get {
                return ResourceManager.GetString("ErrorSTSCode06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station is off-line!.
        /// </summary>
        internal static string ErrorSTSCode07 {
            get {
                return ResourceManager.GetString("ErrorSTSCode07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware fault!.
        /// </summary>
        internal static string ErrorSTSCode08 {
            get {
                return ResourceManager.GetString("ErrorSTSCode08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused error code!.
        /// </summary>
        internal static string ErrorSTSCode09Spare {
            get {
                return ResourceManager.GetString("ErrorSTSCode09Spare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Command or Format!.
        /// </summary>
        internal static string ErrorSTSCode10 {
            get {
                return ResourceManager.GetString("ErrorSTSCode10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host has a problem and will not comunicate!.
        /// </summary>
        internal static string ErrorSTSCode20 {
            get {
                return ResourceManager.GetString("ErrorSTSCode20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote node host is missing, disconnected, or shut down!.
        /// </summary>
        internal static string ErrorSTSCode30 {
            get {
                return ResourceManager.GetString("ErrorSTSCode30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host could not complete function due to hardware fault!.
        /// </summary>
        internal static string ErrorSTSCode40 {
            get {
                return ResourceManager.GetString("ErrorSTSCode40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressing problem or memory protect rungs!.
        /// </summary>
        internal static string ErrorSTSCode50 {
            get {
                return ResourceManager.GetString("ErrorSTSCode50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function disallowed due to command protection selection!.
        /// </summary>
        internal static string ErrorSTSCode60 {
            get {
                return ResourceManager.GetString("ErrorSTSCode60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor is in program mode.
        /// </summary>
        internal static string ErrorSTSCode70 {
            get {
                return ResourceManager.GetString("ErrorSTSCode70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility mode file is missing or comunication zone problem !.
        /// </summary>
        internal static string ErrorSTSCode80 {
            get {
                return ResourceManager.GetString("ErrorSTSCode80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote node cannot buffer command!.
        /// </summary>
        internal static string ErrorSTSCode90 {
            get {
                return ResourceManager.GetString("ErrorSTSCode90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait ACK (1775-KA buffer full).
        /// </summary>
        internal static string ErrorSTSCodeA0 {
            get {
                return ResourceManager.GetString("ErrorSTSCodeA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote node problem due to download!.
        /// </summary>
        internal static string ErrorSTSCodeB0 {
            get {
                return ResourceManager.GetString("ErrorSTSCodeB0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait ACK (1775-KA buffer full).
        /// </summary>
        internal static string ErrorSTSCodeC0 {
            get {
                return ResourceManager.GetString("ErrorSTSCodeC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused error code!.
        /// </summary>
        internal static string ErrorSTSCodeD0 {
            get {
                return ResourceManager.GetString("ErrorSTSCodeD0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused error code!.
        /// </summary>
        internal static string ErrorSTSCodeE0 {
            get {
                return ResourceManager.GetString("ErrorSTSCodeE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status code received from Encapsulation Layer: {0:X2} hex..
        /// </summary>
        internal static string ErrorUnknEncapStatus {
            get {
                return ResourceManager.GetString("ErrorUnknEncapStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status code received: {0:X2} hex..
        /// </summary>
        internal static string ErrorUnknSTSCode {
            get {
                return ResourceManager.GetString("ErrorUnknSTSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Extended Status code received:  {0} hex..
        /// </summary>
        internal static string ErrorUnknSTSEXTCode {
            get {
                return ResourceManager.GetString("ErrorUnknSTSEXTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Message Router Reply code: {0} Hex..
        /// </summary>
        internal static string ErrorWrongMRServiceReplyCode {
            get {
                return ResourceManager.GetString("ErrorWrongMRServiceReplyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected PCCC Response code: {0} Hex..
        /// </summary>
        internal static string ErrorWrongPCCCRespCode {
            get {
                return ResourceManager.GetString("ErrorWrongPCCCRespCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong transaction number received from PLC!.
        /// </summary>
        internal static string ErrorWrongTransaction {
            get {
                return ResourceManager.GetString("ErrorWrongTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected values for the parameters &quot;Plc Type&quot;, &quot;CPU Slot&quot; and &quot;Channel&quot; are already used in another station. Please, change the value of at least one of these parameters.
        /// </summary>
        internal static string EtherNetIPStationErrorDuplicatedStation {
            get {
                return ResourceManager.GetString("EtherNetIPStationErrorDuplicatedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Address Ok.
        /// </summary>
        internal static string ParseAddressOk {
            get {
                return ResourceManager.GetString("ParseAddressOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Address.
        /// </summary>
        internal static string ParseKo {
            get {
                return ResourceManager.GetString("ParseKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC device status field : 0x{0:X} 0x{1:x}.
        /// </summary>
        internal static string PLCDeviceStatusField {
            get {
                return ResourceManager.GetString("PLCDeviceStatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC firmware : {0}.{1}.
        /// </summary>
        internal static string PLCFirmware {
            get {
                return ResourceManager.GetString("PLCFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC product name : {0}.
        /// </summary>
        internal static string PLCProductName {
            get {
                return ResourceManager.GetString("PLCProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC serial number : {0}.
        /// </summary>
        internal static string PLCSerialNumber {
            get {
                return ResourceManager.GetString("PLCSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC Status PollingTime out of Range. Must be between 0 and {0}.
        /// </summary>
        internal static string PLCStatusPollingTimeOutOfRange {
            get {
                return ResourceManager.GetString("PLCStatusPollingTimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Warning: station {0} returned error code {1} getting physical address of the program with instance {2} &quot;.
        /// </summary>
        internal static string WARNRUNGETPROGRAMADD {
            get {
                return ResourceManager.GetString("WARNRUNGETPROGRAMADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: station {0} returned error code {1} getting physical address of program {2}.
        /// </summary>
        internal static string WARNRUNPROGRAMTRUEINST {
            get {
                return ResourceManager.GetString("WARNRUNPROGRAMTRUEINST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: station {0} returned error code {1} getting object instances of program {2}.
        /// </summary>
        internal static string WARNRUNPROGRAMVARINST {
            get {
                return ResourceManager.GetString("WARNRUNPROGRAMVARINST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: station {0} returned error code {1} getting structure infos of the template with instance {2}.
        /// </summary>
        internal static string WARNRUNTEMPLATEINFO {
            get {
                return ResourceManager.GetString("WARNRUNTEMPLATEINFO", resourceCulture);
            }
        }
    }
}
