#region Copyright Syncfusion Inc. 2001 - 2014

// Copyright Syncfusion Inc. 2001 - 2014. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Re-distribution in any form is strictly
// prohibited. Any infringement will be prosecuted under applicable laws. 
#endregion

#if !( SyncfusionFramework1_0 || SyncfusionFramework1_1 )

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Windows.Forms.Layout;
using Syncfusion.Windows.Forms.Tools.Win32API;

namespace Syncfusion.Windows.Forms.Tools
{
    /// <summary> StatusStrip control extended. /// </summary>
    [Designer(typeof(Design.StatusStripExDesigner))]
    [System.Windows.Forms.Design.ToolStripItemDesignerAvailability(System.Windows.Forms.Design.ToolStripItemDesignerAvailability.StatusStrip)]
    [Description("Represents Office 2007 Style StatusStrip.")]
    [ToolboxBitmap(typeof(StatusStripEx), "ToolboxIcons.StatusStripEx.bmp")]
    public partial class StatusStripEx : StatusStrip, IDockExtended,IVisualStyle 
    {
        #region Constants

        private const int MARGIN = 2;

        private const int SEPARATOR_WIDTH = 2;
        private bool Inizilise = true;
        private const int MAIN_SEPARATOR_WIDTH = 3;
        private Color m_metroColor = ColorTranslator.FromHtml("#87CEFF");
        /// <summary>
        /// Default size of the control
        /// </summary>
        private Size CTRLSIZE = default(Size);
        #endregion

        #region Constructors
     
        public StatusStripEx()
            : base()
        {
            try
            {
                AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(AssemblyInfo.AssemblyResolver);
                new Syncfusion.Core.Licensing.LicensedComponent(typeof(StatusBarAdvPanel));
            }
            finally
            {
                AppDomain.CurrentDomain.AssemblyResolve -= new ResolveEventHandler(AssemblyInfo.AssemblyResolver);
            }
            base.Dock = DockStyle.None;
            CTRLSIZE = this.Size;
            m_menuStrip = new StatusContextMenuStrip(this);
            m_menuStrip.AutoGenerated = true;
            ContextMenuStrip = m_menuStrip;
        }
        #endregion

        #region Nested Classes

        #region *** StatusStripExLayoutEngine
        /// <summary>
        /// Layout engine for StatusStripEx.
        /// </summary>
        private class StatusStripExLayoutEngine : LayoutEngine
        {
            #region Overrides
            /// <summary>
            /// Lays out toolstrip items in StatusStripEx.
            /// </summary>
            /// <param name="container">Container object</param>
            /// <param name="layoutEventArgs">LayoutEventArgs that contains the event data.</param>
            /// <returns>returns bool value</returns>
            public override bool Layout(object container, LayoutEventArgs layoutEventArgs)
            {
                StatusStripEx parent = (StatusStripEx)container;

                int iParentHeight = parent.Height;

                Rectangle rcDisplay = parent.DisplayRectangle;

                Size szDisplaySize = rcDisplay.Size;
                int iPosition = rcDisplay.Right;

                int iTop = 0;
                int iParentPaddingTop = parent.Padding.Top;
                int iParentPaddingLeft = parent.Padding.Left;

                bool bEnoughForStatusControlsItems = false;

                // Locate StatusControlsItems items.
                for (int i = parent.StatusControlsItems.Count - 1; i >= 0; i--)
                {
                    ToolStripItem item = parent.StatusControlsItems[i];

                    if (item != null && item.Owner != null)
                    {
                        iTop = item.Margin.Top + iParentPaddingTop;

                        if (item.AutoSize)
                        {
                            item.Size = item.GetPreferredSize(szDisplaySize);
                            iTop = (iParentHeight - item.Height) / 2;
                        }

                        int len = iParentPaddingLeft + item.Width;

                        if (item.Available)
                        {
                            if (iPosition <= len || bEnoughForStatusControlsItems)
                            {
                                SetItemLocationRTL(parent, item, new Point(-item.Width - 1, iTop));
                                bEnoughForStatusControlsItems = true;
                            }
                            else
                            {
                                SetItemLocationRTL(parent, item, new Point(iPosition - item.Width, iTop));
                                iPosition -= item.Width + MARGIN;
                            }
                        }
                    }
                }

                int iLeftPosition = rcDisplay.Left;
                bool bEnoughForNotificationsItems = false;

                // Locate NotificationsItems that represent IStatusItem interface.
                for (int i = 0, count = parent.NotificationsItems.Count; i < count; i++)
                {
                    ToolStripItem item = parent.NotificationsItems[i];

                    if (item != null && item.Owner != null)
                    {
                        iTop = item.Margin.Top + iParentPaddingTop;

                        if (item.AutoSize)
                        {
                            item.Size = item.GetPreferredSize(szDisplaySize);
                            iTop = (iParentHeight - item.Height) / 2;
                        }

                        bool bIsEndOfGroup = false;

                        IStatusItem statusItem = item as IStatusItem;

                        if (statusItem != null)
                        {
                            bIsEndOfGroup = statusItem.EndOfGroup;
                        }

                        if (item.Available)
                        {
                            if ((iLeftPosition + item.Width < iPosition - MAIN_SEPARATOR_WIDTH)
                                && !bEnoughForNotificationsItems
                                && !bEnoughForStatusControlsItems)
                            {
                                SetItemLocationRTL(parent, item, new Point(iLeftPosition, iTop));
                                iLeftPosition += item.Width + SEPARATOR_WIDTH;
                            }
                            else
                            {
                                SetItemLocationRTL(parent, item, new Point(-item.Width - 1, iTop));
                                bEnoughForNotificationsItems = true;
                            }
                        }

                        // Add separator.
                        if (bIsEndOfGroup && !bEnoughForNotificationsItems && parent.Separators != null)
                        {
                            AddSeparatorsPositionRTL(parent, iLeftPosition - SEPARATOR_WIDTH);
                        }
                    }
                }

                // Add main separator.
                SetSeparatorPositionRTL(parent, iPosition - MAIN_SEPARATOR_WIDTH);

                return parent.AutoSize;
            }
            #endregion

            #region Implementation
            /// <summary> Set item location depending on RTL property. </summary>
            /// <param name="parent">Status Strip</param>
            /// <param name="item">Toolstrip Item</param>
            /// <param name="location">Location point</param>
            private void SetItemLocationRTL(StatusStripEx parent, ToolStripItem item, Point location)
            {
                if (parent.RightToLeft == RightToLeft.No)
                {
                    parent.SetItemLocation(item, location);
                }
                else
                {
                    if (location.X > 0)
                    {
                        Point newLocation = new Point(parent.Width - location.X - item.Width + parent.DisplayRectangle.X, location.Y);

                        parent.SetItemLocation(item, newLocation);
                    }
                    else
                    {
                        parent.SetItemLocation(item, location);
                    }
                }
            }

            /// <summary> Set main separator location depending on RTL property. </summary>
            /// <param name="parent">Sgtatus Strip</param>
            /// <param name="position">Separator position</param>
            private void SetSeparatorPositionRTL(StatusStripEx parent, int position)
            {
                if (parent.RightToLeft == RightToLeft.No)
                {
                    parent.SeparatorPosition = (position > 0) ? position : 0;
                }
                else
                {
                    parent.SeparatorPosition = (position > 0) ? parent.Width - position - MAIN_SEPARATOR_WIDTH + parent.DisplayRectangle.X : 0;
                }
            }

            /// <summary> Set separator position and add it to list depending on RTL property. </summary>
            /// <param name="parent">Status StripEx</param>
            /// <param name="position">Separator position</param>
            private void AddSeparatorsPositionRTL(StatusStripEx parent, int position)
            {
                if (parent.RightToLeft == RightToLeft.No)
                {
                    parent.Separators.Add(position);
                }
                else
                {
                    parent.Separators.Add(parent.Width - position - SEPARATOR_WIDTH + parent.DisplayRectangle.X);
                }
            }
            #endregion
        }
        #endregion

        #region *** GripWindow
   
       public class GripWindow : NativeWindow
        {
            #region Constructor
         
            public GripWindow(Control control)
            {
                m_control = control;
                AssignHandle(m_control.Handle);
            }
            #endregion

            #region Overrides
            protected override void WndProc(ref Message m)
            {
                switch ((Msg)m.Msg)
                {
                    case Msg.WM_PAINT:
                        StatusStripEx statusStrip = m_control.Parent as StatusStripEx;
                        if (statusStrip != null)
                        {
                            PAINTSTRUCT paintSt = new PAINTSTRUCT();
                            IntPtr hdc = WindowsAPI.BeginPaint(m.HWnd, ref paintSt);

                            using (Graphics g = Graphics.FromHdc(hdc))
                            {
                                Point pt = m_control.Location;
                                g.TranslateTransform(-(pt.X + 1), -pt.Y);

                                ToolStripRenderEventArgs ea = new ToolStripRenderEventArgs(g, statusStrip);
                                ToolStripRenderer renderer = statusStrip.Renderer;

                                renderer.DrawToolStripBackground(ea);
                                renderer.DrawStatusStripSizingGrip(ea);
                            }
                            WindowsAPI.EndPaint(m.HWnd, ref paintSt);

                            m.Result = IntPtr.Zero;
                            return;
                        }
                        break;
                }
                base.WndProc(ref m);
            }
            #endregion

            #region Fields
           private Control m_control;
            #endregion
        }
        #endregion

        #endregion

        #region Overrides
        protected override void OnHandleDestroyed(EventArgs e)
        {
            if (m_notificationsItems != null)
            {
                m_notificationsItems.Clear();
                m_notificationsItems = null;
            }
            if (m_statusControlsItems != null)
            {
                m_statusControlsItems.Clear();
                m_statusControlsItems = null;
            }
            base.OnHandleDestroyed(e);
        }

        protected override void Dispose(bool disposing)
        {
            m_bDisposing = true;

            if (disposing)
            {
                if (this.m_menuStrip != null)
                {
                    this.m_menuStrip.StatusStrip = null;
                    this.m_menuStrip.Dispose();
                    this.m_menuStrip = null;
                }

                if (m_separators != null)
                {
                    m_separators.Clear();
                    m_separators = null;
                }

                this.ContextMenuStrip = null;
                
                this.Renderer = null;
                
                office12_color_table_mgdColors = null;
                
                m_layoutEngine = null;
            }

            base.Dispose(disposing);
            base.DestroyHandle();

            m_bDisposing = false;
        }

        /// <summary>
        /// Retrieves the size of a rectangular area into which a control can be fitted. 
        /// </summary>
        /// <param name="proposedSize">Proposed size</param>
        /// <returns> Returns Size</returns>
        [Description("Retrieves the size of a rectangular area into which a control can be fitted.")]
        public override Size GetPreferredSize(Size proposedSize)
        {
            Size szDefault = this.DefaultSize - this.Padding.Size;

            int width = MAIN_SEPARATOR_WIDTH;
            int height = szDefault.Height;

            ToolStripItemCollection controlsItems = this.StatusControlsItems;

            int controlsCount = controlsItems.Count;
            if (controlsCount > 0)
            {
                for (int i = 0, count = controlsCount; i < count; i++)
                {
                    ToolStripItem item = controlsItems[i];
                    if (item != null && item.Available)
                    {
                        Size szItem = item.AutoSize ? item.GetPreferredSize(Size.Empty) : item.Size;

                        width += szItem.Width + MARGIN;
                        height = Math.Max(height, szItem.Height + item.Margin.Vertical);
                    }
                }
            }

            ToolStripItemCollection notificationsItems = this.NotificationsItems;

            int notificationsCount = notificationsItems.Count;
            if (notificationsCount > 0)
            {
                for (int i = 0, count = notificationsCount; i < count; i++)
                {
                    ToolStripItem item = notificationsItems[i];
                    if (item != null && item.Available)
                    {
                        Size szItem = item.AutoSize ? item.GetPreferredSize(Size.Empty) : item.Size;

                        width += szItem.Width + SEPARATOR_WIDTH;
                        height = Math.Max(height, szItem.Height + item.Margin.Vertical);
                    }
                }
            }
            else
            {
                if (width < szDefault.Width)
                {
                    width = szDefault.Width;
                }
            }

            return new Size(width + this.Padding.Horizontal, height + this.Padding.Vertical);
        }
 
        protected override void OnLayout(LayoutEventArgs lea)
        {
            // Clear items to refill its values in base Layout.
            if (m_notificationsItems != null)
                m_notificationsItems.Clear();
            if (m_statusControlsItems != null)
                m_statusControlsItems.Clear();

            // Clears separators positions.
            if (m_separators != null)
                m_separators.Clear();

            m_mainSeparatorPosition = -1;

            base.OnLayout(lea);
        }

        protected override void SetBoundsCore(int x, int y, int width, int height, BoundsSpecified specified)
        {
            RibbonForm form = this.Parent as RibbonForm;

            if (form != null)
            {
                switch (this.Dock)
                {
                    case DockStyleEx.BottomMost:
                        width = form.DisplayRectangle.Width;
                        break;
                    case DockStyleEx.TopMost:
                        width = form.ClientRectangle.Width - 2;
                        break;
                }
            }

            base.SetBoundsCore(x, y, width, height, specified);
        }
       
        protected override void OnSizeChanged(EventArgs e)
        {
            if (!EnableTouchMode && this.DesignMode)
                CTRLSIZE = this.Size;
            base.OnSizeChanged(e);
        }
      
        protected override void OnParentChanged(EventArgs e)
        {
            base.OnParentChanged(e);
            if (!m_bDisposing)
            {
                if (Inizilise)
                    Inizilise = false;
                if (this.VisualStyle == StatusStripExStyle.Default)
                {
                    UpdateRenderer();
                }
                else
                {
                    UpdateMetroRenderer();
                }
            }
            else
                UpdateRenderer(true);
        }

        protected override void OnRendererChanged(EventArgs e)
        {
            if (!m_bDisposing)
            {
                if (!(this.Renderer is MetroStatusStripExRenderer))
                {
                    if (this.VisualStyle == StatusStripExStyle.Default)
                    {
                        if (!(this.Renderer is StatusStripExRenderer))
                            UpdateRenderer();
                    }
                    else
                    {
                        UpdateMetroRenderer();
                    }
                }
            }

            else
                UpdateRenderer(true);

            base.OnRendererChanged(e);
        }
   
        protected override void OnControlAdded(ControlEventArgs e)
        {
            Control c = e.Control;
            if (c.GetType().Name == "RightToLeftLayoutGrip")
            {
                GripWindow wnd = new GripWindow(c);
            }
            base.OnControlAdded(e);
        }
        
        protected override void WndProc(ref Message m)
        {
            switch ((Msg)m.Msg)
            {
                case Msg.WM_NCHITTEST:
                    if (OnNcHitTest(ref m)) return;
                    break;
            }
            base.WndProc(ref m);
        }
        #endregion

        #region Properties
        /// <summary>
        /// Gets or sets which control borders are docked to its parent control and determines how a control is resized with its parent.
        /// </summary>
        /// <value></value>
        /// <returns>One of the <see cref="T:System.Windows.Forms.DockStyle"></see> values. The default is <see cref="F:System.Windows.Forms.DockStyle.None"></see>.</returns>
        [DefaultValue(typeof(DockStyleEx), "BottomMost")]
        [Description("Gets or sets which control borders are docked to its parent control and determines how a control is resized with its parent.")]
        public new DockStyleEx Dock
        {
            get
            {
                return m_dock;
            }
            set
            {
                if (m_dock != value)
                {
                    m_dock = value;

                    DockStyle baseDock;

                    switch (value)
                    {
                        case DockStyleEx.Top:
                            baseDock = DockStyle.Top;
                            break;
                        case DockStyleEx.Bottom:
                            baseDock = DockStyle.Bottom;
                            break;
                        case DockStyleEx.Left:
                            baseDock = DockStyle.Left;
                            break;
                        case DockStyleEx.Right:
                            baseDock = DockStyle.Right;
                            break;
                        case DockStyleEx.Fill:
                            baseDock = DockStyle.Fill;
                            break;
                        default:
                            baseDock = DockStyle.None;
                            break;
                    }
                    base.Dock = baseDock;
                }
            }
        }

        /// <summary>
        /// Gets items that located in left side of StatusStrip and not
        /// represent IStatusItem interface.
        /// </summary>
        internal ToolStripItemCollection StatusControlsItems
        {
            get
            {
                if (m_statusControlsItems == null)
                    m_statusControlsItems = new ToolStripItemCollection(this, new ToolStripItem[] { });

                if (m_statusControlsItems.Count == 0)
                {
                    for (int i = 0; i < this.Items.Count; i++)
                    {
                        if (!(this.Items[i] is IStatusItem))
                        {
                            m_statusControlsItems.Add(this.Items[i]);
                        }
                    }
                }

                return m_statusControlsItems;
            }
        }

        /// <summary>
        /// Gets items that located in right side of StatusStrip and
        /// represent IStatusItem interface.
        /// </summary>
        internal ToolStripItemCollection NotificationsItems
        {
            get
            {
                if (m_notificationsItems == null)
                    m_notificationsItems = new ToolStripItemCollection(this, new ToolStripItem[] { });

                if (m_notificationsItems.Count == 0)
                {
                    for (int i = 0; i < this.Items.Count; i++)
                    {
                        if (this.Items[i] is IStatusItem)
                        {
                            m_notificationsItems.Add(this.Items[i]);
                        }
                    }
                }

                return m_notificationsItems;
            }
        }
     
        internal List<int> Separators
        {
            get
            {
                return m_separators;
            }
        }

        /// <summary>
        /// Gets or sets separator position that divide StatusStripEx on two areas.
        /// </summary>
        internal int SeparatorPosition
        {
            get
            {
                return m_mainSeparatorPosition;
            }
            set
            {
                m_mainSeparatorPosition = value;
            }
        }

        /// <summary>
        /// Gets the area where Status controls are located.
        /// </summary>
        [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
        [Description("Gets the area where Status controls are located")]
        public Rectangle StatusControlsArea
        {
            get
            {
                if (m_mainSeparatorPosition != -1)
                {
                    if (RightToLeft == RightToLeft.Yes)
                    {
                        m_statusControlsArea = new Rectangle(Point.Empty, new Size(m_mainSeparatorPosition, Height));
                    }
                    else
                    {
                        m_statusControlsArea = new Rectangle(new Point(m_mainSeparatorPosition + MAIN_SEPARATOR_WIDTH, 0), new Size(Width - m_mainSeparatorPosition, Height));
                    }
                }
                else
                {
                    m_statusControlsArea = Rectangle.Empty;
                }

                return m_statusControlsArea;
            }
        }

        /// <summary>
        /// Gets area where Notifications controls painting.
        /// </summary>
        internal Rectangle NotificationslArea
        {
            get
            {
                if (m_mainSeparatorPosition != -1)
                {
                    if (RightToLeft == RightToLeft.Yes)
                    {
                        m_notificationslArea = new Rectangle(new Point(m_mainSeparatorPosition + MAIN_SEPARATOR_WIDTH, 0), new Size(Width - m_mainSeparatorPosition, Height));
                    }
                    else
                    {
                        m_notificationslArea = new Rectangle(Point.Empty, new Size(m_mainSeparatorPosition, Height));
                    }
                }
                else
                {
                    m_notificationslArea = Rectangle.Empty;
                }

                return m_notificationslArea;
            }
        }
        /// <summary>
        /// Get or Set of Skin Manager Interface
        /// </summary>
        private string style;
        string IVisualStyle.VisualTheme
        {
            get
            {
                return style;
            }
            set
            {
                style = value;

                if (value == "Office2007Blue")
                    OfficeColorScheme = ToolStripEx.ColorScheme.Blue;
                else if (value == "Office2007Silver")
                    OfficeColorScheme = ToolStripEx.ColorScheme.Silver;
                else if (value == "Office2007Black")
                    OfficeColorScheme = ToolStripEx.ColorScheme.Black;
                else if (value == "Managed")
                    OfficeColorScheme = ToolStripEx.ColorScheme.Managed;
                else if (value == "Metro")
                    this.VisualStyle=StatusStripExStyle.Metro;

            }
        }
        /// <summary>
        /// Gets or sets whether the Office color scheme should be Silver or Blue.
        /// </summary>
        [Description("Specifies the color scheme (Silver, Blue).")]
        public virtual ToolStripEx.ColorScheme OfficeColorScheme
        {
            get
            {
                if (m_colorScheme == ToolStripEx.ColorScheme.Default)
                {
                    RibbonForm form = this.Parent as RibbonForm;
                    return form != null ? GetOfficeColorScheme(form.ColorScheme) : ToolStripEx.ColorScheme.Managed;
                }

                return m_colorScheme;
            }
            set
            {
                if (m_colorScheme != value)
                {
                    m_colorScheme = value;
                    if (this.VisualStyle == StatusStripExStyle.Default)
                    UpdateRenderer();
                    Invalidate(false);
                    if (!Inizilise)
                        ResetBackColor();
                }
            }
        }

        /// <summary>
        /// Gets or sets an advanced appearance for the StatusStripEx.
        /// </summary>
        [Description("Gets or sets an advanced appearance for the StatusStripEx.")]
        [Category("Appearance")]
        [DefaultValue(StatusStripExStyle.Default)]
        public StatusStripExStyle VisualStyle
        {
            get
            {
                return this.stripExstyle;
            }
            set
            {
                if (this.stripExstyle != value)
                {
                    this.stripExstyle = value;
                    if (this.VisualStyle == StatusStripExStyle.Metro)
                    {
                        this.UpdateMetroRenderer();
                    }
                    else
                    {
                        this.UpdateRenderer();
                    }
                    this.Invalidate();
                }
            }
        }
        /// <summary>
        /// Gets or sets the theme color of the ColorUI
        /// </summary>
        [
        Browsable(true),
        Category("MetroColor"),
        RefreshProperties(RefreshProperties.Repaint),
        Description("Gets or sets the pressed background color of the control.")
        ]
        public Color MetroColor
        {
            get { return m_metroColor; }
            set
            {
                m_metroColor = value;
                UpdateMetroRenderer();
            }
        }
        /// <summary>
        /// Gets a cached instance of the control's layout engine.
        /// </summary>
        public override LayoutEngine LayoutEngine
        {
            get
            {
                if (m_layoutEngine == null)
                    m_layoutEngine = new StatusStripExLayoutEngine();

                return m_layoutEngine;
            }
        }

        /// <summary>
        /// Gets or sets the context menu strip associated with this control. (overridden property)
        /// </summary>
        public override ContextMenuStrip ContextMenuStrip
        {
            get
            {
                ContextMenuStrip menuStrip = base.ContextMenuStrip;

                if (menuStrip != null)
                {
                    return menuStrip;
                }
                else
                {
                    return m_menuStrip;
                }
            }
            set
            {
                if (value is StatusContextMenuStrip)
                {
                    StatusContextMenuStrip menuStrip = value as StatusContextMenuStrip;
                    menuStrip.StatusStrip = this;
                    base.ContextMenuStrip = menuStrip;
                }
                else
                {
                    base.ContextMenuStrip = value;
                }
            }
        }
        #region For Touch

        bool isScaling = false;
        /// <summary>
        /// Gets/Sets Control size before touch enabled
        /// </summary>
        [Browsable(false)]
        public Size BeforeTouchSize
        {
            get
            {
                return CTRLSIZE;
            }
            set
            {
                CTRLSIZE = value;
            }
        }
        bool _touchMode = false;
        /// <summary>
        /// gets or sets the touchmode
        /// </summary>
		[DefaultValue(false)]
        public virtual bool EnableTouchMode
        {
            get
            {
                return _touchMode;
            }
            set
            {
                if (_touchMode != value)
                {
                    _touchMode = value;
                    if (_touchMode)
                    {
                        this.AutoSize = false;
                        ApplyScaleToControl(1.5F);
                    }
                    else
                    {
                        this.AutoSize = true;
                        ApplyScaleToControl(1);
                    }
                }
            }
        }

        private bool ShouldSerializeEnableTouchMode()
        {
            return EnableTouchMode != false;
        }

        /// <summary></summary>
        private void ResetEnableTouchMode()
        {
            EnableTouchMode = false;
        }
        /// <summary>
        /// applies the scaling
        /// </summary>
        /// <param name="scaleFactor"></param>
        public void ApplyScaleToControl(float sf)
        {
            this.SuspendLayout();
            isScaling = true;
            this.Size = new Size((int)(CTRLSIZE.Width * sf), (int)(CTRLSIZE.Height * sf));
            isScaling = false;
            this.ResumeLayout();
            this.Invalidate();
        }
        /// <summary>
        /// Font changed event
        /// </summary>
        /// <param name="e"></param>
        protected override void OnFontChanged(EventArgs e)
        {
            base.OnFontChanged(e);
        }
        #endregion

        /// <summary>
        /// Gets or sets the Tool strip render mode.
        /// </summary>
        [Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public new ToolStripRenderMode RenderMode
        {
            get { return ToolStripRenderMode.Custom; }
            set { }
        }
        #endregion

        #region Implementation
        /// <summary> Update renderer according to choiced color scheme. </summary>
        internal void UpdateRenderer()
        {
            switch (this.OfficeColorScheme)
            {
                case ToolStripEx.ColorScheme.Managed:
                    this.Renderer = new StatusStripExRenderer(office12_color_table_mgdColors);
                    break;
                case ToolStripEx.ColorScheme.Silver:
                    this.Renderer = new StatusStripExRenderer(new Office12ColorTable());
                    break;
                case ToolStripEx.ColorScheme.Blue:
                    OfficeBlue office_Blue = new OfficeBlue();
                    this.Renderer = new StatusStripExRenderer(office_Blue);
                    break;
                case ToolStripEx.ColorScheme.Black:
                    this.Renderer = new StatusStripExRenderer(new OfficeBlack());
                    break;
            }
        }
        internal void UpdateMetroRenderer()
        {
            this.Renderer = new MetroStatusStripExRenderer(MetroColor, this.BackColor);
        }
        internal void UpdateRenderer(bool disposing)
        {
            if (disposing)
            {
                this.Renderer = null;
            }
        }
        

        /// <summary> Gets ColorScheme according to type. </summary>
        /// <param name="type">Colorscheme type</param>
        /// <returns>Returns Color Scheme</returns>
        private ToolStripEx.ColorScheme GetOfficeColorScheme(RibbonForm.ColorSchemeType type)
        {
            ToolStripEx.ColorScheme color;

            switch (type)
            {
                case RibbonForm.ColorSchemeType.Silver:
                    color = ToolStripEx.ColorScheme.Silver;
                    break;
                case RibbonForm.ColorSchemeType.Black:
                    color = ToolStripEx.ColorScheme.Black;
                    break;
                case RibbonForm.ColorSchemeType.Blue:
                    color = ToolStripEx.ColorScheme.Blue;
                    break;
                default:
                    color = ToolStripEx.ColorScheme.Managed;
                    break;
            }

            return color;
        }
        #endregion

        #region Message handlers
   
        private bool OnNcHitTest(ref Message m)
        {
            Form form = this.Parent as Form;
            if (form != null && form.TopLevel)
            {
                WindowStyles style = (WindowStyles)WindowsAPI.GetWindowLong(form.Handle, (int)SetWindowLongOffsets.GWL_STYLE);
                if ((style & (WindowStyles.WS_MAXIMIZE | WindowStyles.WS_MINIMIZE)) == 0)
                {
                    POINT pt = new POINT(WindowsAPI.GET_X_LPARAM((int)m.LParam), WindowsAPI.GET_Y_LPARAM((int)m.LParam));
                    WindowsAPI.MapWindowPoints(IntPtr.Zero, this.Handle, ref pt, 1);

                    if (this.SizingGrip && this.SizeGripBounds.Contains(pt.x, pt.y))
                    {
                        m.Result = (IntPtr)HitTest.HTBOTTOMRIGHT;
                        return true;
                    }
                }
            }
            return false;
        }
        #endregion

        #region Reset & Serialization
        /// <summary>
        /// Indicates whether the current value of the OfficeColorScheme property is to be serialized.
        /// </summary>
        /// <returns>Returns bool value</returns>
       public bool ShouldSerializeOfficeColorScheme()
        {
            return m_colorScheme != ToolStripEx.ColorScheme.Default;
        }

       public override void ResetBackColor()
       {
           this.BackColor = SystemColors.Control;
       }

        /// <summary>
        /// Resets the office color scheme.
        /// </summary>
      public void ResetOfficeColorScheme()
        {
            this.OfficeColorScheme = ToolStripEx.ColorScheme.Default;
        }
        #endregion

        #region Fields
        /// <summary> Instance of StatusStripExLayoutEngine. </summary>
        private StatusStripExLayoutEngine m_layoutEngine;

        /// <summary> Items that located in left side of StatusStrip and not
        /// represent IStatusItem interface. </summary>
        private ToolStripItemCollection m_notificationsItems;

        /// <summary> Items that located in right side of StatusStrip and
        /// represent IStatusItem interface. </summary>
        private ToolStripItemCollection m_statusControlsItems;

        /// <summary> Color scheme that used in Rendering. </summary>
        private ToolStripEx.ColorScheme m_colorScheme = ToolStripEx.ColorScheme.Default;
  
        private List<int> m_separators = new List<int>();
     
        private int m_mainSeparatorPosition = -1;

        /// <summary> Area where Status controls painting. </summary>
        private Rectangle m_statusControlsArea = Rectangle.Empty;

        /// <summary> Area where Notifications controls painting. </summary>
        private Rectangle m_notificationslArea = Rectangle.Empty;

        /// <summary> Dock value of StatusStripEx. </summary>
        private DockStyleEx m_dock = DockStyleEx.BottomMost;

        /// <summary> MenuStrip for StatusStripEx. </summary>
        private StatusContextMenuStrip m_menuStrip;

        Office12ColorTable office12_color_table_mgdColors = Office12ColorTable.ManagedColors;
    
        private bool m_bDisposing = false;
        /// <summary>
        /// Specifies an advanced appearance this control.
        /// </summary>
        private StatusStripExStyle stripExstyle = StatusStripExStyle.Default;
        #endregion
    }
    /// <summary>
    /// StatusStripEx Style
    /// </summary>
    public enum StatusStripExStyle
    {
        /// <summary>
        /// Classic appearance.
        /// </summary>
        Default,
        /// <summary>
        /// Metro-like appearance.
        /// </summary>
        Metro
    }
}

#endif
