//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverSerialExample.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriverSerialExample.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Channel.
        /// </summary>
        public static string AddChannel {
            get {
                return ResourceManager.GetString("AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Station.
        /// </summary>
        public static string AddStation {
            get {
                return ResourceManager.GetString("AddStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Station Name.
        /// </summary>
        public static string AddStationName {
            get {
                return ResourceManager.GetString("AddStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Limit.
        /// </summary>
        public static string AggregationLimit {
            get {
                return ResourceManager.GetString("AggregationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregation Threshold.
        /// </summary>
        public static string AggregationThreshold {
            get {
                return ResourceManager.GetString("AggregationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the channel &quot;{0}&quot;?.
        /// </summary>
        public static string AskDeleteChannel {
            get {
                return ResourceManager.GetString("AskDeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the station &quot;{0}&quot;?.
        /// </summary>
        public static string AskDeleteStation {
            get {
                return ResourceManager.GetString("AskDeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete channel.
        /// </summary>
        public static string CaptionDeleteChannel {
            get {
                return ResourceManager.GetString("CaptionDeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete station.
        /// </summary>
        public static string CaptionDeleteStation {
            get {
                return ResourceManager.GetString("CaptionDeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name.
        /// </summary>
        public static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Settings.
        /// </summary>
        public static string ChannelsSettings {
            get {
                return ResourceManager.GetString("ChannelsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits.
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Channel.
        /// </summary>
        public static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Station.
        /// </summary>
        public static string DeleteStation {
            get {
                return ResourceManager.GetString("DeleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTR Enable.
        /// </summary>
        public static string DTREnable {
            get {
                return ResourceManager.GetString("DTREnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Channel.
        /// </summary>
        public static string EditChannel {
            get {
                return ResourceManager.GetString("EditChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Station.
        /// </summary>
        public static string EditStation {
            get {
                return ResourceManager.GetString("EditStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Statistic.
        /// </summary>
        public static string EnableStatistic {
            get {
                return ResourceManager.GetString("EnableStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Type.
        /// </summary>
        public static string FrameType {
            get {
                return ResourceManager.GetString("FrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Code.
        /// </summary>
        public static string FunctionCode {
            get {
                return ResourceManager.GetString("FunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handshake.
        /// </summary>
        public static string Handshake {
            get {
                return ResourceManager.GetString("Handshake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ImportAddress {
            get {
                return ResourceManager.GetString("ImportAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select or enter the station name.
        /// </summary>
        public static string ImportEnterStationName {
            get {
                return ResourceManager.GetString("ImportEnterStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading file {0}: {1}.
        /// </summary>
        public static string ImportExceptionFileLoading {
            get {
                return ResourceManager.GetString("ImportExceptionFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        public static string ImportLoadFile {
            get {
                return ResourceManager.GetString("ImportLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverSerialExample - Import Editor.
        /// </summary>
        public static string ImportMsgBoxTitle {
            get {
                return ResourceManager.GetString("ImportMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ImportSelectAll {
            get {
                return ResourceManager.GetString("ImportSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string ImportSelectNone {
            get {
                return ResourceManager.GetString("ImportSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tags.
        /// </summary>
        public static string ImportTags {
            get {
                return ResourceManager.GetString("ImportTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ImportTagType {
            get {
                return ResourceManager.GetString("ImportTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tags Editor.
        /// </summary>
        public static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Opened.
        /// </summary>
        public static string KeepOpened {
            get {
                return ResourceManager.GetString("KeepOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        public static string LinkType {
            get {
                return ResourceManager.GetString("LinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retry before Error.
        /// </summary>
        public static string MaxRetryBeforeError {
            get {
                return ResourceManager.GetString("MaxRetryBeforeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output at Startup.
        /// </summary>
        public static string OutputAtStartup {
            get {
                return ResourceManager.GetString("OutputAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling in Error Time.
        /// </summary>
        public static string PollingInErrorTime {
            get {
                return ResourceManager.GetString("PollingInErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling not in Use Time.
        /// </summary>
        public static string PollingNotInUseTime {
            get {
                return ResourceManager.GetString("PollingNotInUseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTS Enable.
        /// </summary>
        public static string RTSEnable {
            get {
                return ResourceManager.GetString("RTSEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RX Timeout.
        /// </summary>
        public static string RXTimeout {
            get {
                return ResourceManager.GetString("RXTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Time.
        /// </summary>
        public static string ScheduleTime {
            get {
                return ResourceManager.GetString("ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Address.
        /// </summary>
        public static string StartAddress {
            get {
                return ResourceManager.GetString("StartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID.
        /// </summary>
        public static string StationID {
            get {
                return ResourceManager.GetString("StationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Settings.
        /// </summary>
        public static string StationsSettings {
            get {
                return ResourceManager.GetString("StationsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bits.
        /// </summary>
        public static string StopBits {
            get {
                return ResourceManager.GetString("StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Bytes.
        /// </summary>
        public static string SwapBytes {
            get {
                return ResourceManager.GetString("SwapBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Words.
        /// </summary>
        public static string SwapWords {
            get {
                return ResourceManager.GetString("SwapWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synch at Startup.
        /// </summary>
        public static string SynchAtStartup {
            get {
                return ResourceManager.GetString("SynchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnaround Delay.
        /// </summary>
        public static string TurnaroundDelay {
            get {
                return ResourceManager.GetString("TurnaroundDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Timeout.
        /// </summary>
        public static string TXTimeout {
            get {
                return ResourceManager.GetString("TXTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Time.
        /// </summary>
        public static string WaitTime {
            get {
                return ResourceManager.GetString("WaitTime", resourceCulture);
            }
        }
    }
}
