//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HilscherCifXmultiProtocol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HilscherCifXmultiProtocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address {0} out of range (max. {1}).
        /// </summary>
        public static string ErrorAddressOutOfRange {
            get {
                return ResourceManager.GetString("ErrorAddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean and String variables are not supported.
        /// </summary>
        public static string ErrorBooleanString {
            get {
                return ResourceManager.GetString("ErrorBooleanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus State OFF, field bus communication not activated.
        /// </summary>
        public static string ErrorBusStateOff {
            get {
                return ResourceManager.GetString("ErrorBusStateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilscher Driver Error Code {0:X}: {1}  .
        /// </summary>
        public static string ErrorHilscherDriverErrorCode {
            get {
                return ResourceManager.GetString("ErrorHilscherDriverErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        public static string ErrorInvalidAddress {
            get {
                return ResourceManager.GetString("ErrorInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the driver settings, error &apos;{0}&apos;.
        /// </summary>
        public static string ErrorLoadingDriverSettings {
            get {
                return ResourceManager.GetString("ErrorLoadingDriverSettings", resourceCulture);
            }
        }
    }
}
