<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk"> 
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\DocumentManagers\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\DocumentManagers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Layout.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.NavBar.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="ClientEditorControl.xaml.cs">
      <DependentUpon>ClientEditorControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\AppNameSettingsEditor.xaml.cs">
      <DependentUpon>AppNameSettingsEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\NewAppNameEditor.xaml.cs">
      <DependentUpon>NewAppNameEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="Converters\DisplayNameConverter.cs" />
    <Compile Include="MenuControls\BarCommonItems.xaml.cs">
      <DependentUpon>BarCommonItems.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\MenuControl.xaml.cs">
      <DependentUpon>MenuControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\ToolbarControl.xaml.cs">
      <DependentUpon>ToolbarControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Properties\UICommandResource.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>UICommandResource.resx</DependentUpon>
    </Compile>
    <Compile Include="TreeDocumentManagers\TreeAddressSpaceDocManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeChangedDocument.cs" />
    <Compile Include="TreeDocumentManagers\TreeGeneralSettingsDocManager.cs" />
    <Compile Include="UIGeneralCommands.cs" />
    <EmbeddedResource Include="Properties\UICommandResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UICommandResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\WPFUtilities\CryptString\CryptString.cs">
      <Link>CryptString\CryptString.cs</Link>
    </Compile>
    <Compile Include="ComponentService\ClientEditorManagerComponent.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Document\ClientDocument.cs" />
    <Compile Include="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
	</Compile>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
	<None Include="app.config">
		<SubType>Designer</SubType>
	</None>
	<None Update="Properties\Settings.settings">
		<Generator>SettingsSingleFileGenerator</Generator>
		<LastGenOutput>Settings.Designer.cs</LastGenOutput>
	</None>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\TempVariablesModel\TempVariablesModel.csproj" />
    <ProjectReference Include="..\TempVariables\TempVariables.csproj" />
    <ProjectReference Include="..\TranslatableMenu\TranslatableMenu\TranslatableMenu.csproj" />
    <ProjectReference Include="..\LightSharedResources\LightSharedResources.csproj" />
    <ProjectReference Include="..\VFS\VFS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj" />
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj" />
    <ProjectReference Include="..\UFUATag\UFUAModel.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj" />
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Page Include="ClientEditorControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\AppNameSettingsEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Controls\NewAppNameEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="MenuControls\BarCommonItems.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\MenuControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\ToolbarControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
</Project>