//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverterManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitConverterManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Converter System.
        /// </summary>
        public static string AddNewConverterSystem {
            get {
                return ResourceManager.GetString("AddNewConverterSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to permanently removed {0} ?.
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid converter name. Name must start with a letter and only alphanumeric and underscore characters are supported.
        /// </summary>
        public static string ConverterNameInvalid {
            get {
                return ResourceManager.GetString("ConverterNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        public static string ConverterSystemNewName {
            get {
                return ResourceManager.GetString("ConverterSystemNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Name.
        /// </summary>
        public static string ConverterSystemOldName {
            get {
                return ResourceManager.GetString("ConverterSystemOldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CRDescription {
            get {
                return ResourceManager.GetString("CRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        public static string CREngineerUnit {
            get {
                return ResourceManager.GetString("CREngineerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture {0} already in list.
        /// </summary>
        public static string CultureAlreadyInList {
            get {
                return ResourceManager.GetString("CultureAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converters Editor.
        /// </summary>
        public static string DocumentEditorRibbonTitle {
            get {
                return ResourceManager.GetString("DocumentEditorRibbonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured opening the document &apos;{0}&apos;, exception &apos;{1}&apos;..
        /// </summary>
        public static string ErrorOpeningDocument {
            get {
                return ResourceManager.GetString("ErrorOpeningDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured reading the file &apos;{0}. The file may be corrupted.
        /// </summary>
        public static string ErrorReadingDocument {
            get {
                return ResourceManager.GetString("ErrorReadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the document ({0}) !.
        /// </summary>
        public static string ErrorSavingDocument {
            get {
                return ResourceManager.GetString("ErrorSavingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured saving {0}..
        /// </summary>
        public static string ErrorSavingDocWithoutClosure {
            get {
                return ResourceManager.GetString("ErrorSavingDocWithoutClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred validating the file &apos;{0}. The file may belong from another project.
        /// </summary>
        public static string ErrorValidatingDocument {
            get {
                return ResourceManager.GetString("ErrorValidatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed to {0}..
        /// </summary>
        public static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting converters to {0}. msg: {1}.
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists:  press Yes to overwrite, No to create new, Cancel to exit.
        /// </summary>
        public static string ExportFileWarning {
            get {
                return ResourceManager.GetString("ExportFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportConverters.
        /// </summary>
        public static string ExportStrings {
            get {
                return ResourceManager.GetString("ExportStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Editor.
        /// </summary>
        public static string ExpressionEditor {
            get {
                return ResourceManager.GetString("ExpressionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLog {
            get {
                return ResourceManager.GetString("GeneralLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        public static string HeaderID {
            get {
                return ResourceManager.GetString("HeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Expression.
        /// </summary>
        public static string HeaderInputExpression {
            get {
                return ResourceManager.GetString("HeaderInputExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Unit.
        /// </summary>
        public static string HeaderIUnit {
            get {
                return ResourceManager.GetString("HeaderIUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Unit.
        /// </summary>
        public static string HeaderOUnit {
            get {
                return ResourceManager.GetString("HeaderOUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Expression.
        /// </summary>
        public static string HeaderOutputExpression {
            get {
                return ResourceManager.GetString("HeaderOutputExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Already Exists !.
        /// </summary>
        public static string IDAlreadyExist {
            get {
                return ResourceManager.GetString("IDAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid ID.
        /// </summary>
        public static string IDCannotBeEmpty {
            get {
                return ResourceManager.GetString("IDCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Export Converters.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed from {0}..
        /// </summary>
        public static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing strings to {0}. msg: {1}.
        /// </summary>
        public static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard does not contains valid converters..
        /// </summary>
        public static string ImportErrorClipNoCols {
            get {
                return ResourceManager.GetString("ImportErrorClipNoCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file {0} miss some columns..
        /// </summary>
        public static string ImportErrorFileMissCols {
            get {
                return ResourceManager.GetString("ImportErrorFileMissCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file {0} format has no columns headers..
        /// </summary>
        public static string ImportErrorFileNoCols {
            get {
                return ResourceManager.GetString("ImportErrorFileNoCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not supported.
        /// </summary>
        public static string ImportFileFormatError {
            get {
                return ResourceManager.GetString("ImportFileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing converters....
        /// </summary>
        public static string ImportInProgress {
            get {
                return ResourceManager.GetString("ImportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converter named {0} already exists. Do you want to create a new one?.
        /// </summary>
        public static string ImportNameExist {
            get {
                return ResourceManager.GetString("ImportNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Converters.
        /// </summary>
        public static string ImportStrings {
            get {
                return ResourceManager.GetString("ImportStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [...Max Visible Items reached...] Double Click here to load all items.
        /// </summary>
        public static string MaxItemCountVisibleReached {
            get {
                return ResourceManager.GetString("MaxItemCountVisibleReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [...Max Visible Items reached...] Double Click here to load all items.
        /// </summary>
        public static string MaxItemCountVisibleReachedDoubleClick {
            get {
                return ResourceManager.GetString("MaxItemCountVisibleReachedDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No converter defined yet, do you want to upload a list of standard converters?.
        /// </summary>
        public static string NeedToLoadStandardConverters {
            get {
                return ResourceManager.GetString("NeedToLoadStandardConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewConverterID.
        /// </summary>
        public static string NewConverterID {
            get {
                return ResourceManager.GetString("NewConverterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NewConverterItemDescription {
            get {
                return ResourceManager.GetString("NewConverterItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Expression.
        /// </summary>
        public static string NewConverterItemIExpression {
            get {
                return ResourceManager.GetString("NewConverterItemIExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string NewConverterItemIUnit {
            get {
                return ResourceManager.GetString("NewConverterItemIUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewConverterItemName {
            get {
                return ResourceManager.GetString("NewConverterItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Expression.
        /// </summary>
        public static string NewConverterItemOExpression {
            get {
                return ResourceManager.GetString("NewConverterItemOExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewConverterName {
            get {
                return ResourceManager.GetString("NewConverterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the current list of converters there are one or more elements with the same name. Do you want to overwrite the existing converters or add new elements? Press Yes to overwrite, No to add new Converters..
        /// </summary>
        public static string OverrideConverter {
            get {
                return ResourceManager.GetString("OverrideConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Converter System.
        /// </summary>
        public static string RenameConverterSystem {
            get {
                return ResourceManager.GetString("RenameConverterSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converters.
        /// </summary>
        public static string RibbonHeader {
            get {
                return ResourceManager.GetString("RibbonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save {0} ?.
        /// </summary>
        public static string SaveDoc {
            get {
                return ResourceManager.GetString("SaveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Converter.
        /// </summary>
        public static string SelectConverterTitle {
            get {
                return ResourceManager.GetString("SelectConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converter Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate All.
        /// </summary>
        public static string TranslateColumns {
            get {
                return ResourceManager.GetString("TranslateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Converters.
        /// </summary>
        public static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
    }
}
