<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\Drivers</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
    <DocumentationFile>..\UFSolution\bin\Debug\Drivers\DriverSettingsInterfaces.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\Drivers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
    <DocumentationFile>..\UFSolution\bin\Release\Drivers\DriverSettingsInterfaces.XML</DocumentationFile>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <!-- make all references non-private, so they won't be copied to the output folder -->
  <Target Name="ClearReferenceCopyLocalPaths" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
    </ItemGroup>
  </Target>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ICrossReferenceAware.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="ICrossReferenceAware.cs" Condition=" '$(TargetFramework)' == 'net48' " />
    <None Include="..\DriverCodeBase\Properties\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </None>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="ICommunicationDriverWpfEditing.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="ICommunicationDriverWebEditing.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
    
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
      <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>