<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.69" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Libraries\Opc.Ua.Client\Opc.Ua.Client.csproj" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Libraries\Opc.Ua.Server\Opc.Ua.Server.csproj" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
  </ItemGroup>

</Project>
