<?xml version="1.0" encoding="utf-8"?>
<xs:schema 	id="WpfChart" 
			elementFormDefault="qualified" 
			targetNamespace="http://www.syncfusion.com/WpfChart.xsd" 
			xmlns="http://www.syncfusion.com/WpfChart.xsd" 
			xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
			xmlns:xw="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
			xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--Elements-->
  <xs:element name="sgChartArea" type="xs:anyType" abstract="true" />
  <xs:element name="sgChartLegend" type="xs:anyType" abstract="true" />
  <xs:element name="sgChartLegendItem" type="xs:anyType" abstract="true" />
  <xs:element name="sgChartSeries" type="xs:anyType" abstract="true" />
  <xs:element name="sgChartData" type="xs:anyType" abstract="true" />
  <xs:element name="sgChartDataPoint" type="xs:anyType" abstract="true" />

  <xs:element name="Chart" type="tChart" substitutionGroup="xw:sgControl">
  </xs:element>

  <xs:element name="ChartArea" type="tChartArea" substitutionGroup="sgChartArea">
  </xs:element>

  <xs:element name="ChartLegend" type="tChartLegend" substitutionGroup="sgChartLegend">
  </xs:element>

  <xs:element name="ChartSeries" type="tChartSeries" substitutionGroup="sgChartSeries">
  </xs:element>

  <xs:element name="ChartData" type="tChartData" substitutionGroup="sgChartData">
  </xs:element>

  <xs:element name="ChartDataPoint" type="tChartDataPoint" substitutionGroup="sgChartDataPoint">
  </xs:element>

  <!--Types-->
  <xs:complexType name="tChart" mixed="true">
    <xs:choice>
      <xs:element name="Chart.Areas" type="tChartAreasList" />
      <xs:element name="Chart.Legends" type="tChartLegendsList" />
    </xs:choice>
    <xs:attribute ref="x:Class" />
    <xs:attribute ref="x:Subclass" />
    <xs:attribute ref="x:Key" />
    <xs:attribute ref="x:Name" />
    <xs:attributeGroup ref="ChartAttributes" />
  </xs:complexType>

  <xs:complexType name="tChartArea" mixed="true">
    <xs:choice>
      <xs:element name="ChartArea.Series" type="tChartSeriesList" />
    </xs:choice>
    <xs:attributeGroup ref="ChartAreaAttributes" />
  </xs:complexType>

  <xs:complexType name="tChartLegend" mixed="true">
    <xs:attributeGroup ref="ChartLegendAttributes" />
  </xs:complexType>

  <xs:complexType name="tChartSeries" mixed="true">
    <xs:choice>
      <xs:element name="ChartSeries.Data" type="tChartDataContainer" />
    </xs:choice>
    <xs:attributeGroup ref="ChartSeriesAttributes"/>
  </xs:complexType>

  <xs:complexType name="tChartDataContainer" mixed="true">
    <xs:choice>
      <xs:group ref="gChartDatasList"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tChartData" mixed="true">
    <xs:choice>
      <xs:element name="ChartData.Points" type="tChartDataPointsList"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tChartDataPoint" mixed="true">
    <xs:attributeGroup ref="ChartDataPointAttributes"/>
  </xs:complexType>

  <xs:complexType name="tChartAreasList" mixed="true">
    <xs:choice>
      <xs:group ref="gChartAreasList" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tChartLegendsList" mixed="true">
    <xs:choice>
      <xs:group ref="gChartLegendsList" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tChartSeriesList">
    <xs:choice>
      <xs:group ref="gChartSeriesList" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tChartDataPointsList">
    <xs:choice>
      <xs:group ref="gChartDataPointsList" minOccurs="0" maxOccurs="unbounded"/>
    </xs:choice>
  </xs:complexType>

  <xs:simpleType name="tChartSeriesType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Line"/>
      <xs:enumeration value="Spline"/>
      <xs:enumeration value="RotatedSpline"/>
      <xs:enumeration value="Scatter"/>
      <xs:enumeration value="Column"/>
      <xs:enumeration value="Bar"/>
      <xs:enumeration value="Gantt"/>
      <xs:enumeration value="StackingBar"/>
      <xs:enumeration value="Area"/>
      <xs:enumeration value="SplineArea"/>
      <xs:enumeration value="StackingArea"/>
      <xs:enumeration value="StackingColumn"/>
      <xs:enumeration value="Pie"/>
      <xs:enumeration value="HiLo"/>
      <xs:enumeration value="HiLoOpenClose"/>
      <xs:enumeration value="Candle"/>
      <xs:enumeration value="Bubble"/>
      <xs:enumeration value="StepLine"/>
      <xs:enumeration value="StepArea"/>
      <xs:enumeration value="Radar"/>
      <xs:enumeration value="Kagi"/>
      <xs:enumeration value="Renko"/>
      <xs:enumeration value="Polar"/>
      <xs:enumeration value="ColumnRange"/>
      <xs:enumeration value="ThreeLineBreak"/>
      <xs:enumeration value="PointAndFigure"/>
      <xs:enumeration value="BoxAndWhisker"/>
      <xs:enumeration value="Histogram"/>
      <xs:enumeration value="Tornado"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Groups-->
  <xs:group name="gChartAreasList">
    <xs:choice>
      <xs:element ref="sgChartArea" minOccurs="0" />
      <xs:element ref="ChartArea" minOccurs="0" />
    </xs:choice>
  </xs:group>

  <xs:group name="gChartLegendsList">
    <xs:choice>
      <xs:element ref="sgChartLegend" minOccurs="0" />
      <xs:element ref="ChartLegend" minOccurs="0" />
    </xs:choice>
  </xs:group>

  <xs:group name="gChartSeriesList">
    <xs:choice>
      <xs:element ref="sgChartSeries" minOccurs="0" />
      <xs:element ref="ChartSeries" minOccurs="0" />
    </xs:choice>
  </xs:group>

  <xs:group name="gChartDatasList">
    <xs:choice>
      <xs:element ref="sgChartData"/>
      <xs:element ref="ChartData"/>
    </xs:choice>
  </xs:group>

  <xs:group name="gChartDataPointsList">
    <xs:choice>
      <xs:element ref="sgChartDataPoint"/>
      <xs:element ref="ChartDataPoint"/>
    </xs:choice>
  </xs:group>

  <!--Attributes-->
  <xs:attributeGroup name="ChartAttributes">
    <xs:attribute name="Chart.IsContainsDefaultLegend" type="xw:frlrfSystemBooleanClassTopic" />
    <xs:attributeGroup ref="xw:ControlAttributes"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ChartAreaAttributes">
    <xs:attributeGroup ref="xw:ControlAttributes"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ChartLegendAttributes">
    <xs:attributeGroup ref="xw:ControlAttributes"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ChartSeriesAttributes">
    <xs:attribute name="Name" type="xw:frlrfSystemStringClassTopic"/>
    <xs:attribute name="Type" type="tChartSeriesType"/>
    <xs:attribute name="Data" type="xw:frlrfSystemStringClassTopic"/>
  </xs:attributeGroup>

  <xs:attributeGroup name="ChartDataPointAttributes">
    <xs:attribute name="X" type="xw:frlrfSystemDoubleClassTopic"/>
    <xs:attribute name="Y" type="xw:frlrfSystemDoubleClassTopic"/>
  </xs:attributeGroup>

</xs:schema>