<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="DLSSchema" targetNamespace="Syncfusion.DLS" elementFormDefault="qualified"
  xmlns="Syncfusion.DLS" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DLS" type="Document" />
  <xs:complexType name="Document">
    <xs:sequence>
      <xs:element name="image" type="xs:string" />
      <xs:element name="styles">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="style" type="Style" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="liststyles">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="style" type="ListStyle" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="sections">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="section" type="Section" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Column">
    <xs:sequence />
    <xs:attribute name="Width" type="xs:float" />
    <xs:attribute name="Spacing" type="xs:float" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="HeadersFooters">
    <xs:sequence>
      <xs:element name="even-header" type="TextBody" />
      <xs:element name="odd-header" type="TextBody" />
      <xs:element name="even-footer" type="TextBody" />
      <xs:element name="odd-footer" type="TextBody" />
      <xs:element name="firts-page-header" type="TextBody" />
      <xs:element name="firts-page-footer" type="TextBody" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Hyperlink">
    <xs:sequence>
      <xs:element name="Bookmark" type="Ref" />
    </xs:sequence>
    <xs:attribute name="FilePath" type="xs:string" />
    <xs:attribute name="Uri" type="xs:string" />
    <xs:attribute name="BookmarkName" type="xs:string" />
    <xs:attribute name="HyperlinkType" type="HyperlinkType" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="PageSetup">
    <xs:sequence />
    <xs:attribute name="PageHeight" type="xs:float" />
    <xs:attribute name="PageWidth" type="xs:float" />
    <xs:attribute name="Alignment" type="PageAlignment" />
    <xs:attribute name="FooterDistance" type="xs:float" />
    <xs:attribute name="HeaderDistance" type="xs:float" />
    <xs:attribute name="Orientation" type="PageOrientation" />
    <xs:attribute name="BottomMargin" type="xs:float" />
    <xs:attribute name="TopMargin" type="xs:float" />
    <xs:attribute name="LeftMargin" type="xs:float" />
    <xs:attribute name="RightMargin" type="xs:float" />
    <xs:attribute name="DifferentFirstPage" type="xs:boolean" />
    <xs:attribute name="DifferentOddEvenPage" type="xs:boolean" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Paragraph">
    <xs:sequence>
      <xs:element name="style" type="Ref" />
      <xs:element name="character-format" type="CharacterFormat" />
      <xs:element name="paragraph-format" type="ParagraphFormat" />
      <xs:element name="list-format" type="ListFormat" />
      <xs:element name="items">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="item" type="ParagraphItem" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Section">
    <xs:sequence>
      <xs:element name="page-setup" type="PageSetup" />
      <xs:element name="headers-footers" type="HeadersFooters" />
      <xs:element name="columns">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="column" type="Column" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="paragraphs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="paragraph" type="Paragraph" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="BreakCode" type="SectionBreakCode" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="TableCell">
    <xs:sequence>
      <xs:element name="cell-format" type="CellFormat" />
      <xs:element name="paragraphs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="paragraph" type="Paragraph" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Width" type="xs:float" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="TableRow">
    <xs:sequence>
      <xs:element name="cells">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="cell" type="TableCell" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="RowHeight" type="xs:float" />
    <xs:attribute name="IsHeader" type="xs:boolean" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="TextBody">
    <xs:sequence>
      <xs:element name="paragraphs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="paragraph" type="Paragraph" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="ListStyle">
    <xs:sequence>
      <xs:element name="levels">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="level" type="ListLevel" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="ListLevel">
    <xs:sequence />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:group name="ParagraphStyleGroup">
    <xs:sequence>
      <xs:element name="character-format" type="CharacterFormat" />
      <xs:element name="paragraph-format" type="ParagraphFormat" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="ParagraphStyle">
    <xs:group ref="ParagraphStyleGroup" />
    <xs:attributeGroup ref="ParagraphStyleAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="ParagraphStyleAttrGroup">
    <xs:attribute name="BaseStyleName" type="xs:string" />
  </xs:attributeGroup>
  <xs:group name="ShapeStyleGroup">
    <xs:sequence>
      <xs:element name="shape-format" type="ShapeFormat" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="ShapeStyle">
    <xs:group ref="ShapeStyleGroup" />
    <xs:attributeGroup ref="ShapeStyleAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="ShapeStyleAttrGroup" />
  <xs:complexType name="Style">
    <xs:choice>
      <xs:group ref="ParagraphStyleGroup" />
      <xs:group ref="ShapeStyleGroup" />
    </xs:choice>
    <xs:attribute name="type" type="StyleType" />
    <xs:attributeGroup ref="ParagraphStyleAttrGroup" />
    <xs:attributeGroup ref="ShapeStyleAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="CharacterFormat">
    <xs:sequence />
    <xs:attribute name="TextColor" type="Color" />
    <xs:attribute name="FontName" type="xs:string" />
    <xs:attribute name="FontSize" type="xs:float" />
    <xs:attribute name="Bold" type="xs:boolean" />
    <xs:attribute name="Italic" type="xs:boolean" />
    <xs:attribute name="Strike" type="xs:boolean" />
    <xs:attribute name="DoubleStrike" type="xs:boolean" />
    <xs:attribute name="Underline" type="UnderlineStyle" />
    <xs:attribute name="SubSuperScript" type="xs:boolean" />
    <xs:attribute name="LineSpacing" type="xs:float" />
    <xs:attribute name="Position" type="xs:float" />
    <xs:attribute name="TextBackgroundColor" type="Color" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:group name="ParagraphFormatGroup">
    <xs:sequence>
      <xs:element name="borders" type="Borders" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="ParagraphFormat">
    <xs:group ref="ParagraphFormatGroup" />
    <xs:attributeGroup ref="ParagraphFormatAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="ParagraphFormatAttrGroup">
    <xs:attribute name="HrAlignment" type="HorizontalAlignment" />
    <xs:attribute name="VrAlignment" type="VerticalAlignment" />
    <xs:attribute name="LeftIndent" type="xs:float" />
    <xs:attribute name="RightIndent" type="xs:float" />
    <xs:attribute name="FirstLineIndent" type="xs:float" />
    <xs:attribute name="Keep" type="xs:float" />
    <xs:attribute name="BeforeSpacing" type="xs:float" />
    <xs:attribute name="AfterSpacing" type="xs:float" />
    <xs:attribute name="KeepFollow" type="xs:float" />
    <xs:attribute name="WidowControl" type="xs:boolean" />
    <xs:attribute name="PageBreakBefore" type="xs:boolean" />
    <xs:attribute name="PageBreakAfter" type="xs:boolean" />
    <xs:attribute name="ColumnBreakAfter" type="xs:boolean" />
    <xs:attribute name="BackColor" type="Color" />
  </xs:attributeGroup>
  <xs:complexType name="Borders">
    <xs:sequence>
      <xs:element name="Bottom" type="Border" />
      <xs:element name="Left" type="Border" />
      <xs:element name="Top" type="Border" />
      <xs:element name="Right" type="Border" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Border">
    <xs:sequence />
    <xs:attribute name="Color" type="Color" />
    <xs:attribute name="LineWidth" type="xs:float" />
    <xs:attribute name="BorderType" type="BorderType" />
    <xs:attribute name="Space" type="xs:float" />
    <xs:attribute name="Shadow" type="xs:boolean" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="Paddings">
    <xs:sequence>
      <xs:element name="Bottom" type="xs:float" />
      <xs:element name="Left" type="xs:float" />
      <xs:element name="Top" type="xs:float" />
      <xs:element name="Right" type="xs:float" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="TableFormat">
    <xs:sequence>
      <xs:group ref="CellFormatGroup" />
    </xs:sequence>
    <xs:attribute name="CellSpacing" type="xs:float" />
    <xs:attribute name="LeftOffset" type="xs:float" />
    <xs:attributeGroup ref="CellFormatAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:group name="CellFormatGroup">
    <xs:sequence>
      <xs:element name="borders" type="Borders" />
      <xs:element name="paddings" type="Paddings" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="CellFormat">
    <xs:group ref="CellFormatGroup" />
    <xs:attributeGroup ref="CellFormatAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="CellFormatAttrGroup">
    <xs:attribute name="VAlignment" type="VerticalAlignment" />
    <xs:attribute name="VMerge" type="CellMerge" />
    <xs:attribute name="HMerge" type="CellMerge" />
    <xs:attribute name="ShadingColor" type="Color" />
  </xs:attributeGroup>
  <xs:complexType name="ShapeFormat">
    <xs:sequence />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="ListFormat">
    <xs:sequence />
    <xs:attribute name="ListType" type="ListType" />
    <xs:attribute name="LevelNumber" type="xs:int" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="ParagraphItem">
    <xs:sequence>
      <xs:group ref="TextRangeGroup" />
      <xs:group ref="FieldGroup" />
      <xs:group ref="PictureGroup" />
      <xs:group ref="TableGroup" />
      <xs:group ref="CanvasGroup" />
      <xs:group ref="ShapeGroup" />
      <xs:group ref="BookmarkStartGroup" />
    </xs:sequence>
    <xs:attribute name="type" type="ParagraphItemType" />
    <xs:attributeGroup ref="TextRangeAttrGroup" />
    <xs:attributeGroup ref="FieldAttrGroup" />
    <xs:attributeGroup ref="PictureAttrGroup" />
    <xs:attributeGroup ref="TableAttrGroup" />
    <xs:attributeGroup ref="CanvasAttrGroup" />
    <xs:attributeGroup ref="ShapeAttrGroup" />
    <xs:attributeGroup ref="BookmarkStartAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:group name="TextRangeGroup">
    <xs:sequence>
      <xs:element name="character-format" type="CharacterFormat" />
      <xs:element name="hyperlink" type="Hyperlink" />
      <xs:element name="text" type="xs:string" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="TextRange">
    <xs:group ref="TextRangeGroup" />
    <xs:attributeGroup ref="TextRangeAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="TextRangeAttrGroup" />
  <xs:group name="FieldGroup">
    <xs:sequence />
  </xs:group>
  <xs:complexType name="Field">
    <xs:group ref="FieldGroup" />
    <xs:attributeGroup ref="FieldAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="FieldAttrGroup">
    <xs:attribute name="FieldType" type="FieldType" />
  </xs:attributeGroup>
  <xs:group name="PictureGroup">
    <xs:sequence>
      <xs:element name="image" type="xs:string" />
    </xs:sequence>
  </xs:group>
  <xs:complexType name="Picture">
    <xs:group ref="PictureGroup" />
    <xs:attributeGroup ref="PictureAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="PictureAttrGroup">
    <xs:attribute name="Width" type="xs:float" />
    <xs:attribute name="Height" type="xs:float" />
    <xs:attribute name="WidthScale" type="xs:float" />
    <xs:attribute name="HeightScale" type="xs:float" />
    <xs:attribute name="IsMetafile" type="xs:boolean" />
  </xs:attributeGroup>
  <xs:group name="TableGroup">
    <xs:sequence>
      <xs:element name="table-format" type="TableFormat" />
      <xs:element name="rows">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="row" type="TableRow" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:complexType name="Table">
    <xs:group ref="TableGroup" />
    <xs:attributeGroup ref="TableAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="TableAttrGroup" />
  <xs:group name="CanvasGroup">
    <xs:sequence>
      <xs:element name="shapes">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="shape" type="Shape" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:complexType name="Canvas">
    <xs:group ref="CanvasGroup" />
    <xs:attributeGroup ref="CanvasAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="CanvasAttrGroup">
    <xs:attribute name="BorderColor" type="Color" />
  </xs:attributeGroup>
  <xs:group name="ShapeGroup">
    <xs:sequence />
  </xs:group>
  <xs:complexType name="Shape">
    <xs:group ref="ShapeGroup" />
    <xs:attributeGroup ref="ShapeAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="ShapeAttrGroup" />
  <xs:group name="BookmarkStartGroup">
    <xs:sequence />
  </xs:group>
  <xs:complexType name="BookmarkStart">
    <xs:group ref="BookmarkStartGroup" />
    <xs:attributeGroup ref="BookmarkStartAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="BookmarkStartAttrGroup">
    <xs:attribute name="BookmarkName" type="xs:string" />
  </xs:attributeGroup>
  <xs:group name="BookmarkEndGroup">
    <xs:sequence />
  </xs:group>
  <xs:complexType name="BookmarkEnd">
    <xs:group ref="BookmarkEndGroup" />
    <xs:attributeGroup ref="BookmarkEndAttrGroup" />
    <xs:attribute name="id" type="xs:int" />
  </xs:complexType>
  <xs:attributeGroup name="BookmarkEndAttrGroup">
    <xs:attribute name="BookmarkName" type="xs:string" />
  </xs:attributeGroup>
  <xs:simpleType name="HyperlinkType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="FileLink" />
      <xs:enumeration value="UriLink" />
      <xs:enumeration value="Bookmark" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PageAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Top" />
      <xs:enumeration value="Middle" />
      <xs:enumeration value="Justified" />
      <xs:enumeration value="Bottom" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PageOrientation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Top" />
      <xs:enumeration value="Middle" />
      <xs:enumeration value="Justified" />
      <xs:enumeration value="Bottom" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SectionBreakCode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NoBreak" />
      <xs:enumeration value="NewColumn" />
      <xs:enumeration value="NewPage" />
      <xs:enumeration value="EvenPage" />
      <xs:enumeration value="Oddpage" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UnderlineStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Single" />
      <xs:enumeration value="Words" />
      <xs:enumeration value="Double" />
      <xs:enumeration value="Dotted" />
      <xs:enumeration value="Thick" />
      <xs:enumeration value="Dash" />
      <xs:enumeration value="DashLong" />
      <xs:enumeration value="DotDash" />
      <xs:enumeration value="DotDotDash" />
      <xs:enumeration value="Wavy" />
      <xs:enumeration value="DottedHeavy" />
      <xs:enumeration value="DashHeavy" />
      <xs:enumeration value="DashLongHeavy" />
      <xs:enumeration value="DotDashHeavy" />
      <xs:enumeration value="DotDotDashHeavy" />
      <xs:enumeration value="WavyHeavy" />
      <xs:enumeration value="WavyDouble" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HorizontalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Left" />
      <xs:enumeration value="Center" />
      <xs:enumeration value="Right" />
      <xs:enumeration value="Justify" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="VerticalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Top" />
      <xs:enumeration value="Middle" />
      <xs:enumeration value="Bottom" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BorderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Single" />
      <xs:enumeration value="Thick" />
      <xs:enumeration value="Double" />
      <xs:enumeration value="Hairline" />
      <xs:enumeration value="Wave" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FieldType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PageNumber" />
      <xs:enumeration value="NumPages" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Color">
    <xs:restriction base="xs:string">
      <xs:pattern value="^#[0-9a-fA-F]{8}$" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ParagraphItemType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TextRange" />
      <xs:enumeration value="Picture" />
      <xs:enumeration value="Canvas" />
      <xs:enumeration value="Table" />
      <xs:enumeration value="BookmarkStart" />
      <xs:enumeration value="BookmarkEnd" />
      <xs:enumeration value="Field" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StyleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ParagraphStyle" />
      <xs:enumeration value="ImageStyle" />
      <xs:enumeration value="ShapeStyle" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ListType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Numbered" />
      <xs:enumeration value="Bulleted" />
      <xs:enumeration value="NoList" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CellMerge">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Start" />
      <xs:enumeration value="Continue" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Ref">
    <xs:sequence />
    <xs:attribute name="ref" type="xs:int" />
  </xs:complexType>
</xs:schema>