<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>App.ico</ApplicationIcon>
  </PropertyGroup>

   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="OPCUAClient.Config.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs" Link="Properties\AssemblyVersionInfo.cs" />
    <Compile Include="..\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="OPCUAClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Mindscape.Raygun4Net.NetCore" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
    <ProjectReference Include="..\ConcurrentLog4Net\ConcurrentLog4Net.csproj" />
    <ProjectReference Include="..\Dynamics\MSZ.csproj" />
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj" />
    <ProjectReference Include="..\SolutionExplorer\UFProjectManager.csproj" />
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj" />
    <ProjectReference Include="..\UFRecipeEditor\UFRecipeEditor.csproj" />
    <ProjectReference Include="..\UFRecipeExecutionContext\UFRecipeExecutionContext.csproj" />
    <ProjectReference Include="..\UFUAEditor\UFUAEditor.csproj" />
    <ProjectReference Include="..\UriResolver\UriResolver.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
