<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>MSServer</RootNamespace>
    <AssemblyName>SchedulerServer.Core</AssemblyName>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <DefineConstants>NET_CORE;NET_STANDARD</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG;NET_CORE;NET_STANDARD</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>NET_CORE;NET_STANDARD</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="MSServer.MSUAServer.Config.xml" />
    <None Remove="OPCUAClient.Config.xml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="DevExpress.Data" Version="21.2.6" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.6" />
    <PackageReference Include="log4net" Version="2.0.14" />
    <PackageReference Include="Mindscape.Raygun4Net.NetCore" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Libraries\Opc.Ua.Configuration\Opc.Ua.Configuration.csproj" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Libraries\Opc.Ua.Client\Opc.Ua.Client.csproj" />
    <ProjectReference Include="..\DriverBaseClassLibrary\DriverBaseInterfaces.csproj" />
    <ProjectReference Include="..\ConcurrentLog4Net\ConcurrentLog4Net.csproj" />
    <ProjectReference Include="..\Dynamics\MSZ.csproj" />
    <ProjectReference Include="..\MSModel\MSModel.csproj" />
    <ProjectReference Include="..\MSSchedulerDocument\MSSchedulerSettings.csproj" />
    <ProjectReference Include="..\MSServerInfo\MSServerInfo.csproj" />
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj" />
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj" />
    <ProjectReference Include="..\UFUAServerBase\UFUAServerBase.csproj" />
    <ProjectReference Include="..\UFUATag\UFUAModel.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs" Link="Properties\AssemblyVersionInfo.cs" />
    <Compile Include="..\MSServer\MSServer.cs" Link="MSServer.cs" />
    <Compile Include="..\MSServer\MSUANodeManager.cs" Link="MSUANodeManager.cs" />
    <Compile Include="..\MSServer\MSUAServer.cs" Link="MSUAServer.cs" />
    <Compile Include="..\MSServer\Program.cs" Link="Program.cs" />
    <Compile Include="..\MSServer\ScheduledEvent.cs" Link="ScheduledEvent.cs" />
    <Compile Include="..\MSServer\SchedulerPersistence.cs" Link="SchedulerPersistence.cs" />
    <Compile Include="..\MSServer\SchedulingDate.cs" Link="SchedulingDate.cs" />
    <Compile Include="..\MSServer\SchedulingThread.cs" Link="SchedulingThread.cs" />
    <Compile Include="..\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
    <Content Include="App.ico" />
    <Content Include="OPCUAClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
      <Compile Include="..\MSServer\Properties\Settings.Designer.cs" Link="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>..\MSServer\Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DesignTime>True</DesignTime>
    </Compile>
    <None Include="..\MSServer\Properties\Settings.settings" Link="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
    </None>
    <Compile Include="..\MSServer\Properties\Resources.Designer.cs" Link="Properties\Resources.Designer.cs">
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\MSServer\Properties\Resources.resx" Link="Properties\Resources.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Include="MSServer.MSUAServer.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SchedulerServer.Core.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
