<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\DocumentManagers\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\DocumentManagers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup> 
	
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="MouseKeyHook" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="Accessibility" />
    <Reference Include="DevExpress.Xpf.Accordion.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Pdf.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Export, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Controls.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.DocumentViewer.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Extensions, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>false</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.CodeView.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Map.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Map.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.NavBar.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Ribbon.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <SpecificVersion>true</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Docking.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>false</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Layout.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>false</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.Expression.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35">
      <HintPath>C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Libraries\Microsoft.Expression.Drawing.dll</HintPath>
      <SpecificVersion>true</SpecificVersion>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Speech, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Program Files (x86)\Microsoft SDKs\Speech\v11.0\Assembly\Microsoft.Speech.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="ShaderEffects">
      <HintPath>..\..\..\Sources\References\ShaderEffects\ShaderEffects.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationUI, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" />
    <Reference Include="ReachFramework" />
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Printing" />
    <Reference Include="System.Runtime.Serialization">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Discovery" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Interactivity">
      <HintPath>C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.0\Libraries\System.Windows.Interactivity.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="UIAutomationProvider">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="UIAutomationTypes">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="WindowsBase">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="PresentationFramework">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Page Include="Adorners\SetZOrderControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Adorners\WarningAdornerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Adorners\GlassButton.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Adorners\ManipulationAdornerControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Adorners\DynamicControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Adorners\EditingAdornerControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Adorners\styles.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Controls\CulturesSelector.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="FolderBrowser.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="GadgetScreen.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="GeoViewer.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\BarCommonItems.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\BarCommonGeneralItems.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\MenuControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="MenuControls\ToolbarControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="NewScreenType.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="NewScreen.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="ObjectBrowseTreeItem.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\3DTransformSliders.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\AliasEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\CameraTransformsEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\DynamicPropertyInspector.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\DynamicPropertyInspectorPage.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\ItemControlSourceProperties.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\EffectSettings.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\RenameUserControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\SmartProperties.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\SpaceDistribution.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\TextProperties.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Popups\TypeDefinitionSummary.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\_3DInnerScreen.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\CultureFontListPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\CommandExplorerPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\GeoScadaExplorerPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>    
    <Page Include="PropertyDataTemplate\AnimationExplorerPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ListItemsSourcePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\BrushPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ListFontEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\SmartPropertiesEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="ScreenEditorView.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="ScreenTransitionViewer.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="ScreenViewer.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Resource Include="Resources\SearchPanelResources.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Generator>MSBuild:Compile</Generator>
    </Resource>
    <Compile Include="..\wpfutilities\cryptstring\CryptString.cs">
      <Link>CrypString\CryptString.cs</Link>
    </Compile>
    <Compile Include="Adorners\Converters\InverseZoomConverter.cs" />
    <Compile Include="Adorners\Converters\ColorConverter.cs" />
    <Compile Include="Adorners\PolyBezierAdorner.cs" />
    <Compile Include="Adorners\SetZOrderControl.xaml.cs">
      <DependentUpon>SetZOrderControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Adorners\WarningAdornerControl.xaml.cs">
      <DependentUpon>WarningAdornerControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Adorners\WarningAdorner.cs" />
    <Compile Include="Adorners\SetZOrderAdorner.cs" />
    <Compile Include="Adorners\PipelineAdorner.cs" />
    <Compile Include="Adorners\ManipulationAdorner.cs" />
    <Compile Include="Adorners\ManipulationAdornerControl.xaml.cs">
      <DependentUpon>ManipulationAdornerControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Adorners\DynamicAdorner.cs" />
    <Compile Include="Adorners\DynamicControl.xaml.cs">
      <DependentUpon>DynamicControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Behaviors\TranslateZoomRotateBehavior.cs" />
    <Compile Include="Controls\CulturesSelector.xaml.cs">
	    <DependentUpon>CulturesSelector.xaml</DependentUpon>
	</Compile>
    <Compile Include="Converters\AnimTypeToAnimationTypeConverter.cs" />
    <Compile Include="Converters\FontSettingsCountConverter.cs" />
    <Compile Include="Converters\OneChildEnabledConverter.cs" />
    <Compile Include="Converters\BoolToYesNoConverter.cs" />
    <Compile Include="CustomMapDataProvider.cs" />
    <Compile Include="Converters\BoolToVisibilityConverter.cs" />
    <Compile Include="Converters\DivideDoubleByParameterConverter.cs" />
	<Compile Include="Converters\UriToUriAbsoluteImageConverter.cs" />
    <Compile Include="Converters\ViewBoxHeightConverter.cs" />
    <Compile Include="Converters\UriToUriImageConverter.cs" />
    <Compile Include="Converters\FileNameToVisibilityConverter.cs" />
    <Compile Include="Converters\DoubleToIntConverter.cs" />
    <Compile Include="Converters\ToPercentConverter.cs" />
    <Compile Include="Converters\BarItemMinWidthConverter.cs" />
    <Compile Include="Converters\UriToTextConverter.cs" />
    <Compile Include="Converters\AliasValueToHumanReadableConverter.cs" />
    <Compile Include="FolderBrowser.xaml.cs">
      <DependentUpon>FolderBrowser.xaml</DependentUpon>
    </Compile>
    <Compile Include="GadgetScreen.xaml.cs">
      <DependentUpon>GadgetScreen.xaml</DependentUpon>
    </Compile>
    <Compile Include="GadgetSettings.cs" />
    <Compile Include="GeoViewer.xaml.cs">
      <DependentUpon>GeoViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="GeoViewerItemModel.cs" />
    <Compile Include="MenuControls\BarCommonItems.xaml.cs">
      <DependentUpon>BarCommonItems.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\BarCommonGeneralItems.xaml.cs">
      <DependentUpon>BarCommonGeneralItems.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\MenuControl.xaml.cs">
      <DependentUpon>MenuControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\ToolbarControl.xaml.cs">
      <DependentUpon>ToolbarControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="NewScreenType.xaml.cs">
      <DependentUpon>NewScreenType.xaml</DependentUpon>
    </Compile>
    <Compile Include="NewScreen.xaml.cs">
      <DependentUpon>NewScreen.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\AliasEditor.xaml.cs">
      <DependentUpon>AliasEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\CameraTransformsEditor.xaml.cs">
      <DependentUpon>CameraTransformsEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\DynamicPropertyInspector.xaml.cs">
      <DependentUpon>DynamicPropertyInspector.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\DynamicPropertyInspectorPage.xaml.cs">
      <DependentUpon>DynamicPropertyInspectorPage.xaml</DependentUpon>
    </Compile>
	<Compile Include="Popups\DynamicStringInspector.xaml.cs">
      <DependentUpon>DynamicStringInspector.xaml</DependentUpon>
	</Compile>
	<Compile Include="Popups\DynamicStringInspectorPage.xaml.cs">
	  <DependentUpon>DynamicStringInspectorPage.xaml</DependentUpon>
	</Compile>
    <Compile Include="Popups\ItemControlSourceProperties.xaml.cs">
      <DependentUpon>ItemControlSourceProperties.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\RenameUserControl.xaml.cs">
      <DependentUpon>RenameUserControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\SilverlightishPopup.cs" />
    <Compile Include="Popups\SpaceDistribution.xaml.cs">
      <DependentUpon>SpaceDistribution.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\TypeDefinitionSummary.xaml.cs">
      <DependentUpon>TypeDefinitionSummary.xaml</DependentUpon>
    </Compile>
    <Compile Include="OpenUriEventArgs.cs" />
    <Compile Include="Popups\_3DInnerScreen.xaml.cs">
      <DependentUpon>_3DInnerScreen.xaml</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.cs" />
    <Compile Include="PropertyDataTemplate\CultureFontListPropertyEditor.xaml.cs">
      <DependentUpon>CultureFontListPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\BrushEditorOptions.cs" />
    <Compile Include="PropertyDataTemplate\CommandExplorerPropertyEditor.xaml.cs">
      <DependentUpon>CommandExplorerPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\GeoScadaExplorerPropertyEditor.xaml.cs">
      <DependentUpon>GeoScadaExplorerPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ListItemsSourcePropertyEditor.xaml.cs">
      <DependentUpon>ListItemsSourcePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\AnimationExplorerPropertyEditor.xaml.cs">
      <DependentUpon>AnimationExplorerPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\BrushPropertyEditor.xaml.cs">
      <DependentUpon>BrushPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ListFontEditor.xaml.cs">
      <DependentUpon>ListFontEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\SmartPropertiesEditor.xaml.cs">
      <DependentUpon>SmartPropertiesEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="ScreenEditorView.xaml.cs">
      <DependentUpon>ScreenEditorView.xaml</DependentUpon>
    </Compile>
    <Page Include="SpecialObjects\AnimatedProgressBar.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="SpecialObjects\Controls\EmbeddedTabScreenSmartControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="SpecialObjects\EmbeddedTabScreen.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="SpeechWindow.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Storyboards.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="StyleEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="TileViewer.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\DynamicStringInspectorPage.xaml">
	  <SubType>Designer</SubType>
	  <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Popups\DynamicStringInspector.xaml">
	  <SubType>Designer</SubType>
	  <Generator>MSBuild:Compile</Generator>
    </Page>
    <Resource Include="Adorners\Rotate.cur">
    </Resource>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="Adorners\BasicAdorner.cs" />
    <Compile Include="Adorners\BasicPointAdorner.cs" />
    <Compile Include="Adorners\EditingAdornerControl.xaml.cs">
      <DependentUpon>EditingAdornerControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Adorners\GridAdorner.cs" />
    <Compile Include="Adorners\IGridViewInfoService.cs" />
    <Compile Include="Adorners\LineAdorner.cs" />
    <Compile Include="Adorners\PolygonAdorner.cs" />
    <Compile Include="Adorners\DragThumb.cs" />
    <Compile Include="Adorners\MessageAdorner.cs" />
    <Compile Include="Adorners\PointDragThumb.cs" />
    <Compile Include="Adorners\PolylineAdorner.cs" />
    <Compile Include="Adorners\ResizeThumb.cs" />
    <Compile Include="Adorners\RotateThumb.cs" />
    <Compile Include="Adorners\SelectionAdorner.cs" />
    <Compile Include="Adorners\TransformOriginThumb.cs" />
    <Compile Include="Converters\DivideDoubleByTwoConverter.cs" />
    <Compile Include="ObjectBrowseTreeItem.xaml.cs">
      <DependentUpon>ObjectBrowseTreeItem.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\3DTransformSliders.xaml.cs">
      <DependentUpon>3DTransformSliders.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\EffectSettings.xaml.cs">
      <DependentUpon>EffectSettings.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\SmartProperties.xaml.cs">
      <DependentUpon>SmartProperties.xaml</DependentUpon>
    </Compile>
    <Compile Include="Popups\TextProperties.xaml.cs">
      <DependentUpon>TextProperties.xaml</DependentUpon>
    </Compile>
    <Compile Include="Adorners\GenericElementAdorner.cs" />
    <Compile Include="Properties\UICommandResource.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>UICommandResource.resx</DependentUpon>
    </Compile>
    <Compile Include="ScreenLayoutData.cs" />
    <Compile Include="ScreenTransitionViewer.xaml.cs">
      <DependentUpon>ScreenTransitionViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="ScreenViewer.xaml.cs">
      <DependentUpon>ScreenViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="SpecialObjects\AnimatedProgressBar.xaml.cs">
      <DependentUpon>AnimatedProgressBar.xaml</DependentUpon>
    </Compile>
    <Compile Include="SpecialObjects\Controls\EmbeddedTabScreenSmartControl.xaml.cs">
      <DependentUpon>EmbeddedTabScreenSmartControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="SpecialObjects\EmbeddedTabScreen.xaml.cs">
      <DependentUpon>EmbeddedTabScreen.xaml</DependentUpon>
    </Compile>
    <Compile Include="SpecialObjects\Enums\AnimType.cs" />
    <Compile Include="SpecialObjects\ScreenList.cs" />
    <Compile Include="SpeechWindow.xaml.cs">
      <DependentUpon>SpeechWindow.xaml</DependentUpon>
    </Compile>
    <Compile Include="StyleEditor.xaml.cs">
      <DependentUpon>StyleEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="TileViewer.xaml.cs">
      <DependentUpon>TileViewer.xaml</DependentUpon>
    </Compile>
    <Compile Include="TagListSearchOperators.cs" />
    <Compile Include="DockLayoutControlEx.cs" />
    <Compile Include="TouchHelper.cs" />
    <Compile Include="TreeDocumentManagers\TreeEntityReferenceDocManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeElementDocManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeEntityDocManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeElementsDocManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeEntitiesDocManager.cs" />
    <Compile Include="UIGeneralCommands.cs" />
    <Compile Include="UndoRedoManager.cs" />
    <EmbeddedResource Include="Properties\UICommandResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UICommandResource.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="ComponentService\ScreenManagerComponent.cs" />    
    <Compile Include="LocalEnumConverter.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <None Include="app.config" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="PropertyDataTemplate\SmartPropertiesEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\SVGHelper\SVGHelper.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\GadgetLibrary\GadgetLibrary.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\helixtoolkit\Source\HelixToolkit.Wpf\HelixToolkit.Wpf.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\SmartThreadPool\SmartThreadPool.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\3DTools-1.01-src\3DTools\3DTools.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommonControls\CommonControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\LightSharedResources\LightSharedResources.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\RuntimeLightSharedResources\RuntimeLightSharedResources.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\RuntimeDarkSharedResources\RuntimeDarkSharedResources.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Converters\Converters.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CrossReferenceHelper\CrossReferenceHelper.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataReaderEditor\DataReaderEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Log4NetViewer\Log4NetViewer.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MSZui\MSZui.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Pipeline\Pipeline.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\PolyBezier\PolyBezier.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\SysVariables\SysVariables.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslationHelpers\TranslationHelpers.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\VFS\VFS.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WatchControl\WatchControl.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WebHMIDesignHelper\WebHMIDesignHelper.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslatableMenu\TranslatableMenu\TranslatableMenu.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimationManager\AnimationManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommandManager\CommandManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataReader\DataReader.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Dynamics\MSZ.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScreenSettings\ScreenSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MenuControls\Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IdentityModel" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;&#xD;&#xA;XCOPY /Y &quot;$(TargetDir)GadgetLibrary.*&quot; &quot;$(OutDir)..\&quot;&#xD;&#xA;XCOPY /Y &quot;$(TargetDir)Gma.System.MouseKeyHook.*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>