//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverSerialExample.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriverSerialExample.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits.
        /// </summary>
        public static string DataBits {
            get {
                return ResourceManager.GetString("DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Number.
        /// </summary>
        public static string FileNumber {
            get {
                return ResourceManager.GetString("FileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Type.
        /// </summary>
        public static string FrameType {
            get {
                return ResourceManager.GetString("FrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Area.
        /// </summary>
        public static string FunctionCode {
            get {
                return ResourceManager.GetString("FunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading file {0}: {1}.
        /// </summary>
        public static string ImportExceptionFileLoading {
            get {
                return ResourceManager.GetString("ImportExceptionFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverSerialExample driver - Import Editor.
        /// </summary>
        public static string ImportMsgBoxTitle {
            get {
                return ResourceManager.GetString("ImportMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Address.
        /// </summary>
        public static string StartAddress {
            get {
                return ResourceManager.GetString("StartAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station ID.
        /// </summary>
        public static string StationID {
            get {
                return ResourceManager.GetString("StationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnaround Delay.
        /// </summary>
        public static string TurnaroundDelay {
            get {
                return ResourceManager.GetString("TurnaroundDelay", resourceCulture);
            }
        }
    }
}
