using System.Text.Json;

namespace ServerEditorWeb.Services;

/// <summary>
/// Provides editor UI localization. Persists the selected locale to disk.
/// All translations are embedded — no resource files needed.
/// </summary>
public class EditorLocalizationService
{
    private static readonly string SettingsPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "SimpleOpcFileServer", "editor_locale.json");

    public string Locale { get; private set; } = "en";

    public event Action? LocaleChanged;

    /// <summary>Supported locales: code → (display name, flag).</summary>
    public static readonly (string Code, string Name, string Flag)[] SupportedLocales =
    [
        ("en", "English", "🇬🇧"),
        ("de", "Deutsch", "🇩🇪"),
        ("it", "Italiano", "🇮🇹"),
        ("fr", "Français", "🇫🇷"),
        ("ja", "日本語", "🇯🇵"),
        ("zh", "中文", "🇨🇳"),
    ];

    public EditorLocalizationService()
    {
        Load();
    }

    public void SetLocale(string locale)
    {
        if (Locale == locale) return;
        Locale = locale;
        Save();
        LocaleChanged?.Invoke();
    }

    /// <summary>
    /// Resolve a localization key. Returns the translated string for the current locale,
    /// falling back to English if the key is missing.
    /// </summary>
    public string this[string key]
    {
        get
        {
            if (_translations.TryGetValue(Locale, out var dict) && dict.TryGetValue(key, out var val))
                return val;
            if (_translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enVal))
                return enVal;
            return key; // fallback: return the key itself
        }
    }

    private void Load()
    {
        try
        {
            if (File.Exists(SettingsPath))
            {
                var json = File.ReadAllText(SettingsPath);
                var obj = JsonSerializer.Deserialize<LocaleSettings>(json);
                if (obj != null && SupportedLocales.Any(l => l.Code == obj.Locale))
                    Locale = obj.Locale;
            }
        }
        catch { /* use default */ }
    }

    private void Save()
    {
        try
        {
            var dir = Path.GetDirectoryName(SettingsPath)!;
            Directory.CreateDirectory(dir);
            var json = JsonSerializer.Serialize(new LocaleSettings { Locale = Locale });
            File.WriteAllText(SettingsPath, json);
        }
        catch { /* ignore */ }
    }

    private record LocaleSettings
    {
        public string Locale { get; init; } = "en";
    }

    // ═══════════════════════════════════════════════════════════
    //  Translation dictionaries
    // ═══════════════════════════════════════════════════════════

    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["en"] = new()
        {
            // ── Menus ──
            ["menu.file"] = "File",
            ["menu.edit"] = "Edit",
            ["menu.view"] = "View",
            ["menu.settings"] = "Settings",
            ["menu.help"] = "Help",

            // File menu
            ["menu.file.new"] = "New",
            ["menu.file.open"] = "Open",
            ["menu.file.browseServer"] = "Browse Server…",
            ["menu.file.recent"] = "Recent",
            ["menu.file.save"] = "Save",
            ["menu.file.saveAs"] = "Save As…",

            // Edit menu
            ["menu.edit.addFolder"] = "Add Folder",
            ["menu.edit.addVariable"] = "Add Variable",
            ["menu.edit.addScript"] = "Add Script",
            ["menu.edit.addScreen"] = "Add Screen",
            ["menu.edit.copy"] = "Copy",
            ["menu.edit.paste"] = "Paste",
            ["menu.edit.delete"] = "Delete",

            // View menu
            ["menu.view.panels"] = "Panels",
            ["menu.view.maximize"] = "Maximize Active Panel",

            // Settings menu
            ["menu.settings.theme"] = "Theme",
            ["menu.settings.light"] = "Light",
            ["menu.settings.dark"] = "Dark",
            ["menu.settings.language"] = "Language",
            ["menu.settings.protection"] = "Project Protection",
            ["menu.settings.unlock"] = "Unlock Project…",
            ["menu.settings.lock"] = "Lock Project",
            ["menu.settings.changePw"] = "Change Password…",
            ["menu.settings.removePw"] = "Remove Password…",
            ["menu.settings.setPw"] = "Set Password…",

            // Help menu
            ["menu.help.help"] = "Help",
            ["menu.help.validate"] = "Validate Project",
            ["menu.help.about"] = "About",

            // Toolbar tooltips
            ["toolbar.new"] = "New",
            ["toolbar.save"] = "Save",
            ["toolbar.saveAs"] = "Save As…",
            ["toolbar.undo"] = "Undo",
            ["toolbar.redo"] = "Redo",
            ["toolbar.copy"] = "Copy",
            ["toolbar.paste"] = "Paste",
            ["toolbar.delete"] = "Delete",
            ["toolbar.addFolder"] = "Add Folder",
            ["toolbar.addVariable"] = "Add Variable",
            ["toolbar.addScript"] = "Add Script",
            ["toolbar.addPlc"] = "Add PLC Program",
            ["toolbar.addRecipe"] = "Add Recipe",
            ["toolbar.addScheduler"] = "Add Scheduler",
            ["toolbar.addReport"] = "Add Report",
            ["toolbar.addScreen"] = "Add Screen",
            ["toolbar.restore"] = "Restore layout",
            ["toolbar.maximize"] = "Maximize active panel",
            ["toolbar.toggleTheme"] = "Toggle theme",
            ["toolbar.logout"] = "Logout",

            // Status bar
            ["status.unsaved"] = "Unsaved",
            ["status.locked"] = "Locked",
            ["status.unlocked"] = "Unlocked",

            // Dialogs
            ["dialog.saveAs.title"] = "Save As",
            ["dialog.saveAs.filePath"] = "File path:",
            ["dialog.saveAs.current"] = "Current:",
            ["dialog.saveAs.cancel"] = "Cancel",
            ["dialog.saveAs.save"] = "Save",

            ["dialog.unsaved.title"] = "Unsaved Changes",
            ["dialog.unsaved.message"] = "The project {0} has unsaved changes. Do you want to save before closing?",
            ["dialog.unsaved.cancel"] = "Cancel",
            ["dialog.unsaved.discard"] = "Discard",
            ["dialog.unsaved.save"] = "Save",

            ["dialog.open.title"] = "Open Project File",
            ["dialog.open.empty"] = "Select a drive or enter a path",
            ["dialog.open.emptyFolder"] = "Empty folder or access denied",
            ["dialog.open.cancel"] = "Cancel",
            ["dialog.open.open"] = "Open",

            ["dialog.unlock.title"] = "Unlock Project",
            ["dialog.unlock.message"] = "This project is password-protected. Enter the password to unlock it for editing.",
            ["dialog.unlock.password"] = "Password",
            ["dialog.unlock.cancel"] = "Cancel",
            ["dialog.unlock.unlock"] = "Unlock",

            ["dialog.setPw.title.change"] = "Change Project Password",
            ["dialog.setPw.title.set"] = "Set Project Password",
            ["dialog.setPw.msgChange"] = "Change or remove the project protection password.",
            ["dialog.setPw.msgSet"] = "Set a password to protect this project. When locked, the project cannot be edited without the correct password.",
            ["dialog.setPw.currentPw"] = "Current Password",
            ["dialog.setPw.newPw"] = "New Password",
            ["dialog.setPw.confirmPw"] = "Confirm Password",
            ["dialog.setPw.cancel"] = "Cancel",
            ["dialog.setPw.change"] = "Change Password",
            ["dialog.setPw.set"] = "Set Password",

            ["dialog.changePw.title"] = "Change Password",
            ["dialog.changePw.message"] = "You must change your password before continuing.",
            ["dialog.changePw.currentPw"] = "Current Password",
            ["dialog.changePw.newPw"] = "New Password",
            ["dialog.changePw.confirmPw"] = "Confirm New Password",
            ["dialog.changePw.submit"] = "Change Password",

            // General
            ["general.serverEditor"] = "Server Editor",
            ["general.projectLocked"] = "Project is locked. Unlock it first to make changes.",
            ["general.projectUnlocked"] = "Project unlocked.",
            ["general.projectLocked2"] = "Project locked.",
            ["prop.name"] = "Name",
            ["prop.type"] = "Type",
            ["prop.access"] = "Access",
            ["prop.initialValue"] = "Initial Value",
            ["prop.initialValueHint"] = "Value applied on server start (e.g. 0, true, Hello)",
            ["prop.initialValueDesc"] = "Parsed according to the variable Type. Leave empty for default.",
            ["prop.retentive"] = "Retentive",
            ["prop.retentiveHint"] = "When enabled, the variable value is saved to disk and restored on server restart.",
            ["prop.enableStats"] = "Enable Statistics",
            ["prop.enableStatsHint"] = "Publishes Min, Max, Average, and Count as OPC sub-variables. A Reset command is also created.",
            ["prop.driverJson"] = "Driver Settings (JSON)",
            ["prop.children"] = "Children",
            ["prop.folders"] = "Folders",
            ["prop.variables"] = "Variables",
            ["prop.interval"] = "Interval (ms)",
            ["prop.language"] = "Language",
            ["prop.enabled"] = "Enabled",
            ["prop.cycleTime"] = "Cycle Time (ms)",
            ["prop.dbPath"] = "Database Path",
            ["prop.slotGranularity"] = "Slot Granularity (minutes)",
            ["prop.holidayLocale"] = "Holiday Locale",
            ["prop.holidayLocaleHint"] = "Select a locale to load built-in public holidays.",
            ["prop.title"] = "Title",
            ["prop.description"] = "Description",
            ["prop.format"] = "Format",
            ["prop.pageSize"] = "Page Size",
            ["prop.orientation"] = "Orientation",
            ["prop.deliveryMethod"] = "Delivery Method",
            ["prop.outputDir"] = "Output Directory",
            ["prop.fileNamePattern"] = "File Name Pattern",
            ["prop.recipients"] = "Recipients (comma-separated)",
            ["prop.emailSubject"] = "Email Subject",
            ["prop.smtpServer"] = "SMTP Server",
            ["prop.smtpPort"] = "SMTP Port",
            ["prop.smtpUser"] = "SMTP Username",
            ["prop.smtpPass"] = "SMTP Password",
            ["prop.smtpSsl"] = "Use SSL/TLS",
            ["prop.fromAddress"] = "From Address",
            ["prop.width"] = "Width",
            ["prop.height"] = "Height",
            ["prop.background"] = "Background",
            ["prop.backgroundImage"] = "Background Image",
            ["prop.showInNav"] = "Show In Navigation",
            ["prop.showInNavHint"] = "When enabled, this screen appears in the runtime navigation bar/menu.",
            ["prop.symbols"] = "Symbols",
            ["prop.screenEditorHint"] = "Use the Screen Editor panel to design the SVG layout and bind OPC variables.",
            ["prop.endpointUrl"] = "Endpoint URL",
            ["prop.startupScreen"] = "Startup Screen",
            ["prop.navStyle"] = "Navigation Style",
            ["prop.navStyleHint"] = "Controls how screens are navigated in the RuntimeViewer.",
            ["prop.navTabs"] = "Tabs (top)",
            ["prop.navSidebar"] = "Sidebar (left)",
            ["prop.navHamburger"] = "Hamburger Menu",
            ["prop.navBottom"] = "Bottom Tab Bar",
            ["prop.showNavBar"] = "Show Navigation Bar (Kiosk)",
            ["prop.showNavBarHint"] = "In kiosk mode the navigation bar is hidden by default. Enable this to keep it visible.",
            ["prop.enableAnon"] = "Enable Anonymous Access",
            ["prop.requireEditorLogin"] = "Require Editor Login",
            ["prop.requireRuntimeLogin"] = "Require Runtime Login",
            ["prop.requireStrongPw"] = "Require Strong Passwords",
            ["prop.diagPort"] = "Diagnostics Port",
            ["prop.diagPortHint"] = "HTTP port for the diagnostics API. Set to 0 to disable.",
            ["prop.accessLevel"] = "Access Level (OPC Variables)",
            ["prop.canAccessEditor"] = "Can access project editor",
            ["prop.username"] = "Username",
            ["prop.group"] = "Group",
            ["prop.password"] = "Password",
            ["prop.pwEncrypted"] = "Encrypted",
            ["prop.pwResetHint"] = "Use the Users panel to reset.",
            ["prop.pwNotSet"] = "No password set. Use the Users panel to set one.",
            ["prop.none"] = "(none)",
            ["section.folder"] = "Folder Properties",
            ["section.variable"] = "Variable Properties",
            ["section.script"] = "Script Properties",
            ["section.plc"] = "PLC Program Properties",
            ["section.recipe"] = "Recipe Properties",
            ["section.scheduler"] = "Scheduler Properties",
            ["section.report"] = "Report Properties",
            ["section.screen"] = "Screen Properties",
            ["section.serverSettings"] = "Server Settings",
            ["section.screenGroup"] = "Screen Group",
            ["section.screenGroupHint"] = "Select a screen to edit, or add a new one.",
            ["section.userGroupList"] = "Users &amp; Groups",
            ["section.userGroupListHint"] = "Right-click to add a user group, then add users to groups.",
            ["section.userGroupListHint2"] = "Use the Users panel for full management including passwords and access levels.",
            ["section.userGroup"] = "User Group Properties",
            ["section.user"] = "User Properties",
            ["section.users"] = "Users",
            ["general.selectItem"] = "Select an item to view its properties.",
            ["prop.allowRuntimeEdit"] = "Allow Runtime Edit",
            ["prop.allowRuntimeEditHint"] = "When enabled, runtime users can modify the schedule from the Weekly Planner widget.",
            ["help.toc"] = "Table of Contents",
            ["help.home"] = "Home",
        },

        ["de"] = new()
        {
            ["menu.file"] = "Datei",
            ["menu.edit"] = "Bearbeiten",
            ["menu.view"] = "Ansicht",
            ["menu.settings"] = "Einstellungen",
            ["menu.help"] = "Hilfe",

            ["menu.file.new"] = "Neu",
            ["menu.file.open"] = "Öffnen",
            ["menu.file.browseServer"] = "Server durchsuchen…",
            ["menu.file.recent"] = "Zuletzt verwendet",
            ["menu.file.save"] = "Speichern",
            ["menu.file.saveAs"] = "Speichern unter…",

            ["menu.edit.addFolder"] = "Ordner hinzufügen",
            ["menu.edit.addVariable"] = "Variable hinzufügen",
            ["menu.edit.addScript"] = "Skript hinzufügen",
            ["menu.edit.addScreen"] = "Bildschirm hinzufügen",
            ["menu.edit.copy"] = "Kopieren",
            ["menu.edit.paste"] = "Einfügen",
            ["menu.edit.delete"] = "Löschen",

            ["menu.view.panels"] = "Bereiche",
            ["menu.view.maximize"] = "Aktiven Bereich maximieren",

            ["menu.settings.theme"] = "Design",
            ["menu.settings.light"] = "Hell",
            ["menu.settings.dark"] = "Dunkel",
            ["menu.settings.language"] = "Sprache",
            ["menu.settings.protection"] = "Projektschutz",
            ["menu.settings.unlock"] = "Projekt entsperren…",
            ["menu.settings.lock"] = "Projekt sperren",
            ["menu.settings.changePw"] = "Passwort ändern…",
            ["menu.settings.removePw"] = "Passwort entfernen…",
            ["menu.settings.setPw"] = "Passwort festlegen…",

            ["menu.help.help"] = "Hilfe",
            ["menu.help.validate"] = "Projekt validieren",
            ["menu.help.about"] = "Über",

            ["toolbar.new"] = "Neu",
            ["toolbar.save"] = "Speichern",
            ["toolbar.saveAs"] = "Speichern unter…",
            ["toolbar.undo"] = "Rückgängig",
            ["toolbar.redo"] = "Wiederholen",
            ["toolbar.copy"] = "Kopieren",
            ["toolbar.paste"] = "Einfügen",
            ["toolbar.delete"] = "Löschen",
            ["toolbar.addFolder"] = "Ordner hinzufügen",
            ["toolbar.addVariable"] = "Variable hinzufügen",
            ["toolbar.addScript"] = "Skript hinzufügen",
            ["toolbar.addPlc"] = "SPS-Programm hinzufügen",
            ["toolbar.addRecipe"] = "Rezept hinzufügen",
            ["toolbar.addScheduler"] = "Zeitplan hinzufügen",
            ["toolbar.addReport"] = "Bericht hinzufügen",
            ["toolbar.addScreen"] = "Bildschirm hinzufügen",
            ["toolbar.restore"] = "Layout wiederherstellen",
            ["toolbar.maximize"] = "Aktiven Bereich maximieren",
            ["toolbar.toggleTheme"] = "Design wechseln",
            ["toolbar.logout"] = "Abmelden",

            ["status.unsaved"] = "Nicht gespeichert",
            ["status.locked"] = "Gesperrt",
            ["status.unlocked"] = "Entsperrt",

            ["dialog.saveAs.title"] = "Speichern unter",
            ["dialog.saveAs.filePath"] = "Dateipfad:",
            ["dialog.saveAs.current"] = "Aktuell:",
            ["dialog.saveAs.cancel"] = "Abbrechen",
            ["dialog.saveAs.save"] = "Speichern",

            ["dialog.unsaved.title"] = "Nicht gespeicherte Änderungen",
            ["dialog.unsaved.message"] = "Das Projekt {0} hat nicht gespeicherte Änderungen. Möchten Sie vor dem Schließen speichern?",
            ["dialog.unsaved.cancel"] = "Abbrechen",
            ["dialog.unsaved.discard"] = "Verwerfen",
            ["dialog.unsaved.save"] = "Speichern",

            ["dialog.open.title"] = "Projektdatei öffnen",
            ["dialog.open.empty"] = "Wählen Sie ein Laufwerk oder geben Sie einen Pfad ein",
            ["dialog.open.emptyFolder"] = "Leerer Ordner oder Zugriff verweigert",
            ["dialog.open.cancel"] = "Abbrechen",
            ["dialog.open.open"] = "Öffnen",

            ["dialog.unlock.title"] = "Projekt entsperren",
            ["dialog.unlock.message"] = "Dieses Projekt ist passwortgeschützt. Geben Sie das Passwort ein, um es zu bearbeiten.",
            ["dialog.unlock.password"] = "Passwort",
            ["dialog.unlock.cancel"] = "Abbrechen",
            ["dialog.unlock.unlock"] = "Entsperren",

            ["dialog.setPw.title.change"] = "Projektpasswort ändern",
            ["dialog.setPw.title.set"] = "Projektpasswort festlegen",
            ["dialog.setPw.msgChange"] = "Projektschutzpasswort ändern oder entfernen.",
            ["dialog.setPw.msgSet"] = "Legen Sie ein Passwort fest, um dieses Projekt zu schützen.",
            ["dialog.setPw.currentPw"] = "Aktuelles Passwort",
            ["dialog.setPw.newPw"] = "Neues Passwort",
            ["dialog.setPw.confirmPw"] = "Passwort bestätigen",
            ["dialog.setPw.cancel"] = "Abbrechen",
            ["dialog.setPw.change"] = "Passwort ändern",
            ["dialog.setPw.set"] = "Passwort festlegen",

            ["dialog.changePw.title"] = "Passwort ändern",
            ["dialog.changePw.message"] = "Sie müssen Ihr Passwort ändern, bevor Sie fortfahren können.",
            ["dialog.changePw.currentPw"] = "Aktuelles Passwort",
            ["dialog.changePw.newPw"] = "Neues Passwort",
            ["dialog.changePw.confirmPw"] = "Neues Passwort bestätigen",
            ["dialog.changePw.submit"] = "Passwort ändern",

            ["general.serverEditor"] = "Server-Editor",
            ["general.projectLocked"] = "Projekt ist gesperrt. Entsperren Sie es zuerst.",
            ["general.projectUnlocked"] = "Projekt entsperrt.",
            ["general.projectLocked2"] = "Projekt gesperrt.",
            ["prop.name"] = "Name",
            ["prop.type"] = "Typ",
            ["prop.access"] = "Zugriff",
            ["prop.initialValue"] = "Anfangswert",
            ["prop.initialValueHint"] = "Wert beim Serverstart (z.B. 0, true, Hallo)",
            ["prop.initialValueDesc"] = "Wird gemäß dem Variablentyp analysiert. Leer lassen für Standard.",
            ["prop.retentive"] = "Remanent",
            ["prop.retentiveHint"] = "Wenn aktiviert, wird der Variablenwert auf der Festplatte gespeichert und beim Neustart wiederhergestellt.",
            ["prop.enableStats"] = "Statistiken aktivieren",
            ["prop.enableStatsHint"] = "Veröffentlicht Min, Max, Durchschnitt und Anzahl als OPC-Untervariablen.",
            ["prop.driverJson"] = "Treibereinstellungen (JSON)",
            ["prop.children"] = "Unterelemente",
            ["prop.folders"] = "Ordner",
            ["prop.variables"] = "Variablen",
            ["prop.interval"] = "Intervall (ms)",
            ["prop.language"] = "Sprache",
            ["prop.enabled"] = "Aktiviert",
            ["prop.cycleTime"] = "Zykluszeit (ms)",
            ["prop.dbPath"] = "Datenbankpfad",
            ["prop.slotGranularity"] = "Zeitschlitzgranularität (Minuten)",
            ["prop.holidayLocale"] = "Feiertags-Gebietsschema",
            ["prop.holidayLocaleHint"] = "Gebietsschema auswählen, um integrierte Feiertage zu laden.",
            ["prop.title"] = "Titel",
            ["prop.description"] = "Beschreibung",
            ["prop.format"] = "Format",
            ["prop.pageSize"] = "Seitengröße",
            ["prop.orientation"] = "Ausrichtung",
            ["prop.deliveryMethod"] = "Zustellmethode",
            ["prop.outputDir"] = "Ausgabeverzeichnis",
            ["prop.fileNamePattern"] = "Dateinamenmuster",
            ["prop.recipients"] = "Empfänger (kommagetrennt)",
            ["prop.emailSubject"] = "E-Mail-Betreff",
            ["prop.smtpServer"] = "SMTP-Server",
            ["prop.smtpPort"] = "SMTP-Port",
            ["prop.smtpUser"] = "SMTP-Benutzername",
            ["prop.smtpPass"] = "SMTP-Passwort",
            ["prop.smtpSsl"] = "SSL/TLS verwenden",
            ["prop.fromAddress"] = "Absenderadresse",
            ["prop.width"] = "Breite",
            ["prop.height"] = "Höhe",
            ["prop.background"] = "Hintergrund",
            ["prop.backgroundImage"] = "Hintergrundbild",
            ["prop.showInNav"] = "In Navigation anzeigen",
            ["prop.showInNavHint"] = "Wenn aktiviert, erscheint dieser Bildschirm in der Laufzeit-Navigationsleiste.",
            ["prop.symbols"] = "Symbole",
            ["prop.screenEditorHint"] = "Verwenden Sie den Bildschirm-Editor zum Entwerfen des SVG-Layouts.",
            ["prop.endpointUrl"] = "Endpunkt-URL",
            ["prop.startupScreen"] = "Startbildschirm",
            ["prop.navStyle"] = "Navigationsstil",
            ["prop.navStyleHint"] = "Legt fest, wie Bildschirme im RuntimeViewer navigiert werden.",
            ["prop.navTabs"] = "Tabs (oben)",
            ["prop.navSidebar"] = "Seitenleiste (links)",
            ["prop.navHamburger"] = "Hamburger-Menü",
            ["prop.navBottom"] = "Untere Tab-Leiste",
            ["prop.showNavBar"] = "Navigationsleiste anzeigen (Kiosk)",
            ["prop.showNavBarHint"] = "Im Kiosk-Modus ist die Navigationsleiste standardmäßig ausgeblendet.",
            ["prop.enableAnon"] = "Anonymen Zugriff aktivieren",
            ["prop.requireEditorLogin"] = "Editor-Anmeldung erforderlich",
            ["prop.requireRuntimeLogin"] = "Laufzeit-Anmeldung erforderlich",
            ["prop.requireStrongPw"] = "Starke Passwörter erforderlich",
            ["prop.diagPort"] = "Diagnose-Port",
            ["prop.diagPortHint"] = "HTTP-Port für die Diagnose-API. 0 zum Deaktivieren.",
            ["prop.accessLevel"] = "Zugriffsebene (OPC-Variablen)",
            ["prop.canAccessEditor"] = "Kann auf Projekteditor zugreifen",
            ["prop.username"] = "Benutzername",
            ["prop.group"] = "Gruppe",
            ["prop.password"] = "Passwort",
            ["prop.pwEncrypted"] = "Verschlüsselt",
            ["prop.pwResetHint"] = "Verwenden Sie das Benutzer-Panel zum Zurücksetzen.",
            ["prop.pwNotSet"] = "Kein Passwort gesetzt. Verwenden Sie das Benutzer-Panel.",
            ["prop.none"] = "(keiner)",
            ["section.folder"] = "Ordner-Eigenschaften",
            ["section.variable"] = "Variablen-Eigenschaften",
            ["section.script"] = "Skript-Eigenschaften",
            ["section.plc"] = "SPS-Programm-Eigenschaften",
            ["section.recipe"] = "Rezept-Eigenschaften",
            ["section.scheduler"] = "Zeitplan-Eigenschaften",
            ["section.report"] = "Bericht-Eigenschaften",
            ["section.screen"] = "Bildschirm-Eigenschaften",
            ["section.serverSettings"] = "Server-Einstellungen",
            ["section.screenGroup"] = "Bildschirmgruppe",
            ["section.screenGroupHint"] = "Wählen Sie einen Bildschirm zum Bearbeiten oder fügen Sie einen neuen hinzu.",
            ["section.userGroupList"] = "Benutzer &amp; Gruppen",
            ["section.userGroupListHint"] = "Rechtsklick, um eine Benutzergruppe hinzuzufügen.",
            ["section.userGroupListHint2"] = "Verwenden Sie das Benutzer-Panel für die vollständige Verwaltung.",
            ["section.userGroup"] = "Benutzergruppen-Eigenschaften",
            ["section.user"] = "Benutzer-Eigenschaften",
            ["section.users"] = "Benutzer",
            ["general.selectItem"] = "Element ausw\u00e4hlen, um Eigenschaften anzuzeigen.",
            ["prop.allowRuntimeEdit"] = "Laufzeit-Bearbeitung erlauben",
            ["prop.allowRuntimeEditHint"] = "Laufzeitbenutzer k\u00f6nnen den Zeitplan \u00e4ndern.",
            ["help.toc"] = "Inhaltsverzeichnis",
            ["help.home"] = "Startseite",
        },

        ["it"] = new()
        {
            ["menu.file"] = "File",
            ["menu.edit"] = "Modifica",
            ["menu.view"] = "Visualizza",
            ["menu.settings"] = "Impostazioni",
            ["menu.help"] = "Aiuto",

            ["menu.file.new"] = "Nuovo",
            ["menu.file.open"] = "Apri",
            ["menu.file.browseServer"] = "Sfoglia server…",
            ["menu.file.recent"] = "Recenti",
            ["menu.file.save"] = "Salva",
            ["menu.file.saveAs"] = "Salva con nome…",

            ["menu.edit.addFolder"] = "Aggiungi cartella",
            ["menu.edit.addVariable"] = "Aggiungi variabile",
            ["menu.edit.addScript"] = "Aggiungi script",
            ["menu.edit.addScreen"] = "Aggiungi schermata",
            ["menu.edit.copy"] = "Copia",
            ["menu.edit.paste"] = "Incolla",
            ["menu.edit.delete"] = "Elimina",

            ["menu.view.panels"] = "Pannelli",
            ["menu.view.maximize"] = "Massimizza pannello attivo",

            ["menu.settings.theme"] = "Tema",
            ["menu.settings.light"] = "Chiaro",
            ["menu.settings.dark"] = "Scuro",
            ["menu.settings.language"] = "Lingua",
            ["menu.settings.protection"] = "Protezione progetto",
            ["menu.settings.unlock"] = "Sblocca progetto…",
            ["menu.settings.lock"] = "Blocca progetto",
            ["menu.settings.changePw"] = "Cambia password…",
            ["menu.settings.removePw"] = "Rimuovi password…",
            ["menu.settings.setPw"] = "Imposta password…",

            ["menu.help.help"] = "Aiuto",
            ["menu.help.validate"] = "Valida progetto",
            ["menu.help.about"] = "Informazioni",

            ["toolbar.new"] = "Nuovo",
            ["toolbar.save"] = "Salva",
            ["toolbar.saveAs"] = "Salva con nome…",
            ["toolbar.undo"] = "Annulla",
            ["toolbar.redo"] = "Ripeti",
            ["toolbar.copy"] = "Copia",
            ["toolbar.paste"] = "Incolla",
            ["toolbar.delete"] = "Elimina",
            ["toolbar.addFolder"] = "Aggiungi cartella",
            ["toolbar.addVariable"] = "Aggiungi variabile",
            ["toolbar.addScript"] = "Aggiungi script",
            ["toolbar.addPlc"] = "Aggiungi programma PLC",
            ["toolbar.addRecipe"] = "Aggiungi ricetta",
            ["toolbar.addScheduler"] = "Aggiungi pianificazione",
            ["toolbar.addReport"] = "Aggiungi report",
            ["toolbar.addScreen"] = "Aggiungi schermata",
            ["toolbar.restore"] = "Ripristina layout",
            ["toolbar.maximize"] = "Massimizza pannello attivo",
            ["toolbar.toggleTheme"] = "Cambia tema",
            ["toolbar.logout"] = "Esci",

            ["status.unsaved"] = "Non salvato",
            ["status.locked"] = "Bloccato",
            ["status.unlocked"] = "Sbloccato",

            ["dialog.saveAs.title"] = "Salva con nome",
            ["dialog.saveAs.filePath"] = "Percorso file:",
            ["dialog.saveAs.current"] = "Corrente:",
            ["dialog.saveAs.cancel"] = "Annulla",
            ["dialog.saveAs.save"] = "Salva",

            ["dialog.unsaved.title"] = "Modifiche non salvate",
            ["dialog.unsaved.message"] = "Il progetto {0} ha modifiche non salvate. Vuoi salvare prima di chiudere?",
            ["dialog.unsaved.cancel"] = "Annulla",
            ["dialog.unsaved.discard"] = "Scarta",
            ["dialog.unsaved.save"] = "Salva",

            ["dialog.open.title"] = "Apri file progetto",
            ["dialog.open.empty"] = "Seleziona un'unità o inserisci un percorso",
            ["dialog.open.emptyFolder"] = "Cartella vuota o accesso negato",
            ["dialog.open.cancel"] = "Annulla",
            ["dialog.open.open"] = "Apri",

            ["dialog.unlock.title"] = "Sblocca progetto",
            ["dialog.unlock.message"] = "Questo progetto è protetto da password. Inserisci la password per modificarlo.",
            ["dialog.unlock.password"] = "Password",
            ["dialog.unlock.cancel"] = "Annulla",
            ["dialog.unlock.unlock"] = "Sblocca",

            ["dialog.setPw.title.change"] = "Cambia password progetto",
            ["dialog.setPw.title.set"] = "Imposta password progetto",
            ["dialog.setPw.msgChange"] = "Cambia o rimuovi la password di protezione del progetto.",
            ["dialog.setPw.msgSet"] = "Imposta una password per proteggere questo progetto.",
            ["dialog.setPw.currentPw"] = "Password corrente",
            ["dialog.setPw.newPw"] = "Nuova password",
            ["dialog.setPw.confirmPw"] = "Conferma password",
            ["dialog.setPw.cancel"] = "Annulla",
            ["dialog.setPw.change"] = "Cambia password",
            ["dialog.setPw.set"] = "Imposta password",

            ["dialog.changePw.title"] = "Cambia password",
            ["dialog.changePw.message"] = "Devi cambiare la password prima di continuare.",
            ["dialog.changePw.currentPw"] = "Password corrente",
            ["dialog.changePw.newPw"] = "Nuova password",
            ["dialog.changePw.confirmPw"] = "Conferma nuova password",
            ["dialog.changePw.submit"] = "Cambia password",

            ["general.serverEditor"] = "Editor Server",
            ["general.projectLocked"] = "Il progetto è bloccato. Sbloccalo prima di apportare modifiche.",
            ["general.projectUnlocked"] = "Progetto sbloccato.",
            ["general.projectLocked2"] = "Progetto bloccato.",
            ["prop.name"] = "Nome",
            ["prop.type"] = "Tipo",
            ["prop.access"] = "Accesso",
            ["prop.initialValue"] = "Valore iniziale",
            ["prop.initialValueHint"] = "Valore all'avvio del server (es. 0, true, Ciao)",
            ["prop.initialValueDesc"] = "Analizzato in base al tipo di variabile. Lasciare vuoto per il predefinito.",
            ["prop.retentive"] = "Ritentivo",
            ["prop.retentiveHint"] = "Se abilitato, il valore viene salvato su disco e ripristinato al riavvio.",
            ["prop.enableStats"] = "Abilita statistiche",
            ["prop.enableStatsHint"] = "Pubblica Min, Max, Media e Conteggio come sotto-variabili OPC.",
            ["prop.driverJson"] = "Impostazioni driver (JSON)",
            ["prop.children"] = "Figli",
            ["prop.folders"] = "Cartelle",
            ["prop.variables"] = "Variabili",
            ["prop.interval"] = "Intervallo (ms)",
            ["prop.language"] = "Linguaggio",
            ["prop.enabled"] = "Abilitato",
            ["prop.cycleTime"] = "Tempo ciclo (ms)",
            ["prop.dbPath"] = "Percorso database",
            ["prop.slotGranularity"] = "Granularità slot (minuti)",
            ["prop.holidayLocale"] = "Lingua festività",
            ["prop.title"] = "Titolo",
            ["prop.description"] = "Descrizione",
            ["prop.format"] = "Formato",
            ["prop.pageSize"] = "Dimensione pagina",
            ["prop.orientation"] = "Orientamento",
            ["prop.deliveryMethod"] = "Metodo di consegna",
            ["prop.outputDir"] = "Directory di output",
            ["prop.fileNamePattern"] = "Modello nome file",
            ["prop.recipients"] = "Destinatari (separati da virgola)",
            ["prop.emailSubject"] = "Oggetto email",
            ["prop.smtpServer"] = "Server SMTP",
            ["prop.smtpPort"] = "Porta SMTP",
            ["prop.smtpUser"] = "Utente SMTP",
            ["prop.smtpPass"] = "Password SMTP",
            ["prop.smtpSsl"] = "Usa SSL/TLS",
            ["prop.fromAddress"] = "Indirizzo mittente",
            ["prop.width"] = "Larghezza",
            ["prop.height"] = "Altezza",
            ["prop.background"] = "Sfondo",
            ["prop.backgroundImage"] = "Immagine di sfondo",
            ["prop.showInNav"] = "Mostra nella navigazione",
            ["prop.showInNavHint"] = "Se abilitato, questa schermata appare nella barra di navigazione runtime.",
            ["prop.symbols"] = "Simboli",
            ["prop.screenEditorHint"] = "Usa il pannello Editor schermata per progettare il layout SVG.",
            ["prop.endpointUrl"] = "URL endpoint",
            ["prop.startupScreen"] = "Schermata iniziale",
            ["prop.navStyle"] = "Stile navigazione",
            ["prop.navStyleHint"] = "Controlla come le schermate vengono navigate nel RuntimeViewer.",
            ["prop.navTabs"] = "Schede (in alto)",
            ["prop.navSidebar"] = "Barra laterale (sinistra)",
            ["prop.navHamburger"] = "Menu hamburger",
            ["prop.navBottom"] = "Barra schede in basso",
            ["prop.showNavBar"] = "Mostra barra di navigazione (Kiosk)",
            ["prop.showNavBarHint"] = "In modalità kiosk la barra di navigazione è nascosta per impostazione predefinita.",
            ["prop.enableAnon"] = "Abilita accesso anonimo",
            ["prop.requireEditorLogin"] = "Richiedi login editor",
            ["prop.requireRuntimeLogin"] = "Richiedi login runtime",
            ["prop.requireStrongPw"] = "Richiedi password complesse",
            ["prop.diagPort"] = "Porta diagnostica",
            ["prop.diagPortHint"] = "Porta HTTP per l'API diagnostica. Impostare a 0 per disabilitare.",
            ["prop.accessLevel"] = "Livello di accesso (variabili OPC)",
            ["prop.canAccessEditor"] = "Può accedere all'editor del progetto",
            ["prop.username"] = "Nome utente",
            ["prop.group"] = "Gruppo",
            ["prop.password"] = "Password",
            ["prop.pwEncrypted"] = "Crittografata",
            ["prop.pwResetHint"] = "Usa il pannello Utenti per reimpostare.",
            ["prop.pwNotSet"] = "Nessuna password impostata. Usa il pannello Utenti.",
            ["prop.none"] = "(nessuno)",
            ["section.folder"] = "Proprietà cartella",
            ["section.variable"] = "Proprietà variabile",
            ["section.script"] = "Proprietà script",
            ["section.plc"] = "Proprietà programma PLC",
            ["section.recipe"] = "Proprietà ricetta",
            ["section.scheduler"] = "Proprietà pianificazione",
            ["section.report"] = "Proprietà report",
            ["section.screen"] = "Proprietà schermata",
            ["section.serverSettings"] = "Impostazioni server",
            ["section.screenGroup"] = "Gruppo schermate",
            ["section.screenGroupHint"] = "Seleziona una schermata da modificare o aggiungine una nuova.",
            ["section.userGroupList"] = "Utenti e gruppi",
            ["section.userGroupListHint"] = "Tasto destro per aggiungere un gruppo utenti.",
            ["section.userGroupListHint2"] = "Usa il pannello Utenti per la gestione completa.",
            ["section.userGroup"] = "Proprietà gruppo utenti",
            ["section.user"] = "Proprietà utente",
            ["section.users"] = "Utenti",
            ["general.selectItem"] = "Seleziona un elemento per le propriet\u00e0.",
            ["prop.allowRuntimeEdit"] = "Consenti modifica runtime",
            ["prop.allowRuntimeEditHint"] = "Gli utenti runtime possono modificare la pianificazione.",
            ["prop.holidayLocaleHint"] = "Seleziona un locale per caricare i giorni festivi integrati.",
            ["help.toc"] = "Indice",
            ["help.home"] = "Home",
        },

        ["fr"] = new()
        {
            ["menu.file"] = "Fichier",
            ["menu.edit"] = "Édition",
            ["menu.view"] = "Affichage",
            ["menu.settings"] = "Paramètres",
            ["menu.help"] = "Aide",

            ["menu.file.new"] = "Nouveau",
            ["menu.file.open"] = "Ouvrir",
            ["menu.file.browseServer"] = "Parcourir le serveur…",
            ["menu.file.recent"] = "Récents",
            ["menu.file.save"] = "Enregistrer",
            ["menu.file.saveAs"] = "Enregistrer sous…",

            ["menu.edit.addFolder"] = "Ajouter un dossier",
            ["menu.edit.addVariable"] = "Ajouter une variable",
            ["menu.edit.addScript"] = "Ajouter un script",
            ["menu.edit.addScreen"] = "Ajouter un écran",
            ["menu.edit.copy"] = "Copier",
            ["menu.edit.paste"] = "Coller",
            ["menu.edit.delete"] = "Supprimer",

            ["menu.view.panels"] = "Panneaux",
            ["menu.view.maximize"] = "Maximiser le panneau actif",

            ["menu.settings.theme"] = "Thème",
            ["menu.settings.light"] = "Clair",
            ["menu.settings.dark"] = "Sombre",
            ["menu.settings.language"] = "Langue",
            ["menu.settings.protection"] = "Protection du projet",
            ["menu.settings.unlock"] = "Déverrouiller le projet…",
            ["menu.settings.lock"] = "Verrouiller le projet",
            ["menu.settings.changePw"] = "Changer le mot de passe…",
            ["menu.settings.removePw"] = "Supprimer le mot de passe…",
            ["menu.settings.setPw"] = "Définir un mot de passe…",

            ["menu.help.help"] = "Aide",
            ["menu.help.validate"] = "Valider le projet",
            ["menu.help.about"] = "À propos",

            ["toolbar.new"] = "Nouveau",
            ["toolbar.save"] = "Enregistrer",
            ["toolbar.saveAs"] = "Enregistrer sous…",
            ["toolbar.undo"] = "Annuler",
            ["toolbar.redo"] = "Rétablir",
            ["toolbar.copy"] = "Copier",
            ["toolbar.paste"] = "Coller",
            ["toolbar.delete"] = "Supprimer",
            ["toolbar.addFolder"] = "Ajouter un dossier",
            ["toolbar.addVariable"] = "Ajouter une variable",
            ["toolbar.addScript"] = "Ajouter un script",
            ["toolbar.addPlc"] = "Ajouter un programme API",
            ["toolbar.addRecipe"] = "Ajouter une recette",
            ["toolbar.addScheduler"] = "Ajouter un planificateur",
            ["toolbar.addReport"] = "Ajouter un rapport",
            ["toolbar.addScreen"] = "Ajouter un écran",
            ["toolbar.restore"] = "Restaurer la disposition",
            ["toolbar.maximize"] = "Maximiser le panneau actif",
            ["toolbar.toggleTheme"] = "Changer le thème",
            ["toolbar.logout"] = "Déconnexion",

            ["status.unsaved"] = "Non enregistré",
            ["status.locked"] = "Verrouillé",
            ["status.unlocked"] = "Déverrouillé",

            ["dialog.saveAs.title"] = "Enregistrer sous",
            ["dialog.saveAs.filePath"] = "Chemin du fichier :",
            ["dialog.saveAs.current"] = "Actuel :",
            ["dialog.saveAs.cancel"] = "Annuler",
            ["dialog.saveAs.save"] = "Enregistrer",

            ["dialog.unsaved.title"] = "Modifications non enregistrées",
            ["dialog.unsaved.message"] = "Le projet {0} a des modifications non enregistrées. Voulez-vous enregistrer avant de fermer ?",
            ["dialog.unsaved.cancel"] = "Annuler",
            ["dialog.unsaved.discard"] = "Abandonner",
            ["dialog.unsaved.save"] = "Enregistrer",

            ["dialog.open.title"] = "Ouvrir un fichier projet",
            ["dialog.open.empty"] = "Sélectionnez un lecteur ou entrez un chemin",
            ["dialog.open.emptyFolder"] = "Dossier vide ou accès refusé",
            ["dialog.open.cancel"] = "Annuler",
            ["dialog.open.open"] = "Ouvrir",

            ["dialog.unlock.title"] = "Déverrouiller le projet",
            ["dialog.unlock.message"] = "Ce projet est protégé par mot de passe. Entrez le mot de passe pour le modifier.",
            ["dialog.unlock.password"] = "Mot de passe",
            ["dialog.unlock.cancel"] = "Annuler",
            ["dialog.unlock.unlock"] = "Déverrouiller",

            ["dialog.setPw.title.change"] = "Changer le mot de passe du projet",
            ["dialog.setPw.title.set"] = "Définir le mot de passe du projet",
            ["dialog.setPw.msgChange"] = "Changer ou supprimer le mot de passe de protection du projet.",
            ["dialog.setPw.msgSet"] = "Définissez un mot de passe pour protéger ce projet.",
            ["dialog.setPw.currentPw"] = "Mot de passe actuel",
            ["dialog.setPw.newPw"] = "Nouveau mot de passe",
            ["dialog.setPw.confirmPw"] = "Confirmer le mot de passe",
            ["dialog.setPw.cancel"] = "Annuler",
            ["dialog.setPw.change"] = "Changer le mot de passe",
            ["dialog.setPw.set"] = "Définir le mot de passe",

            ["dialog.changePw.title"] = "Changer le mot de passe",
            ["dialog.changePw.message"] = "Vous devez changer votre mot de passe avant de continuer.",
            ["dialog.changePw.currentPw"] = "Mot de passe actuel",
            ["dialog.changePw.newPw"] = "Nouveau mot de passe",
            ["dialog.changePw.confirmPw"] = "Confirmer le nouveau mot de passe",
            ["dialog.changePw.submit"] = "Changer le mot de passe",

            ["general.serverEditor"] = "Éditeur serveur",
            ["general.projectLocked"] = "Le projet est verrouillé. Déverrouillez-le d'abord.",
            ["general.projectUnlocked"] = "Projet déverrouillé.",
            ["general.projectLocked2"] = "Projet verrouillé.",
            ["prop.name"] = "Nom",
            ["prop.type"] = "Type",
            ["prop.access"] = "Accès",
            ["prop.initialValue"] = "Valeur initiale",
            ["prop.initialValueHint"] = "Valeur au démarrage du serveur (ex. 0, true, Bonjour)",
            ["prop.initialValueDesc"] = "Analysée selon le type de variable. Laisser vide pour la valeur par défaut.",
            ["prop.retentive"] = "Rémanent",
            ["prop.retentiveHint"] = "Si activé, la valeur est sauvegardée sur disque et restaurée au redémarrage.",
            ["prop.enableStats"] = "Activer les statistiques",
            ["prop.enableStatsHint"] = "Publie Min, Max, Moyenne et Nombre comme sous-variables OPC.",
            ["prop.driverJson"] = "Paramètres du pilote (JSON)",
            ["prop.children"] = "Enfants",
            ["prop.folders"] = "Dossiers",
            ["prop.variables"] = "Variables",
            ["prop.interval"] = "Intervalle (ms)",
            ["prop.language"] = "Langage",
            ["prop.enabled"] = "Activé",
            ["prop.cycleTime"] = "Temps de cycle (ms)",
            ["prop.dbPath"] = "Chemin de la base de données",
            ["prop.slotGranularity"] = "Granularité des créneaux (minutes)",
            ["prop.holidayLocale"] = "Locale des jours fériés",
            ["prop.holidayLocaleHint"] = "Sélectionnez un locale pour charger les jours fériés intégrés.",
            ["prop.title"] = "Titre",
            ["prop.description"] = "Description",
            ["prop.format"] = "Format",
            ["prop.pageSize"] = "Taille de page",
            ["prop.orientation"] = "Orientation",
            ["prop.deliveryMethod"] = "Méthode de livraison",
            ["prop.outputDir"] = "Répertoire de sortie",
            ["prop.fileNamePattern"] = "Modèle de nom de fichier",
            ["prop.recipients"] = "Destinataires (séparés par virgule)",
            ["prop.emailSubject"] = "Objet de l'email",
            ["prop.smtpServer"] = "Serveur SMTP",
            ["prop.smtpPort"] = "Port SMTP",
            ["prop.smtpUser"] = "Utilisateur SMTP",
            ["prop.smtpPass"] = "Mot de passe SMTP",
            ["prop.smtpSsl"] = "Utiliser SSL/TLS",
            ["prop.fromAddress"] = "Adresse de l'expéditeur",
            ["prop.width"] = "Largeur",
            ["prop.height"] = "Hauteur",
            ["prop.background"] = "Arrière-plan",
            ["prop.backgroundImage"] = "Image d'arrière-plan",
            ["prop.showInNav"] = "Afficher dans la navigation",
            ["prop.showInNavHint"] = "Si activé, cet écran apparaît dans la barre de navigation runtime.",
            ["prop.symbols"] = "Symboles",
            ["prop.screenEditorHint"] = "Utilisez le panneau Éditeur d'écran pour concevoir la mise en page SVG.",
            ["prop.endpointUrl"] = "URL du point de terminaison",
            ["prop.startupScreen"] = "Écran de démarrage",
            ["prop.navStyle"] = "Style de navigation",
            ["prop.navStyleHint"] = "Définit la navigation entre écrans dans le RuntimeViewer.",
            ["prop.navTabs"] = "Onglets (haut)",
            ["prop.navSidebar"] = "Barre latérale (gauche)",
            ["prop.navHamburger"] = "Menu hamburger",
            ["prop.navBottom"] = "Barre d'onglets en bas",
            ["prop.showNavBar"] = "Afficher la barre de navigation (Kiosque)",
            ["prop.showNavBarHint"] = "En mode kiosque, la barre de navigation est masquée par défaut.",
            ["prop.enableAnon"] = "Activer l'accès anonyme",
            ["prop.requireEditorLogin"] = "Exiger la connexion à l'éditeur",
            ["prop.requireRuntimeLogin"] = "Exiger la connexion runtime",
            ["prop.requireStrongPw"] = "Exiger des mots de passe forts",
            ["prop.diagPort"] = "Port de diagnostic",
            ["prop.diagPortHint"] = "Port HTTP pour l'API de diagnostic. Mettre à 0 pour désactiver.",
            ["prop.accessLevel"] = "Niveau d'accès (variables OPC)",
            ["prop.canAccessEditor"] = "Peut accéder à l'éditeur de projet",
            ["prop.username"] = "Nom d'utilisateur",
            ["prop.group"] = "Groupe",
            ["prop.password"] = "Mot de passe",
            ["prop.pwEncrypted"] = "Chiffré",
            ["prop.pwResetHint"] = "Utilisez le panneau Utilisateurs pour réinitialiser.",
            ["prop.pwNotSet"] = "Aucun mot de passe défini. Utilisez le panneau Utilisateurs.",
            ["prop.none"] = "(aucun)",
            ["section.folder"] = "Propriétés du dossier",
            ["section.variable"] = "Propriétés de la variable",
            ["section.script"] = "Propriétés du script",
            ["section.plc"] = "Propriétés du programme API",
            ["section.recipe"] = "Propriétés de la recette",
            ["section.scheduler"] = "Propriétés du planificateur",
            ["section.report"] = "Propriétés du rapport",
            ["section.screen"] = "Propriétés de l'écran",
            ["section.serverSettings"] = "Paramètres du serveur",
            ["section.screenGroup"] = "Groupe d'écrans",
            ["section.screenGroupHint"] = "Sélectionnez un écran à modifier ou ajoutez-en un nouveau.",
            ["section.userGroupList"] = "Utilisateurs et groupes",
            ["section.userGroupListHint"] = "Clic droit pour ajouter un groupe d'utilisateurs.",
            ["section.userGroupListHint2"] = "Utilisez le panneau Utilisateurs pour la gestion complète.",
            ["section.userGroup"] = "Propriétés du groupe",
            ["section.user"] = "Propriétés de l'utilisateur",
            ["section.users"] = "Utilisateurs",
            ["general.selectItem"] = "S\u00e9lectionnez un \u00e9l\u00e9ment pour ses propri\u00e9t\u00e9s.",
            ["prop.allowRuntimeEdit"] = "Autoriser la modification runtime",
            ["prop.allowRuntimeEditHint"] = "Les utilisateurs runtime peuvent modifier le programme.",
            ["help.toc"] = "Table des matières",
            ["help.home"] = "Accueil",
        },

        ["ja"] = new()
        {
            ["menu.file"] = "ファイル",
            ["menu.edit"] = "編集",
            ["menu.view"] = "表示",
            ["menu.settings"] = "設定",
            ["menu.help"] = "ヘルプ",

            ["menu.file.new"] = "新規作成",
            ["menu.file.open"] = "開く",
            ["menu.file.browseServer"] = "サーバーを参照…",
            ["menu.file.recent"] = "最近使用",
            ["menu.file.save"] = "保存",
            ["menu.file.saveAs"] = "名前を付けて保存…",

            ["menu.edit.addFolder"] = "フォルダーを追加",
            ["menu.edit.addVariable"] = "変数を追加",
            ["menu.edit.addScript"] = "スクリプトを追加",
            ["menu.edit.addScreen"] = "画面を追加",
            ["menu.edit.copy"] = "コピー",
            ["menu.edit.paste"] = "貼り付け",
            ["menu.edit.delete"] = "削除",

            ["menu.view.panels"] = "パネル",
            ["menu.view.maximize"] = "アクティブパネルを最大化",

            ["menu.settings.theme"] = "テーマ",
            ["menu.settings.light"] = "ライト",
            ["menu.settings.dark"] = "ダーク",
            ["menu.settings.language"] = "言語",
            ["menu.settings.protection"] = "プロジェクト保護",
            ["menu.settings.unlock"] = "プロジェクトのロック解除…",
            ["menu.settings.lock"] = "プロジェクトをロック",
            ["menu.settings.changePw"] = "パスワードを変更…",
            ["menu.settings.removePw"] = "パスワードを削除…",
            ["menu.settings.setPw"] = "パスワードを設定…",

            ["menu.help.help"] = "ヘルプ",
            ["menu.help.validate"] = "プロジェクトを検証",
            ["menu.help.about"] = "バージョン情報",

            ["toolbar.new"] = "新規",
            ["toolbar.save"] = "保存",
            ["toolbar.saveAs"] = "名前を付けて保存…",
            ["toolbar.undo"] = "元に戻す",
            ["toolbar.redo"] = "やり直し",
            ["toolbar.copy"] = "コピー",
            ["toolbar.paste"] = "貼り付け",
            ["toolbar.delete"] = "削除",
            ["toolbar.addFolder"] = "フォルダーを追加",
            ["toolbar.addVariable"] = "変数を追加",
            ["toolbar.addScript"] = "スクリプトを追加",
            ["toolbar.addPlc"] = "PLCプログラムを追加",
            ["toolbar.addRecipe"] = "レシピを追加",
            ["toolbar.addScheduler"] = "スケジューラーを追加",
            ["toolbar.addReport"] = "レポートを追加",
            ["toolbar.addScreen"] = "画面を追加",
            ["toolbar.restore"] = "レイアウトを復元",
            ["toolbar.maximize"] = "アクティブパネルを最大化",
            ["toolbar.toggleTheme"] = "テーマ切替",
            ["toolbar.logout"] = "ログアウト",

            ["status.unsaved"] = "未保存",
            ["status.locked"] = "ロック中",
            ["status.unlocked"] = "ロック解除",

            ["dialog.saveAs.title"] = "名前を付けて保存",
            ["dialog.saveAs.filePath"] = "ファイルパス：",
            ["dialog.saveAs.current"] = "現在：",
            ["dialog.saveAs.cancel"] = "キャンセル",
            ["dialog.saveAs.save"] = "保存",

            ["dialog.unsaved.title"] = "未保存の変更",
            ["dialog.unsaved.message"] = "プロジェクト{0}に未保存の変更があります。閉じる前に保存しますか？",
            ["dialog.unsaved.cancel"] = "キャンセル",
            ["dialog.unsaved.discard"] = "破棄",
            ["dialog.unsaved.save"] = "保存",

            ["dialog.open.title"] = "プロジェクトファイルを開く",
            ["dialog.open.empty"] = "ドライブを選択するかパスを入力してください",
            ["dialog.open.emptyFolder"] = "空のフォルダーまたはアクセス拒否",
            ["dialog.open.cancel"] = "キャンセル",
            ["dialog.open.open"] = "開く",

            ["dialog.unlock.title"] = "プロジェクトのロック解除",
            ["dialog.unlock.message"] = "このプロジェクトはパスワードで保護されています。パスワードを入力してください。",
            ["dialog.unlock.password"] = "パスワード",
            ["dialog.unlock.cancel"] = "キャンセル",
            ["dialog.unlock.unlock"] = "ロック解除",

            ["dialog.setPw.title.change"] = "プロジェクトパスワードの変更",
            ["dialog.setPw.title.set"] = "プロジェクトパスワードの設定",
            ["dialog.setPw.msgChange"] = "プロジェクト保護パスワードを変更または削除します。",
            ["dialog.setPw.msgSet"] = "このプロジェクトを保護するパスワードを設定します。",
            ["dialog.setPw.currentPw"] = "現在のパスワード",
            ["dialog.setPw.newPw"] = "新しいパスワード",
            ["dialog.setPw.confirmPw"] = "パスワードの確認",
            ["dialog.setPw.cancel"] = "キャンセル",
            ["dialog.setPw.change"] = "パスワード変更",
            ["dialog.setPw.set"] = "パスワード設定",

            ["dialog.changePw.title"] = "パスワード変更",
            ["dialog.changePw.message"] = "続行するにはパスワードを変更する必要があります。",
            ["dialog.changePw.currentPw"] = "現在のパスワード",
            ["dialog.changePw.newPw"] = "新しいパスワード",
            ["dialog.changePw.confirmPw"] = "新しいパスワードの確認",
            ["dialog.changePw.submit"] = "パスワード変更",

            ["general.serverEditor"] = "サーバーエディター",
            ["general.projectLocked"] = "プロジェクトはロックされています。先にロックを解除してください。",
            ["general.projectUnlocked"] = "プロジェクトのロックが解除されました。",
            ["general.projectLocked2"] = "プロジェクトがロックされました。",
            ["prop.name"] = "名前",
            ["prop.type"] = "型",
            ["prop.access"] = "アクセス",
            ["prop.initialValue"] = "初期値",
            ["prop.initialValueHint"] = "サーバー起動時の値（例: 0, true, Hello）",
            ["prop.initialValueDesc"] = "変数の型に従って解析されます。デフォルトの場合は空のままにしてください。",
            ["prop.retentive"] = "保持",
            ["prop.retentiveHint"] = "有効にすると、変数値がディスクに保存され、再起動時に復元されます。",
            ["prop.enableStats"] = "統計を有効化",
            ["prop.enableStatsHint"] = "Min, Max, Average, CountをOPCサブ変数として公開します。",
            ["prop.driverJson"] = "ドライバー設定 (JSON)",
            ["prop.children"] = "子要素",
            ["prop.folders"] = "フォルダー",
            ["prop.variables"] = "変数",
            ["prop.interval"] = "間隔 (ms)",
            ["prop.language"] = "言語",
            ["prop.enabled"] = "有効",
            ["prop.cycleTime"] = "サイクルタイム (ms)",
            ["prop.dbPath"] = "データベースパス",
            ["prop.slotGranularity"] = "スロット粒度（分）",
            ["prop.holidayLocale"] = "祝日ロケール",
            ["prop.holidayLocaleHint"] = "組み込みの祝日を読み込むロケールを選択してください。",
            ["prop.title"] = "タイトル",
            ["prop.description"] = "説明",
            ["prop.format"] = "フォーマット",
            ["prop.pageSize"] = "ページサイズ",
            ["prop.orientation"] = "向き",
            ["prop.deliveryMethod"] = "配信方法",
            ["prop.outputDir"] = "出力ディレクトリ",
            ["prop.fileNamePattern"] = "ファイル名パターン",
            ["prop.recipients"] = "受信者（カンマ区切り）",
            ["prop.emailSubject"] = "メール件名",
            ["prop.smtpServer"] = "SMTPサーバー",
            ["prop.smtpPort"] = "SMTPポート",
            ["prop.smtpUser"] = "SMTPユーザー名",
            ["prop.smtpPass"] = "SMTPパスワード",
            ["prop.smtpSsl"] = "SSL/TLSを使用",
            ["prop.fromAddress"] = "送信者アドレス",
            ["prop.width"] = "幅",
            ["prop.height"] = "高さ",
            ["prop.background"] = "背景",
            ["prop.backgroundImage"] = "背景画像",
            ["prop.showInNav"] = "ナビゲーションに表示",
            ["prop.showInNavHint"] = "有効にすると、この画面がランタイムナビゲーションバーに表示されます。",
            ["prop.symbols"] = "シンボル",
            ["prop.screenEditorHint"] = "画面エディターパネルでSVGレイアウトを設計してください。",
            ["prop.endpointUrl"] = "エンドポイントURL",
            ["prop.startupScreen"] = "起動画面",
            ["prop.navStyle"] = "ナビゲーションスタイル",
            ["prop.navStyleHint"] = "RuntimeViewerでの画面ナビゲーション方法を制御します。",
            ["prop.navTabs"] = "タブ（上部）",
            ["prop.navSidebar"] = "サイドバー（左）",
            ["prop.navHamburger"] = "ハンバーガーメニュー",
            ["prop.navBottom"] = "下部タブバー",
            ["prop.showNavBar"] = "ナビゲーションバーを表示（キオスク）",
            ["prop.showNavBarHint"] = "キオスクモードではナビゲーションバーはデフォルトで非表示です。",
            ["prop.enableAnon"] = "匿名アクセスを有効化",
            ["prop.requireEditorLogin"] = "エディターログインを要求",
            ["prop.requireRuntimeLogin"] = "ランタイムログインを要求",
            ["prop.requireStrongPw"] = "強力なパスワードを要求",
            ["prop.diagPort"] = "診断ポート",
            ["prop.diagPortHint"] = "診断APIのHTTPポート。0で無効化。",
            ["prop.accessLevel"] = "アクセスレベル（OPC変数）",
            ["prop.canAccessEditor"] = "プロジェクトエディターにアクセス可能",
            ["prop.username"] = "ユーザー名",
            ["prop.group"] = "グループ",
            ["prop.password"] = "パスワード",
            ["prop.pwEncrypted"] = "暗号化済み",
            ["prop.pwResetHint"] = "ユーザーパネルでリセットしてください。",
            ["prop.pwNotSet"] = "パスワード未設定。ユーザーパネルで設定してください。",
            ["prop.none"] = "（なし）",
            ["section.folder"] = "フォルダーのプロパティ",
            ["section.variable"] = "変数のプロパティ",
            ["section.script"] = "スクリプトのプロパティ",
            ["section.plc"] = "PLCプログラムのプロパティ",
            ["section.recipe"] = "レシピのプロパティ",
            ["section.scheduler"] = "スケジューラーのプロパティ",
            ["section.report"] = "レポートのプロパティ",
            ["section.screen"] = "画面のプロパティ",
            ["section.serverSettings"] = "サーバー設定",
            ["section.screenGroup"] = "画面グループ",
            ["section.screenGroupHint"] = "編集する画面を選択するか、新しい画面を追加してください。",
            ["section.userGroupList"] = "ユーザーとグループ",
            ["section.userGroupListHint"] = "右クリックでユーザーグループを追加します。",
            ["section.userGroupListHint2"] = "完全な管理にはユーザーパネルを使用してください。",
            ["section.userGroup"] = "ユーザーグループのプロパティ",
            ["section.user"] = "ユーザーのプロパティ",
            ["section.users"] = "ユーザー",
            ["general.selectItem"] = "\u30a2\u30a4\u30c6\u30e0\u3092\u9078\u629e\u3057\u3066\u30d7\u30ed\u30d1\u30c6\u30a3\u3092\u8868\u793a",
            ["prop.allowRuntimeEdit"] = "\u30e9\u30f3\u30bf\u30a4\u30e0\u7de8\u96c6\u3092\u8a31\u53ef",
            ["prop.allowRuntimeEditHint"] = "\u30e9\u30f3\u30bf\u30a4\u30e0\u30e6\u30fc\u30b6\u30fc\u304c\u30b9\u30b1\u30b8\u30e5\u30fc\u30eb\u3092\u5909\u66f4\u53ef\u80fd",
            ["help.toc"] = "目次",
            ["help.home"] = "ホーム",
        },

        ["zh"] = new()
        {
            ["menu.file"] = "文件",
            ["menu.edit"] = "编辑",
            ["menu.view"] = "视图",
            ["menu.settings"] = "设置",
            ["menu.help"] = "帮助",

            ["menu.file.new"] = "新建",
            ["menu.file.open"] = "打开",
            ["menu.file.browseServer"] = "浏览服务器…",
            ["menu.file.recent"] = "最近使用",
            ["menu.file.save"] = "保存",
            ["menu.file.saveAs"] = "另存为…",

            ["menu.edit.addFolder"] = "添加文件夹",
            ["menu.edit.addVariable"] = "添加变量",
            ["menu.edit.addScript"] = "添加脚本",
            ["menu.edit.addScreen"] = "添加画面",
            ["menu.edit.copy"] = "复制",
            ["menu.edit.paste"] = "粘贴",
            ["menu.edit.delete"] = "删除",

            ["menu.view.panels"] = "面板",
            ["menu.view.maximize"] = "最大化活动面板",

            ["menu.settings.theme"] = "主题",
            ["menu.settings.light"] = "浅色",
            ["menu.settings.dark"] = "深色",
            ["menu.settings.language"] = "语言",
            ["menu.settings.protection"] = "项目保护",
            ["menu.settings.unlock"] = "解锁项目…",
            ["menu.settings.lock"] = "锁定项目",
            ["menu.settings.changePw"] = "更改密码…",
            ["menu.settings.removePw"] = "删除密码…",
            ["menu.settings.setPw"] = "设置密码…",

            ["menu.help.help"] = "帮助",
            ["menu.help.validate"] = "验证项目",
            ["menu.help.about"] = "关于",

            ["toolbar.new"] = "新建",
            ["toolbar.save"] = "保存",
            ["toolbar.saveAs"] = "另存为…",
            ["toolbar.undo"] = "撤销",
            ["toolbar.redo"] = "重做",
            ["toolbar.copy"] = "复制",
            ["toolbar.paste"] = "粘贴",
            ["toolbar.delete"] = "删除",
            ["toolbar.addFolder"] = "添加文件夹",
            ["toolbar.addVariable"] = "添加变量",
            ["toolbar.addScript"] = "添加脚本",
            ["toolbar.addPlc"] = "添加PLC程序",
            ["toolbar.addRecipe"] = "添加配方",
            ["toolbar.addScheduler"] = "添加调度器",
            ["toolbar.addReport"] = "添加报表",
            ["toolbar.addScreen"] = "添加画面",
            ["toolbar.restore"] = "还原布局",
            ["toolbar.maximize"] = "最大化活动面板",
            ["toolbar.toggleTheme"] = "切换主题",
            ["toolbar.logout"] = "注销",

            ["status.unsaved"] = "未保存",
            ["status.locked"] = "已锁定",
            ["status.unlocked"] = "已解锁",

            ["dialog.saveAs.title"] = "另存为",
            ["dialog.saveAs.filePath"] = "文件路径：",
            ["dialog.saveAs.current"] = "当前：",
            ["dialog.saveAs.cancel"] = "取消",
            ["dialog.saveAs.save"] = "保存",

            ["dialog.unsaved.title"] = "未保存的更改",
            ["dialog.unsaved.message"] = "项目{0}有未保存的更改。关闭前是否保存？",
            ["dialog.unsaved.cancel"] = "取消",
            ["dialog.unsaved.discard"] = "放弃",
            ["dialog.unsaved.save"] = "保存",

            ["dialog.open.title"] = "打开项目文件",
            ["dialog.open.empty"] = "选择驱动器或输入路径",
            ["dialog.open.emptyFolder"] = "空文件夹或访问被拒绝",
            ["dialog.open.cancel"] = "取消",
            ["dialog.open.open"] = "打开",

            ["dialog.unlock.title"] = "解锁项目",
            ["dialog.unlock.message"] = "此项目受密码保护。请输入密码以进行编辑。",
            ["dialog.unlock.password"] = "密码",
            ["dialog.unlock.cancel"] = "取消",
            ["dialog.unlock.unlock"] = "解锁",

            ["dialog.setPw.title.change"] = "更改项目密码",
            ["dialog.setPw.title.set"] = "设置项目密码",
            ["dialog.setPw.msgChange"] = "更改或删除项目保护密码。",
            ["dialog.setPw.msgSet"] = "设置密码以保护此项目。",
            ["dialog.setPw.currentPw"] = "当前密码",
            ["dialog.setPw.newPw"] = "新密码",
            ["dialog.setPw.confirmPw"] = "确认密码",
            ["dialog.setPw.cancel"] = "取消",
            ["dialog.setPw.change"] = "更改密码",
            ["dialog.setPw.set"] = "设置密码",

            ["dialog.changePw.title"] = "更改密码",
            ["dialog.changePw.message"] = "您必须在继续之前更改密码。",
            ["dialog.changePw.currentPw"] = "当前密码",
            ["dialog.changePw.newPw"] = "新密码",
            ["dialog.changePw.confirmPw"] = "确认新密码",
            ["dialog.changePw.submit"] = "更改密码",

            ["general.serverEditor"] = "服务器编辑器",
            ["general.projectLocked"] = "项目已锁定。请先解锁才能进行更改。",
            ["general.projectUnlocked"] = "项目已解锁。",
            ["general.projectLocked2"] = "项目已锁定。",
            ["prop.name"] = "名称",
            ["prop.type"] = "类型",
            ["prop.access"] = "访问",
            ["prop.initialValue"] = "初始值",
            ["prop.initialValueHint"] = "服务器启动时的值（例如 0, true, 你好）",
            ["prop.initialValueDesc"] = "根据变量类型解析。留空使用默认值。",
            ["prop.retentive"] = "保持性",
            ["prop.retentiveHint"] = "启用后，变量值将保存到磁盘并在重启时恢复。",
            ["prop.enableStats"] = "启用统计",
            ["prop.enableStatsHint"] = "将最小值、最大值、平均值和计数作为OPC子变量发布。",
            ["prop.driverJson"] = "驱动程序设置 (JSON)",
            ["prop.children"] = "子项",
            ["prop.folders"] = "文件夹",
            ["prop.variables"] = "变量",
            ["prop.interval"] = "间隔 (ms)",
            ["prop.language"] = "语言",
            ["prop.enabled"] = "启用",
            ["prop.cycleTime"] = "循环时间 (ms)",
            ["prop.dbPath"] = "数据库路径",
            ["prop.slotGranularity"] = "时间槽粒度（分钟）",
            ["prop.holidayLocale"] = "假日区域设置",
            ["prop.title"] = "标题",
            ["prop.description"] = "描述",
            ["prop.format"] = "格式",
            ["prop.pageSize"] = "页面大小",
            ["prop.orientation"] = "方向",
            ["prop.deliveryMethod"] = "交付方式",
            ["prop.outputDir"] = "输出目录",
            ["prop.fileNamePattern"] = "文件名模式",
            ["prop.recipients"] = "收件人（逗号分隔）",
            ["prop.emailSubject"] = "电子邮件主题",
            ["prop.smtpServer"] = "SMTP服务器",
            ["prop.smtpPort"] = "SMTP端口",
            ["prop.smtpUser"] = "SMTP用户名",
            ["prop.smtpPass"] = "SMTP密码",
            ["prop.smtpSsl"] = "使用SSL/TLS",
            ["prop.fromAddress"] = "发件人地址",
            ["prop.width"] = "宽度",
            ["prop.height"] = "高度",
            ["prop.background"] = "背景",
            ["prop.backgroundImage"] = "背景图像",
            ["prop.showInNav"] = "在导航中显示",
            ["prop.showInNavHint"] = "启用后，此画面将显示在运行时导航栏中。",
            ["prop.symbols"] = "符号",
            ["prop.screenEditorHint"] = "使用画面编辑器面板设计SVG布局。",
            ["prop.endpointUrl"] = "端点URL",
            ["prop.startupScreen"] = "启动画面",
            ["prop.navStyle"] = "导航样式",
            ["prop.navStyleHint"] = "控制RuntimeViewer中画面的导航方式。",
            ["prop.navTabs"] = "选项卡（顶部）",
            ["prop.navSidebar"] = "侧边栏（左侧）",
            ["prop.navHamburger"] = "汉堡菜单",
            ["prop.navBottom"] = "底部选项卡栏",
            ["prop.showNavBar"] = "显示导航栏（信息亭）",
            ["prop.showNavBarHint"] = "在信息亭模式下，导航栏默认隐藏。",
            ["prop.enableAnon"] = "启用匿名访问",
            ["prop.requireEditorLogin"] = "要求编辑器登录",
            ["prop.requireRuntimeLogin"] = "要求运行时登录",
            ["prop.requireStrongPw"] = "要求强密码",
            ["prop.diagPort"] = "诊断端口",
            ["prop.diagPortHint"] = "诊断API的HTTP端口。设为0以禁用。",
            ["prop.accessLevel"] = "访问级别（OPC变量）",
            ["prop.canAccessEditor"] = "可以访问项目编辑器",
            ["prop.username"] = "用户名",
            ["prop.group"] = "组",
            ["prop.password"] = "密码",
            ["prop.pwEncrypted"] = "已加密",
            ["prop.pwResetHint"] = "使用用户面板重置。",
            ["prop.pwNotSet"] = "未设置密码。使用用户面板设置。",
            ["prop.none"] = "（无）",
            ["section.folder"] = "文件夹属性",
            ["section.variable"] = "变量属性",
            ["section.script"] = "脚本属性",
            ["section.plc"] = "PLC程序属性",
            ["section.recipe"] = "配方属性",
            ["section.scheduler"] = "调度器属性",
            ["section.report"] = "报表属性",
            ["section.screen"] = "画面属性",
            ["section.serverSettings"] = "服务器设置",
            ["section.screenGroup"] = "画面组",
            ["section.screenGroupHint"] = "选择一个画面进行编辑，或添加新画面。",
            ["section.userGroupList"] = "用户和组",
            ["section.userGroupListHint"] = "右键单击以添加用户组。",
            ["section.userGroupListHint2"] = "使用用户面板进行完整管理。",
            ["section.userGroup"] = "用户组属性",
            ["section.user"] = "用户属性",
            ["section.users"] = "用户",
            ["general.selectItem"] = "\u9009\u62e9\u9879\u76ee\u4ee5\u67e5\u770b\u5c5e\u6027",
            ["prop.allowRuntimeEdit"] = "\u5141\u8bb8\u8fd0\u884c\u65f6\u7f16\u8f91",
            ["prop.allowRuntimeEditHint"] = "\u8fd0\u884c\u65f6\u7528\u6237\u53ef\u4fee\u6539\u8ba1\u5212",
            ["prop.holidayLocaleHint"] = "\u9009\u62e9\u533a\u57df\u4ee5\u52a0\u8f7d\u5185\u7f6e\u516c\u5171\u5047\u65e5\u3002",
            ["help.toc"] = "目录",
            ["help.home"] = "首页",
        },
    };
}
