<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\DocumentManagers\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\DocumentManagers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  
  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="Mindscape.Raygun4Net" Version="5.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>

    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Pdf.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Export, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.CodeView.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Extensions, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Layout.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Printing" />
    <Reference Include="System.Runtime.Serialization">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Discovery" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Speech" />
    <Reference Include="System.Web" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Data.DataSetExtensions">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="UIAutomationProvider">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="UIAutomationTypes" />
    <Reference Include="WindowsBase">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="PresentationCore">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
    <Reference Include="PresentationFramework">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Page Include="ChildProjectControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\MenuControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\ToolbarControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\BarCommonItems.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\ListScreenEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\AutoloadScreenListPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Service\ServicesControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\StartupControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="FolderTreeControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="NewFolderControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\LatitudePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ListUriLogicEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ListUriEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\LongitudePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ScreenUriPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\StartTypePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ProjectFolderPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\ProjectTypePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\StartupLogicsPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\StartupScriptsPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="ResourcePicker.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="ResourceTreeControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UFProjectExplorerUI.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\EnterKey.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\NewKey.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\DeployClient\DeployClient.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\ProgressDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="UserControls\ProcessOutput.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
	<Page Include="UserControls\RemoteProjectsList.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="UIGeneralCommands.cs" />
    <Compile Include="EventLogHelper\EventLogCommand.cs" />
    <Compile Include="Converters\TagToContextMenuConverter.cs" />
    <Compile Include="Converters\WorkspaceToPathConverter.cs" />
    <Compile Include="Document\PrechargedScreen.cs" />
    <Compile Include="MenuControls\MenuControl.xaml.cs">
      <DependentUpon>MenuControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\ToolbarControl.xaml.cs">
      <DependentUpon>ToolbarControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\BarCommonItems.xaml.cs">
      <DependentUpon>BarCommonItems.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ListScreenEditor.xaml.cs">
      <DependentUpon>ListScreenEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\AutoloadScreenListPropertyEditor.xaml.cs">
      <DependentUpon>AutoloadScreenListPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="ScriptHelpers\TTS.cs" />
    <Compile Include="Service\ServicesControl.xaml.cs">
      <DependentUpon>ServicesControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\StartupControl.xaml.cs">
      <DependentUpon>StartupControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="Converters\ActualWidthConverter.cs" />
    <Compile Include="Converters\ServiceModelConverter.cs" />
    <Compile Include="Converters\DisplayNameConverter.cs" />
	<Compile Include="Converters\ProcessNameConverter.cs" />
    <Compile Include="Document\StartupScript.cs" />
    <Compile Include="ChildProjectControl.xaml.cs">
      <DependentUpon>ChildProjectControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="FolderTreeControl.xaml.cs">
      <DependentUpon>FolderTreeControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="NewFolderControl.xaml.cs">
      <DependentUpon>NewFolderControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\LatitudePropertyEditor.xaml.cs">
      <DependentUpon>LatitudePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ListUriLogicEditor.xaml.cs">
      <DependentUpon>ListUriLogicEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ListUriEditor.xaml.cs">
      <DependentUpon>ListUriEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\LongitudePropertyEditor.xaml.cs">
      <DependentUpon>LongitudePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ScreenUriPropertyEditor.xaml.cs">
      <DependentUpon>ScreenUriPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\StartTypePropertyEditor.xaml.cs">
      <DependentUpon>StartTypePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ProjectFolderPropertyEditor.xaml.cs">
      <DependentUpon>ProjectFolderPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ProjectTypePropertyEditor.xaml.cs">
      <DependentUpon>ProjectTypePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\StartupLogicsPropertyEditor.xaml.cs">
      <DependentUpon>StartupLogicsPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\StartupScriptsPropertyEditor.xaml.cs">
      <DependentUpon>StartupScriptsPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="ResourcePicker.xaml.cs">
      <DependentUpon>ResourcePicker.xaml</DependentUpon>
    </Compile>
    <Compile Include="ResourceTreeControl.xaml.cs">
      <DependentUpon>ResourceTreeControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="ScriptHelpers\Alarms.cs" />
    <Compile Include="ScriptHelpers\ItemConnectedEventArgs.cs" />
    <Compile Include="ScriptHelpers\VariableChangedEventArgs.cs" />
    <Compile Include="ScriptHelpers\Screens.cs" />
    <Compile Include="ScriptHelpers\Scripts.cs" />
    <Compile Include="ScriptHelpers\Servers.cs" />
    <Compile Include="ScriptHelpers\Strings.cs" />
    <Compile Include="Properties\UICommandResource.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>UICommandResource.resx</DependentUpon>
    </Compile>
    <Compile Include="Service\ServiceViewModel.cs" />
    <Compile Include="Service\DiscoveredService.cs" />
    <Compile Include="Service\UFWebClientServiceControl.cs" />
    <Compile Include="Service\UFWebHMIServiceControl.cs" />
    <Compile Include="UFProjectExplorerUI.xaml.cs">
      <DependentUpon>UFProjectExplorerUI.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\EnterKey.xaml.cs">
      <DependentUpon>EnterKey.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\NewKey.xaml.cs">
      <DependentUpon>NewKey.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\DeployClient\DeployClient.xaml.cs">
      <DependentUpon>DeployClient.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\ProgressDialog.xaml.cs">
      <DependentUpon>ProgressDialog.xaml</DependentUpon>
    </Compile>
    <Compile Include="UserControls\ProcessOutput.xaml.cs">
      <DependentUpon>ProcessOutput.xaml</DependentUpon>
    </Compile>
	<Compile Include="UserControls\RemoteProjectsList.xaml.cs">
      <DependentUpon>RemoteProjectsList.xaml</DependentUpon>
    </Compile>
    <EmbeddedResource Include="Properties\UICommandResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UICommandResource.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="EventLogHelper\EventLogCommand.cs" />
    <Compile Include="UserControls\DeployClient\DeployClientProfile.cs" />
    <Compile Include="UserControls\DeployClient\DeployClientVM.cs" />
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="Document\UFChildProjectData.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\WPFUtilities\CryptString\CryptString.cs">
      <Link>CrypString\CryptString.cs</Link>
    </Compile>
    <Compile Include="ComponentService\UFProjectManagerComponent.cs" />
    <Compile Include="Document\ProjectStatus.cs" />
    <Compile Include="Document\ResourceFolderWatcher.cs" />
    <Compile Include="Document\UFControllerData.cs" />
    <Compile Include="Document\UFProjectDocument.cs" />
    <Compile Include="Document\StartupLogic.cs" />
    <Compile Include="Document\UriModel.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Settings.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <None Include="app.config" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="PropertyDataTemplate\ProjectTypePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="PropertyDataTemplate\StartTypePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="UserControls\ProcessOutput.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
	<None Update="UserControls\RemoteProjectsList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommonControls\CommonControls.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\LightSharedResources\LightSharedResources.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Converters\Converters.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\LogicServiceCMS\LogicServiceCMS.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MSZui\MSZui.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ProjectManagerService\UFProjectService.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScriptServiceCMS\ScriptServiceCMS.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScriptVariableValues\ScriptVariableValues.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServiceInstaller\ServiceInstaller.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Pads\Pads.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TerraBrowser\TerraBrowser.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFProcessServiceCMS\UFProcessServiceCMS.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\VFS\VFS.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\SysVariables\SysVariables.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WebHMIDesignHelper\WebHMIDesignHelper.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslatableMenu\TranslatableMenu\TranslatableMenu.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DeployClientLib\DeployClientLib.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ProcessData\ProcessData.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Beeper\Beeper.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataReader\DataReader.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataWriter\DataWriter.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Dynamics\MSZ.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ExpressionManager\ExpressionManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="EventLogHelper\" />
  </ItemGroup>
  
  <!--<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(SolutionDir)$(SolutionName)\bin\$(ConfigurationName)\DocumentManagers\&quot;
XCOPY /Y &quot;$(TargetDir)Newtonsoft.Json.dll&quot; &quot;$(SolutionDir)$(SolutionName)\bin\$(ConfigurationName)\&quot;
XCOPY /Y &quot;$(TargetDir)PubNub-Messaging.dll&quot; &quot;$(SolutionDir)$(SolutionName)\bin\$(ConfigurationName)\&quot;" />
  </Target>-->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;&#xD;&#xA;XCOPY /Y &quot;$(TargetDir)Newtonsoft.Json.*&quot; &quot;$(OutDir)..\..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>