//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQTTClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MQTTClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the driver settings, error &apos;{0}&apos;.
        /// </summary>
        public static string ErrorLoadingDriverSettings {
            get {
                return ResourceManager.GetString("ErrorLoadingDriverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver:{0}, Tag:{1} has an error into definition : {2}.
        /// </summary>
        public static string InvalidTagDefinition {
            get {
                return ResourceManager.GetString("InvalidTagDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encoding data value.
        /// </summary>
        public static string MQTTCErrorCodeErrorBadDecodingError {
            get {
                return ResourceManager.GetString("MQTTCErrorCodeErrorBadDecodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with the broker is broken.
        /// </summary>
        public static string MQTTClientConnectionBroken {
            get {
                return ResourceManager.GetString("MQTTClientConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established for channel {0}.
        /// </summary>
        public static string MQTTClientConnectionEstablished {
            get {
                return ResourceManager.GetString("MQTTClientConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} while opening connection for channel {1}.
        /// </summary>
        public static string MQTTClientConnectionException {
            get {
                return ResourceManager.GetString("MQTTClientConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}: unacceptable protocol version.
        /// </summary>
        public static string MQTTClientConnectionRefusedError1 {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}:  identifier rejected.
        /// </summary>
        public static string MQTTClientConnectionRefusedError2 {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}: Server unavailable.
        /// </summary>
        public static string MQTTClientConnectionRefusedError3 {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}: bad user name or password.
        /// </summary>
        public static string MQTTClientConnectionRefusedError4 {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}: not authorized.
        /// </summary>
        public static string MQTTClientConnectionRefusedError5 {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Refused for channel {0}: error code {1}.
        /// </summary>
        public static string MQTTClientConnectionRefusedErrorUnknown {
            get {
                return ResourceManager.GetString("MQTTClientConnectionRefusedErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation of the MqttClient object failed for channel {0}.
        /// </summary>
        public static string MQTTClientErrorClientObjectAllocation {
            get {
                return ResourceManager.GetString("MQTTClientErrorClientObjectAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} while initializing the MqttClient object for channel {1}.
        /// </summary>
        public static string MQTTClientErrorClientObjectInitializationException {
            get {
                return ResourceManager.GetString("MQTTClientErrorClientObjectInitializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected values for the parameters &quot;Broker Host Name&quot;, &quot;Broker Host Port&quot; and &quot;ClientIdentifier&quot; are already used in another channel. Please, change the value of at least one of these parameters.
        /// </summary>
        public static string MQTTClientErrorDuplicatedChannel {
            get {
                return ResourceManager.GetString("MQTTClientErrorDuplicatedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hysteresis Threshold: it must be a non-negative number.
        /// </summary>
        public static string MQTTClientErrorInvalidHysteresis {
            get {
                return ResourceManager.GetString("MQTTClientErrorInvalidHysteresis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quality Of Service level.
        /// </summary>
        public static string MQTTClientErrorInvalidQualityOfServiceLevel {
            get {
                return ResourceManager.GetString("MQTTClientErrorInvalidQualityOfServiceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Topic.
        /// </summary>
        public static string MQTTClientErrorInvalidTagName {
            get {
                return ResourceManager.GetString("MQTTClientErrorInvalidTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Preparing Publish Message.
        /// </summary>
        public static string MQTTClientErrorPreparingPublishMessage {
            get {
                return ResourceManager.GetString("MQTTClientErrorPreparingPublishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Publishing Variable.
        /// </summary>
        public static string MQTTClientErrorPublish {
            get {
                return ResourceManager.GetString("MQTTClientErrorPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error publishing topic {0} on channel {1}.
        /// </summary>
        public static string MQTTClientErrorPublishing {
            get {
                return ResourceManager.GetString("MQTTClientErrorPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in publishing topic: publishing of topics is not permitted using Json format.
        /// </summary>
        public static string MQTTClientErrorPublishJson {
            get {
                return ResourceManager.GetString("MQTTClientErrorPublishJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Timeout elapsed while publishing topic {0} on channel {1}.
        /// </summary>
        public static string MQTTClientErrorPublishTimeout {
            get {
                return ResourceManager.GetString("MQTTClientErrorPublishTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error subscription failed for topic {0} on channel {1}.
        /// </summary>
        public static string MQTTClientErrorSubscribing {
            get {
                return ResourceManager.GetString("MQTTClientErrorSubscribing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Subscription.
        /// </summary>
        public static string MQTTClientErrorSubscription {
            get {
                return ResourceManager.GetString("MQTTClientErrorSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Timeout elapsed while subscribing topic {0} on channel {1}.
        /// </summary>
        public static string MQTTClientErrorSubscriptionTimeout {
            get {
                return ResourceManager.GetString("MQTTClientErrorSubscriptionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} validating server certificate.
        /// </summary>
        public static string MQTTClientErrorValidatingServerCertificate {
            get {
                return ResourceManager.GetString("MQTTClientErrorValidatingServerCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} while allocating certificate {1} for channel {2}.
        /// </summary>
        public static string MQTTClientExceptionAllocatingCertificate {
            get {
                return ResourceManager.GetString("MQTTClientExceptionAllocatingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} while subscribing channel {1}.
        /// </summary>
        public static string MQTTClientExceptionInSubscription {
            get {
                return ResourceManager.GetString("MQTTClientExceptionInSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} while publishing tag {1} on channel {2}.
        /// </summary>
        public static string MQTTClientExceptionPublishing {
            get {
                return ResourceManager.GetString("MQTTClientExceptionPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Broker Host Name.
        /// </summary>
        public static string MQTTClientInvalidBrokerHostName {
            get {
                return ResourceManager.GetString("MQTTClientInvalidBrokerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Client Identifier.
        /// </summary>
        public static string MQTTClientInvalidClientIdentifier {
            get {
                return ResourceManager.GetString("MQTTClientInvalidClientIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &quot;Json Field for Tag Value&quot;.
        /// </summary>
        public static string MQTTClientInvalidJsonField {
            get {
                return ResourceManager.GetString("MQTTClientInvalidJsonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered Max. Number of Pending Requests is invalid: it must be between 1 and 100.
        /// </summary>
        public static string MQTTClientInvalidMaxNumberOfPendingRequests {
            get {
                return ResourceManager.GetString("MQTTClientInvalidMaxNumberOfPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Protocol For Secure Connection.
        /// </summary>
        public static string MQTTClientInvalidProtocolForSecureConnection {
            get {
                return ResourceManager.GetString("MQTTClientInvalidProtocolForSecureConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the variable is invalid for the message format selected in the station.
        /// </summary>
        public static string MQTTClientInvalidVarTypeForMessageFormat {
            get {
                return ResourceManager.GetString("MQTTClientInvalidVarTypeForMessageFormat", resourceCulture);
            }
        }
    }
}
