//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFEventEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UICommandResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UICommandResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UFEventEditor.Properties.UICommandResource", typeof(UICommandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string AddNewEventDescription {
            get {
                return ResourceManager.GetString("AddNewEventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewEventGestures {
            get {
                return ResourceManager.GetString("AddNewEventGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewEventGesturesDisplayText {
            get {
                return ResourceManager.GetString("AddNewEventGesturesDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string AddNewEventName {
            get {
                return ResourceManager.GetString("AddNewEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string AddNewEventText {
            get {
                return ResourceManager.GetString("AddNewEventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Event.
        /// </summary>
        public static string AddNewEventTooltip {
            get {
                return ResourceManager.GetString("AddNewEventTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder.
        /// </summary>
        public static string AddNewFolderDescription {
            get {
                return ResourceManager.GetString("AddNewFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewFolderGestures {
            get {
                return ResourceManager.GetString("AddNewFolderGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewFolderGesturesDisplayText {
            get {
                return ResourceManager.GetString("AddNewFolderGesturesDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder.
        /// </summary>
        public static string AddNewFolderName {
            get {
                return ResourceManager.GetString("AddNewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder.
        /// </summary>
        public static string AddNewFolderText {
            get {
                return ResourceManager.GetString("AddNewFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Folder.
        /// </summary>
        public static string AddNewFolderTooltip {
            get {
                return ResourceManager.GetString("AddNewFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ShowToolbarDescription {
            get {
                return ResourceManager.GetString("ShowToolbarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShowToolbarGestures {
            get {
                return ResourceManager.GetString("ShowToolbarGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ShowToolbarGesturesDisplayText {
            get {
                return ResourceManager.GetString("ShowToolbarGesturesDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ShowToolbarName {
            get {
                return ResourceManager.GetString("ShowToolbarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ShowToolbarText {
            get {
                return ResourceManager.GetString("ShowToolbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
    }
}
