<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netcoreapp2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <DefineConstants>NET_CORE</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>
	
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataLoggerModel\DataLoggerModel.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataReader\DataReader.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataWriter\DataWriter.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFUAHistorianModel\UFUAHistorianModel.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="ReachFramework">
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.ComponentModel.DataAnnotations">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.Entity">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.Linq">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.Services.Client">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Drawing">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Printing">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xml">
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Xaml">
      <RequiredTargetFramework>4.0</RequiredTargetFramework>
      <Private>False</Private>
    </Reference>
    <Reference Include="WindowsBase">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationFramework">
      <Private>False</Private>
    </Reference>
    <Reference Include="WindowsFormsIntegration">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\wpfutilities\cryptstring\CryptString.cs">
      <Link>CrypString\CryptString.cs</Link>
    </Compile>
    <Compile Include="CommandLineOptions.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DesignTime>True</DesignTime>
    </Compile>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Update="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="DEL &quot;$(TargetDir)$(TargetFileName).config&quot;&#xD;&#xA;XCOPY /Y &quot;$(ProjectDir)App.net48.config&quot; &quot;$(TargetDir)$(TargetFileName).config*&quot;&#xD;&#xA;XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>