# Copyright (c) 2026 Claudio Fiorani
# All rights reserved.

$file = "C:\Users\cfior\source\repos\ServerEditorWeb\Components\Editor\NodeProperties.razor"
$c = [System.IO.File]::ReadAllText($file)

$nl = "`r`n"
$anchor = "        }${nl}    </div>${nl}}${nl}else if (Node is CalculatedNode calcNode)"

if (-not $c.Contains($anchor)) {
    Write-Host "ERROR: anchor not found"
    exit 1
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine('        @* ── Natural Language Query ──────────────────────────── *@')
[void]$sb.AppendLine("        <hr />")
[void]$sb.AppendLine("        <h6>Natural Language Query</h6>")
[void]$sb.AppendLine('        <div class="form-text mb-2">')
[void]$sb.AppendLine("            Let operators ask plain-English questions about historical process data and get AI-powered answers.")
[void]$sb.AppendLine("        </div>")
[void]$sb.AppendLine('        <div class="mb-3 form-check">')
[void]$sb.AppendLine('            <input class="form-check-input" type="checkbox"')
[void]$sb.AppendLine('                   checked="@(ssNode.Settings.NaturalLanguageQuery?.Enabled == true)"')
[void]$sb.AppendLine('                   @onchange="@(e => { EnsureNlQueryConfig(ssNode).Enabled = (bool)(e.Value ?? false); OnChanged(); })" />')
[void]$sb.AppendLine('            <label class="form-check-label">Enable Natural Language Query</label>')
[void]$sb.AppendLine("        </div>")
[void]$sb.AppendLine("        @if (ssNode.Settings.NaturalLanguageQuery is { Enabled: true })")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine('            <div class="row g-2 mb-2">')
[void]$sb.AppendLine('                <div class="col-6">')
[void]$sb.AppendLine('                    <label class="form-label small">AI Engine</label>')
[void]$sb.AppendLine('                    <select class="form-select form-select-sm"')
[void]$sb.AppendLine('                            value="@(ssNode.Settings.NaturalLanguageQuery.Engine)"')
[void]$sb.AppendLine('                            @onchange="@(e => { SetNlEngine(ssNode, e.Value?.ToString()); OnChanged(); })">')
[void]$sb.AppendLine('                        <option value="Ollama">Ollama (local)</option>')
[void]$sb.AppendLine('                        <option value="OpenAI">OpenAI</option>')
[void]$sb.AppendLine('                        <option value="Gemini">Gemini</option>')
[void]$sb.AppendLine("                    </select>")
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine('                <div class="col-6">')
[void]$sb.AppendLine('                    <label class="form-label small">Model</label>')
[void]$sb.AppendLine('                    <input type="text" class="form-control form-control-sm"')
[void]$sb.AppendLine('                           @bind="ssNode.Settings.NaturalLanguageQuery.Model" @bind:after="OnChanged"')
[void]$sb.AppendLine('                           placeholder="mistral" />')
[void]$sb.AppendLine('                    <div class="form-text">e.g. mistral, llama3, gpt-4o</div>')
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine("            </div>")
[void]$sb.AppendLine('            @if (ssNode.Settings.NaturalLanguageQuery.Engine == "Ollama")')
[void]$sb.AppendLine("            {")
[void]$sb.AppendLine('                <div class="mb-2">')
[void]$sb.AppendLine('                    <label class="form-label small">Ollama Base URL</label>')
[void]$sb.AppendLine('                    <input type="text" class="form-control form-control-sm"')
[void]$sb.AppendLine('                           @bind="ssNode.Settings.NaturalLanguageQuery.OllamaBaseUrl" @bind:after="OnChanged"')
[void]$sb.AppendLine('                           placeholder="http://localhost:11434" />')
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine('            @if (ssNode.Settings.NaturalLanguageQuery.Engine is "OpenAI" or "Gemini")')
[void]$sb.AppendLine("            {")
[void]$sb.AppendLine('                <div class="mb-2">')
[void]$sb.AppendLine('                    <label class="form-label small">API Key</label>')
[void]$sb.AppendLine('                    <input type="password" class="form-control form-control-sm"')
[void]$sb.AppendLine('                           @bind="ssNode.Settings.NaturalLanguageQuery.ApiKey" @bind:after="OnChanged"')
[void]$sb.AppendLine('                           placeholder="sk-..." />')
[void]$sb.AppendLine('                    <div class="form-text">Or set OPENAI_API_KEY / GEMINI_API_KEY env var on the RuntimeViewer host.</div>')
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine('            <div class="row g-2 mb-2">')
[void]$sb.AppendLine('                <div class="col-6">')
[void]$sb.AppendLine('                    <label class="form-label small">Default Time Range (min)</label>')
[void]$sb.AppendLine('                    <input type="number" class="form-control form-control-sm" min="1"')
[void]$sb.AppendLine('                           @bind="ssNode.Settings.NaturalLanguageQuery.DefaultTimeRangeMinutes" @bind:after="OnChanged" />')
[void]$sb.AppendLine('                    <div class="form-text">Fallback when user does not specify a time range.</div>')
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine('                <div class="col-6">')
[void]$sb.AppendLine('                    <label class="form-label small">Max Data Points</label>')
[void]$sb.AppendLine('                    <input type="number" class="form-control form-control-sm" min="10" max="5000"')
[void]$sb.AppendLine('                           @bind="ssNode.Settings.NaturalLanguageQuery.MaxDataPoints" @bind:after="OnChanged" />')
[void]$sb.AppendLine('                    <div class="form-text">Per-variable limit sent to the AI.</div>')
[void]$sb.AppendLine("                </div>")
[void]$sb.AppendLine("            </div>")
[void]$sb.AppendLine('            <div class="mb-2">')
[void]$sb.AppendLine('                <label class="form-label small">Input Placeholder</label>')
[void]$sb.AppendLine('                <input type="text" class="form-control form-control-sm"')
[void]$sb.AppendLine('                       @bind="ssNode.Settings.NaturalLanguageQuery.Placeholder" @bind:after="OnChanged"')
[void]$sb.AppendLine('                       placeholder="Ask about your process data..." />')
[void]$sb.AppendLine("            </div>")
[void]$sb.AppendLine("        }")
[void]$sb.Append("    </div>")
[void]$sb.Append("`r`n}")
[void]$sb.Append("`r`nelse if (Node is CalculatedNode calcNode)")

$replacement = $sb.ToString()
$c = $c.Replace($anchor, $replacement)
[System.IO.File]::WriteAllText($file, $c)
Write-Host "Done - NL Query section inserted correctly"
