//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverCodeBaseEx.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".drvSettings")]
        public string DefaultDrvFileExt {
            get {
                return ((string)(this["DefaultDrvFileExt"]));
            }
            set {
                this["DefaultDrvFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".dynJobs")]
        public string DefaultDynFileExt {
            get {
                return ((string)(this["DefaultDynFileExt"]));
            }
            set {
                this["DefaultDynFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Drivers")]
        public string TypeLabel {
            get {
                return ((string)(this["TypeLabel"]));
            }
            set {
                this["TypeLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".changeSettings")]
        public string DefaultExchFileExt {
            get {
                return ((string)(this["DefaultExchFileExt"]));
            }
            set {
                this["DefaultExchFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxConsecutivePollingHiPriJobs {
            get {
                return ((int)(this["MaxConsecutivePollingHiPriJobs"]));
            }
            set {
                this["MaxConsecutivePollingHiPriJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxConsecutivePollingInUseJobs {
            get {
                return ((int)(this["MaxConsecutivePollingInUseJobs"]));
            }
            set {
                this["MaxConsecutivePollingInUseJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxConsecutivePollingNotInUseJobs {
            get {
                return ((int)(this["MaxConsecutivePollingNotInUseJobs"]));
            }
            set {
                this["MaxConsecutivePollingNotInUseJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RefreshDiagnosticIntervall {
            get {
                return ((int)(this["RefreshDiagnosticIntervall"]));
            }
            set {
                this["RefreshDiagnosticIntervall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int MaxErrorPollingTime {
            get {
                return ((int)(this["MaxErrorPollingTime"]));
            }
            set {
                this["MaxErrorPollingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float ScheduleRemainingPercent {
            get {
                return ((float)(this["ScheduleRemainingPercent"]));
            }
            set {
                this["ScheduleRemainingPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int ClosingTimeout {
            get {
                return ((int)(this["ClosingTimeout"]));
            }
            set {
                this["ClosingTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".core")]
        public string DefaultDrvFileExtCore {
            get {
                return ((string)(this["DefaultDrvFileExtCore"]));
            }
            set {
                this["DefaultDrvFileExtCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ErrorPollingTimeMultiplier {
            get {
                return ((int)(this["ErrorPollingTimeMultiplier"]));
            }
            set {
                this["ErrorPollingTimeMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxRunningJobs {
            get {
                return ((int)(this["MaxRunningJobs"]));
            }
            set {
                this["MaxRunningJobs"] = value;
            }
        }
    }
}
