//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFRecipeExecutionContext.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UFRecipeExecutionContext.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write to PLC.
        /// </summary>
        internal static string RecipeCommandType_Activate {
            get {
                return ResourceManager.GetString("RecipeCommandType_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        internal static string RecipeCommandType_Export {
            get {
                return ResourceManager.GetString("RecipeCommandType_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        internal static string RecipeCommandType_Import {
            get {
                return ResourceManager.GetString("RecipeCommandType_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From DB.
        /// </summary>
        internal static string RecipeCommandType_Load {
            get {
                return ResourceManager.GetString("RecipeCommandType_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read From PLC.
        /// </summary>
        internal static string RecipeCommandType_Read {
            get {
                return ResourceManager.GetString("RecipeCommandType_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From DB.
        /// </summary>
        internal static string RecipeCommandType_Remove {
            get {
                return ResourceManager.GetString("RecipeCommandType_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To DB.
        /// </summary>
        internal static string RecipeCommandType_Save {
            get {
                return ResourceManager.GetString("RecipeCommandType_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string RecipeCommandType_Show {
            get {
                return ResourceManager.GetString("RecipeCommandType_Show", resourceCulture);
            }
        }
    }
}
