<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;IO_Server;MOV_BUILDER</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE;IO_Server;MOV_BUILDER</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <PackageReference Include="AmazedSaint.ElasticObject" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Pdf.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Export, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.CodeView.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.ReportDesigner.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Charts.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.XtraCharts.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.DirectoryServices.AccountManagement" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
	<Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="AlarmDispatcher.cs" />
    <Compile Include="SchedulerServer.cs" />
    <Compile Include="EventsManager.cs" />
    <Compile Include="RecipeContainer.cs" />
    <Compile Include="ReportContainer.cs" />
    <Compile Include="MenuContainer.cs" />
    <Compile Include="ShortcutContainer.cs" />
    <Compile Include="ScreenContainer.cs" />
    <Compile Include="Parameters.cs" />
    <Compile Include="TextResource.cs" />
    <Compile Include="UsersManager.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\WPFUtilities\CryptString\CryptString.cs">
      <Link>CrypString\CryptString.cs</Link>
    </Compile>
    <Compile Include="IODataServer.cs" />
    <Compile Include="ProjectBuilder.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

 <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="..\AuthenticationCredentialsProvider\ComponentService\AuthenticationCredentialsProviderComponent.cs" Link="CredentialsProvider\AuthenticationCredentialsProviderComponent.cs" />
    <Compile Include="..\UFUserEditor\CredentialsProviderHelper.cs" Link="CredentialsProvider\CredentialsProviderHelper.cs" />
  </ItemGroup>
      
	  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADEditor\ADEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADModel\ADModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADServerInfo\ADServerInfo.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MSEditor\MSEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MSSchedulerDocument\MSSchedulerSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MSModel\MSModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScreenEditor\ScreenManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScreenSettings\ScreenSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScreenParametersEditor\ScreenParametersEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScreenParameterSettings\ScreenParameterSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ScriptEditor\ScriptManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\StringEditor\StringManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\StringModel\StringModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TempVariablesModel\TempVariablesModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TempVariables\TempVariables.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFEventEditor\UFEventEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFEventModel\UFEventModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReportManager\ReportManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReportSettings\ReportSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFRecipeEditor\UFRecipeEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFRecipeSettings\UFRecipeSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFUserEditor\UFUserEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UserModel\UFUserModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFMenuEditor\UFMenuEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\MenuSettings\MenuSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFShortcutEditor\UFShortcutEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFShortcutSettings\UFShortcutSettings.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\AnimationManager\AnimationManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommandManager\CommandManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\SymbolGallery\SymbolGallery.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ToolBox\ToolBox.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslationHelpers\TranslationHelpers.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\VFS\VFS.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ExternalAuthentication\ExternalAuthentication.csproj" />
    <ProjectReference Include="..\SolutionExplorer\UFProjectManager.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFUAEditor\UFUAEditor.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFUATag\UFUAModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\DataLoggerModel\DataLoggerModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UriResolver\UriResolver.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
	  <ProjectReference Include="..\DriverBaseClassLibrary\DriverBaseInterfaces.csproj">
		  <Private>false</Private>
	  </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>