//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace UFWebClient.UFProjectManagerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UFProjectManagerServiceReference.IPolicyProvider")]
    public interface IPolicyProvider {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPolicyProvider/ProvidePolicy", ReplyAction="http://tempuri.org/IPolicyProvider/ProvidePolicyResponse")]
        System.IAsyncResult BeginProvidePolicy(System.AsyncCallback callback, object asyncState);
        
        byte[] EndProvidePolicy(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyProviderChannel : UFWebClient.UFProjectManagerServiceReference.IPolicyProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvidePolicyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProvidePolicyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyProviderClient : System.ServiceModel.ClientBase<UFWebClient.UFProjectManagerServiceReference.IPolicyProvider>, UFWebClient.UFProjectManagerServiceReference.IPolicyProvider {
        
        private BeginOperationDelegate onBeginProvidePolicyDelegate;
        
        private EndOperationDelegate onEndProvidePolicyDelegate;
        
        private System.Threading.SendOrPostCallback onProvidePolicyCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PolicyProviderClient() {
        }
        
        public PolicyProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ProvidePolicyCompletedEventArgs> ProvidePolicyCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UFWebClient.UFProjectManagerServiceReference.IPolicyProvider.BeginProvidePolicy(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProvidePolicy(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] UFWebClient.UFProjectManagerServiceReference.IPolicyProvider.EndProvidePolicy(System.IAsyncResult result) {
            return base.Channel.EndProvidePolicy(result);
        }
        
        private System.IAsyncResult OnBeginProvidePolicy(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UFWebClient.UFProjectManagerServiceReference.IPolicyProvider)(this)).BeginProvidePolicy(callback, asyncState);
        }
        
        private object[] OnEndProvidePolicy(System.IAsyncResult result) {
            byte[] retVal = ((UFWebClient.UFProjectManagerServiceReference.IPolicyProvider)(this)).EndProvidePolicy(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProvidePolicyCompleted(object state) {
            if ((this.ProvidePolicyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProvidePolicyCompleted(this, new ProvidePolicyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProvidePolicyAsync() {
            this.ProvidePolicyAsync(null);
        }
        
        public void ProvidePolicyAsync(object userState) {
            if ((this.onBeginProvidePolicyDelegate == null)) {
                this.onBeginProvidePolicyDelegate = new BeginOperationDelegate(this.OnBeginProvidePolicy);
            }
            if ((this.onEndProvidePolicyDelegate == null)) {
                this.onEndProvidePolicyDelegate = new EndOperationDelegate(this.OnEndProvidePolicy);
            }
            if ((this.onProvidePolicyCompletedDelegate == null)) {
                this.onProvidePolicyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProvidePolicyCompleted);
            }
            base.InvokeAsync(this.onBeginProvidePolicyDelegate, null, this.onEndProvidePolicyDelegate, this.onProvidePolicyCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override UFWebClient.UFProjectManagerServiceReference.IPolicyProvider CreateChannel() {
            return new PolicyProviderClientChannel(this);
        }
        
        private class PolicyProviderClientChannel : ChannelBase<UFWebClient.UFProjectManagerServiceReference.IPolicyProvider>, UFWebClient.UFProjectManagerServiceReference.IPolicyProvider {
            
            public PolicyProviderClientChannel(System.ServiceModel.ClientBase<UFWebClient.UFProjectManagerServiceReference.IPolicyProvider> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginProvidePolicy(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ProvidePolicy", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndProvidePolicy(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("ProvidePolicy", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="UFProjectManager.Services", ConfigurationName="UFProjectManagerServiceReference.IUFProjectManager")]
    public interface IUFProjectManager {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="UFProjectManager.Services/IUFProjectManager/ListActiveProjects", ReplyAction="UFProjectManager.Services/IUFProjectManager/ListActiveProjectsResponse")]
        System.IAsyncResult BeginListActiveProjects(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndListActiveProjects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="UFProjectManager.Services/IUFProjectManager/GetStartupScreen", ReplyAction="UFProjectManager.Services/IUFProjectManager/GetStartupScreenResponse")]
        System.IAsyncResult BeginGetStartupScreen(string project, System.AsyncCallback callback, object asyncState);
        
        System.Uri EndGetStartupScreen(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUFProjectManagerChannel : UFWebClient.UFProjectManagerServiceReference.IUFProjectManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListActiveProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListActiveProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStartupScreenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStartupScreenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Uri Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Uri)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UFProjectManagerClient : System.ServiceModel.ClientBase<UFWebClient.UFProjectManagerServiceReference.IUFProjectManager>, UFWebClient.UFProjectManagerServiceReference.IUFProjectManager {
        
        private BeginOperationDelegate onBeginListActiveProjectsDelegate;
        
        private EndOperationDelegate onEndListActiveProjectsDelegate;
        
        private System.Threading.SendOrPostCallback onListActiveProjectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStartupScreenDelegate;
        
        private EndOperationDelegate onEndGetStartupScreenDelegate;
        
        private System.Threading.SendOrPostCallback onGetStartupScreenCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UFProjectManagerClient() {
        }
        
        public UFProjectManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UFProjectManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UFProjectManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UFProjectManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ListActiveProjectsCompletedEventArgs> ListActiveProjectsCompleted;
        
        public event System.EventHandler<GetStartupScreenCompletedEventArgs> GetStartupScreenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UFWebClient.UFProjectManagerServiceReference.IUFProjectManager.BeginListActiveProjects(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListActiveProjects(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> UFWebClient.UFProjectManagerServiceReference.IUFProjectManager.EndListActiveProjects(System.IAsyncResult result) {
            return base.Channel.EndListActiveProjects(result);
        }
        
        private System.IAsyncResult OnBeginListActiveProjects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UFWebClient.UFProjectManagerServiceReference.IUFProjectManager)(this)).BeginListActiveProjects(callback, asyncState);
        }
        
        private object[] OnEndListActiveProjects(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((UFWebClient.UFProjectManagerServiceReference.IUFProjectManager)(this)).EndListActiveProjects(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListActiveProjectsCompleted(object state) {
            if ((this.ListActiveProjectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListActiveProjectsCompleted(this, new ListActiveProjectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListActiveProjectsAsync() {
            this.ListActiveProjectsAsync(null);
        }
        
        public void ListActiveProjectsAsync(object userState) {
            if ((this.onBeginListActiveProjectsDelegate == null)) {
                this.onBeginListActiveProjectsDelegate = new BeginOperationDelegate(this.OnBeginListActiveProjects);
            }
            if ((this.onEndListActiveProjectsDelegate == null)) {
                this.onEndListActiveProjectsDelegate = new EndOperationDelegate(this.OnEndListActiveProjects);
            }
            if ((this.onListActiveProjectsCompletedDelegate == null)) {
                this.onListActiveProjectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListActiveProjectsCompleted);
            }
            base.InvokeAsync(this.onBeginListActiveProjectsDelegate, null, this.onEndListActiveProjectsDelegate, this.onListActiveProjectsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UFWebClient.UFProjectManagerServiceReference.IUFProjectManager.BeginGetStartupScreen(string project, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStartupScreen(project, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Uri UFWebClient.UFProjectManagerServiceReference.IUFProjectManager.EndGetStartupScreen(System.IAsyncResult result) {
            return base.Channel.EndGetStartupScreen(result);
        }
        
        private System.IAsyncResult OnBeginGetStartupScreen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string project = ((string)(inValues[0]));
            return ((UFWebClient.UFProjectManagerServiceReference.IUFProjectManager)(this)).BeginGetStartupScreen(project, callback, asyncState);
        }
        
        private object[] OnEndGetStartupScreen(System.IAsyncResult result) {
            System.Uri retVal = ((UFWebClient.UFProjectManagerServiceReference.IUFProjectManager)(this)).EndGetStartupScreen(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStartupScreenCompleted(object state) {
            if ((this.GetStartupScreenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStartupScreenCompleted(this, new GetStartupScreenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStartupScreenAsync(string project) {
            this.GetStartupScreenAsync(project, null);
        }
        
        public void GetStartupScreenAsync(string project, object userState) {
            if ((this.onBeginGetStartupScreenDelegate == null)) {
                this.onBeginGetStartupScreenDelegate = new BeginOperationDelegate(this.OnBeginGetStartupScreen);
            }
            if ((this.onEndGetStartupScreenDelegate == null)) {
                this.onEndGetStartupScreenDelegate = new EndOperationDelegate(this.OnEndGetStartupScreen);
            }
            if ((this.onGetStartupScreenCompletedDelegate == null)) {
                this.onGetStartupScreenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStartupScreenCompleted);
            }
            base.InvokeAsync(this.onBeginGetStartupScreenDelegate, new object[] {
                        project}, this.onEndGetStartupScreenDelegate, this.onGetStartupScreenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override UFWebClient.UFProjectManagerServiceReference.IUFProjectManager CreateChannel() {
            return new UFProjectManagerClientChannel(this);
        }
        
        private class UFProjectManagerClientChannel : ChannelBase<UFWebClient.UFProjectManagerServiceReference.IUFProjectManager>, UFWebClient.UFProjectManagerServiceReference.IUFProjectManager {
            
            public UFProjectManagerClientChannel(System.ServiceModel.ClientBase<UFWebClient.UFProjectManagerServiceReference.IUFProjectManager> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginListActiveProjects(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ListActiveProjects", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndListActiveProjects(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("ListActiveProjects", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStartupScreen(string project, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = project;
                System.IAsyncResult _result = base.BeginInvoke("GetStartupScreen", _args, callback, asyncState);
                return _result;
            }
            
            public System.Uri EndGetStartupScreen(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Uri _result = ((System.Uri)(base.EndInvoke("GetStartupScreen", _args, result)));
                return _result;
            }
        }
    }
}
