<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAnalisysRTControl\DataAnalisysRTControl.csproj" />
    <ProjectReference Include="..\DataReader\DataReader.csproj" />
    <ProjectReference Include="..\EditDisplay\EditDisplay.csproj" />
    <ProjectReference Include="..\FastControls\FastControls.csproj" />
    <ProjectReference Include="..\ScreenEditor\ScreenManager.csproj" />
    <ProjectReference Include="..\ScreenSettings\ScreenSettings.csproj" />
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Screen\DartAndSparkline.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Screen\DartAndSparkline.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Screen\DartAndSparkline.xaml.Settings">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Screen\DartAndSparkline.xaml.Settings.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
