<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>	  
    <UserSecretsId>f97633ef-5469-4c53-8f07-084e70c144e5</UserSecretsId>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\AssemblyVersionInfo.cs" Link="Properties\AssemblyVersionInfo.cs" />
    <Compile Include="..\..\HistoricalEventControl\Constants\Constants.cs" Link="PlatformComponents\HistoricalHelpers\Constants.cs" />
    <Compile Include="..\..\HistoricalEventControl\Enums\Filters.cs" Link="PlatformComponents\HistoricalHelpers\Filters.cs" />
    <Compile Include="..\..\SharedAssemblyInfo.cs" Link="Properties\SharedAssemblyInfo.cs" />
    <Compile Include="..\..\WPFPenHelpers\MyDataValue.cs" Link="PlatformComponents\HistoricalHelpers\MyDataValue.cs" />
    <Compile Include="..\..\WPFPenHelpers\SerieSettings.cs" Link="PlatformComponents\HistoricalHelpers\SerieSettings.cs" />
    <Compile Include="..\..\WPFPenHelpers\SettingsStorage.cs" Link="PlatformComponents\HistoricalHelpers\SettingsStorage.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.AspNetCore.Common" Version="21.2.6" />
    <PackageReference Include="DevExpress.AspNetCore.Core" Version="21.2.6" />
    <PackageReference Include="DevExpress.AspNetCore.Reporting" Version="21.2.6" />
    <PackageReference Include="DevExpress.Data" Version="21.2.6" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.6" />
    <PackageReference Include="knockoutjs" Version="3.5.1" />
    <PackageReference Include="log4net" Version="2.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Connections" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
    <PackageReference Include="Mindscape.Raygun4Net.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Nager.Date" Version="1.30.0" />
    <PackageReference Include="NetMQ" Version="4.0.1.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="PlatformComponents\HistoricalHelpers\" />
    <Folder Include="wwwroot\lib\pdf.js\" />
    <Folder Include="wwwroot\scripts\components\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="wwwroot\lib\howler\dist\howler.core.min.js" />
    <None Include="wwwroot\lib\howler\dist\howler.js" />
    <None Include="wwwroot\lib\howler\dist\howler.min.js" />
    <None Include="wwwroot\lib\howler\dist\howler.spatial.min.js" />
    <None Include="wwwroot\lib\Keyboard\css\images\disabled.svg" />
    <None Include="wwwroot\lib\Keyboard\css\images\enabled.svg" />
    <None Include="wwwroot\lib\Keyboard\css\images\keyboard.svg" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-all.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-altkeyspopup.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-autocomplete.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-caret.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-extender.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-mobile.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-navigation.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-previewkeyset.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-scramble.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.extension-typing.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.keyboard.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\js\jquery.mousewheel.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\amh.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\cs.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\de.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\es.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\fa.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\fr.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\he.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\hu.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\it.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\lv.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\my.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\pl.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\pt.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\ro.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\ru.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\sq.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\languages\syr.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\albanian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\arabic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\belarusian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\bengali.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\bulgarian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\burmese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\catalan.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\chinese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\danish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ethiopic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\french.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\german.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\hebrew.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\hindi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\hungarian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\hungarianansi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\japanese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\keyboard-layouts-combined.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\keyboard-layouts-greywyvern.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\keyboard-layouts-microsoft.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\latvian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\mongolian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Albanian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Arabic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Armenian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Assamese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Azeri.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Bashkir.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Belarusian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Belgian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Bengali.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Bulgarian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Canadian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Chinese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Czech.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Danish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Devanagari.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Divehi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Dutch.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Estonian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Faeroese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Finnish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-French.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Gaelic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Georgian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-German.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Greek.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Greenlandic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Gujarati.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Hausa.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Hebrew.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Hindi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Hungarian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Icelandic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Igbo.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Inuktitut.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Irish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Italian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Japanese-Hiragana.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Kannada.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Kazakh.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Korean.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Kyrgyz-Cyrillic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Lao.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Latin-American.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Latvian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Lithuanian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Luxembourgish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Macedonian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Malayalam.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Maltese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Maori.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Marathi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Mongolian-Cyrillic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Nepali.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Norwegian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Oriya.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Pashto.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Persian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Polish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Portuguese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Punjabi.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Romanian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Russian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Sami.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Serbian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Setswana.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Sinhala.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Slovak.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Slovenian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Sorbian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Spanish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Swedish-Sami.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Swedish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Swiss-German.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Syriac.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Tajik.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Tamil.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Tatar.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Telugu.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Thai.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Tibetan.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Turkish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Turkmen.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Ukrainian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-United-Kingdom.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Urdu.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-US-Dvorak.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-US-English.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Uyghur.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Uzbek-Cyrillic.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Vietnamese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Wolof.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Yakut.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\ms-Yoruba.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\persian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\polish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\portuguese.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\romanian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\russian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\serbian.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\spanish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\swedish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\syriac.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\tamil.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\thai.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\turkish.min.js" />
    <None Include="wwwroot\lib\Keyboard\dist\layouts\vietnamese.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\fonts\fontawesome-webfont.svg" />
    <None Include="wwwroot\lib\Keyboard\docs\fonts\fontawesome-webfont.woff2" />
    <None Include="wwwroot\lib\Keyboard\docs\js\bootstrap.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\calculator.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\demo.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\jquery-latest-slim.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\jquery-migrate-3.1.0.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\jquery-ui-custom.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\jquery.jui_theme_switch.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\jquery.tipsy.min.js" />
    <None Include="wwwroot\lib\Keyboard\docs\js\prettify.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-all.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-altkeyspopup.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-autocomplete.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-caret.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-extender.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-mobile.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-navigation.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-previewkeyset.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-scramble.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.extension-typing.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.keyboard.js" />
    <None Include="wwwroot\lib\Keyboard\js\jquery.mousewheel.js" />
    <None Include="wwwroot\lib\svg.filter.js\.config\rollup.config.js" />
    <None Include="wwwroot\lib\svg.filter.js\.eslintrc.yaml" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.js" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.js.map" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.min.js" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.min.js.map" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.node.js" />
    <None Include="wwwroot\lib\svg.filter.js\dist\svg.filter.node.js.map" />
    <None Include="wwwroot\lib\svg.filter.js\LICENSE" />
    <None Include="wwwroot\lib\svg.filter.js\README.md" />
    <None Include="wwwroot\lib\svg.filter.js\spec\lib\jasmine-2.4.1\boot.js" />
    <None Include="wwwroot\lib\svg.filter.js\spec\lib\jasmine-2.4.1\console.js" />
    <None Include="wwwroot\lib\svg.filter.js\spec\lib\jasmine-2.4.1\jasmine-html.js" />
    <None Include="wwwroot\lib\svg.filter.js\spec\lib\jasmine-2.4.1\jasmine.js" />
    <None Include="wwwroot\lib\svg.filter.js\spec\spec\helper.js" />
    <None Include="wwwroot\lib\svg.filter.js\spec\spec\svg.filter.js" />
    <None Include="wwwroot\lib\svg.filter.js\src\svg.filter.js" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Sources\MJPEG_src\MJPEG\MjpegProcessor\MjpegProcessor.csproj" />
    <ProjectReference Include="..\..\ClientEditor\ClientEditor.csproj" />
    <ProjectReference Include="..\..\DataLoggerColumnList\DataLoggerColumnList.csproj" />
    <ProjectReference Include="..\..\DataLoggerModel\DataLoggerModel.csproj" />
    <ProjectReference Include="..\..\Dynamics\MSZ.csproj" />
    <ProjectReference Include="..\..\MSEditor\MSEditor.csproj" />
    <ProjectReference Include="..\..\MSModel\MSModel.csproj" />
    <ProjectReference Include="..\..\MSSchedulerDocument\MSSchedulerSettings.csproj" />
    <ProjectReference Include="..\..\MSServerInfo\MSServerInfo.csproj" />
    <ProjectReference Include="..\..\SVGHelper\SVGHelper.csproj" />
    <ProjectReference Include="..\..\OPCUAViewModel\OPCUAViewModel.csproj" />
    <ProjectReference Include="..\..\ReportAlarmStatisticsExecuter\ReportAlarms.csproj" />
    <ProjectReference Include="..\..\ReportManager\ReportManager.csproj" />
    <ProjectReference Include="..\..\ReportService\ReportService.csproj" />
    <ProjectReference Include="..\..\ScreenEditor\ScreenManager.csproj" />
    <ProjectReference Include="..\..\ScreenSettings\ScreenSettings.csproj" />
    <ProjectReference Include="..\..\SolutionExplorer\UFProjectManager.csproj" />
    <ProjectReference Include="..\..\StringEditor\StringManager.csproj" />
    <ProjectReference Include="..\..\StringModel\StringModel.csproj" />
    <ProjectReference Include="..\..\SysVariables\SysVariables.csproj" />
    <ProjectReference Include="..\..\TempVariables\TempVariables.csproj" />
    <ProjectReference Include="..\..\UFEventEditor\UFEventEditor.csproj" />
    <ProjectReference Include="..\..\UFEventModel\UFEventModel.csproj" />
    <ProjectReference Include="..\..\UFInterfaces\UFInterfaces.csproj" />
    <ProjectReference Include="..\..\UFRecipeEditor\UFRecipeEditor.csproj" />
    <ProjectReference Include="..\..\UFRecipeExecuter\UFRecipeExecuter.csproj" />
    <ProjectReference Include="..\..\UFRecipeSettings\UFRecipeSettings.csproj" />
    <ProjectReference Include="..\..\UFUAEditor\UFUAEditor.csproj" />
    <ProjectReference Include="..\..\UFUAHistorianModel\UFUAHistorianModel.csproj" />
    <ProjectReference Include="..\..\UFUserEditor\UFUserEditor.csproj" />
    <ProjectReference Include="..\..\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\..\WebSessions\WebSessions.csproj" />
    <ProjectReference Include="..\..\WPFUtilities\WPFUtilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <TypeScriptCompile Include="wwwroot\lib\svg.filter.js\svg.filter.js.d.ts" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\AssemblyInfo.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="OPCUAClient.Config.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DismissedDevExtremeVersion="18.2.3" />
    </VisualStudio>
  </ProjectExtensions>
</Project>