//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSchedulerSettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSSchedulerSettings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Mask Editor.
        /// </summary>
        public static string AccessMaskEditor {
            get {
                return ResourceManager.GetString("AccessMaskEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Calendar Item.
        /// </summary>
        public static string AddCalendarItem {
            get {
                return ResourceManager.GetString("AddCalendarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Refresh Holidays.
        /// </summary>
        public static string AddDefaultHolidays {
            get {
                return ResourceManager.GetString("AddDefaultHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        public static string AddNewApp {
            get {
                return ResourceManager.GetString("AddNewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNewWeeklyItem {
            get {
                return ResourceManager.GetString("AddNewWeeklyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Schedule Time.
        /// </summary>
        public static string AddScheduleTime {
            get {
                return ResourceManager.GetString("AddScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the missing current year&apos;s holidays in the exceptions list?.
        /// </summary>
        public static string AskAddHolidays {
            get {
                return ResourceManager.GetString("AskAddHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all the calendar items?.
        /// </summary>
        public static string AskDeleteAllCalendarItems {
            get {
                return ResourceManager.GetString("AskDeleteAllCalendarItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete CalendarItem:
        ///{0}-{1}-{2}?.
        /// </summary>
        public static string AskDeleteCalendarItem {
            get {
                return ResourceManager.GetString("AskDeleteCalendarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected calendar items?.
        /// </summary>
        public static string AskDeleteCalendarItems {
            get {
                return ResourceManager.GetString("AskDeleteCalendarItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Month.
        /// </summary>
        public static string CalendarItemDayOfMonth {
            get {
                return ResourceManager.GetString("CalendarItemDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        public static string CalendarItemDayOfWeek {
            get {
                return ResourceManager.GetString("CalendarItemDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string CalendarItemEnd {
            get {
                return ResourceManager.GetString("CalendarItemEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string CalendarItemMonth {
            get {
                return ResourceManager.GetString("CalendarItemMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string CalendarItemStart {
            get {
                return ResourceManager.GetString("CalendarItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string CalendarItemType {
            get {
                return ResourceManager.GetString("CalendarItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of Month.
        /// </summary>
        public static string CalendarItemWeekOfMonth {
            get {
                return ResourceManager.GetString("CalendarItemWeekOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delect Calendar Item.
        /// </summary>
        public static string CaptionDeleteCalendarItem {
            get {
                return ResourceManager.GetString("CaptionDeleteCalendarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Enable variable.
        /// </summary>
        public static string CaptionDeleteEnableVar {
            get {
                return ResourceManager.GetString("CaptionDeleteEnableVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Scheduler variable.
        /// </summary>
        public static string CaptionDeleteItemVar {
            get {
                return ResourceManager.GetString("CaptionDeleteItemVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string CDayOfWeek_Friday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string CDayOfWeek_Monday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string CDayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string CDayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string CDayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string CDayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string CDayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("CDayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands Off.
        /// </summary>
        public static string CommandsOff {
            get {
                return ResourceManager.GetString("CommandsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands On.
        /// </summary>
        public static string CommandsOn {
            get {
                return ResourceManager.GetString("CommandsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date On.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Off.
        /// </summary>
        public static string DateOff {
            get {
                return ResourceManager.GetString("DateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Month.
        /// </summary>
        public static string DayMonth {
            get {
                return ResourceManager.GetString("DayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Of Month.
        /// </summary>
        public static string DayOfMonth {
            get {
                return ResourceManager.GetString("DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Calendar Item.
        /// </summary>
        public static string DeleteCalendarItem {
            get {
                return ResourceManager.GetString("DeleteCalendarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Items.
        /// </summary>
        public static string DeleteCalendarItems {
            get {
                return ResourceManager.GetString("DeleteCalendarItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteWeeklyPlanItem {
            get {
                return ResourceManager.GetString("DeleteWeeklyPlanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Calendar Item.
        /// </summary>
        public static string EditCalendarItem {
            get {
                return ResourceManager.GetString("EditCalendarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please, the scheduled item will end after the workview end time..
        /// </summary>
        public static string EditWarningAfterWorkView {
            get {
                return ResourceManager.GetString("EditWarningAfterWorkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please, the scheduled item will start before the workview start time..
        /// </summary>
        public static string EditWarningBeforeWorkView {
            get {
                return ResourceManager.GetString("EditWarningBeforeWorkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Calendar Editing.
        /// </summary>
        public static string EditWarningCaption {
            get {
                return ResourceManager.GetString("EditWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention please, the scheduled item will start and stop out of time workview..
        /// </summary>
        public static string EditWarningOutOfWorkView {
            get {
                return ResourceManager.GetString("EditWarningOutOfWorkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inserted event has been split into several events and normalized to actual workview..
        /// </summary>
        public static string EditWarningSplittedEvent {
            get {
                return ResourceManager.GetString("EditWarningSplittedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditWeeklyPlanItem {
            get {
                return ResourceManager.GetString("EditWeeklyPlanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string EnableEvent {
            get {
                return ResourceManager.GetString("EnableEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Do you really want to delete the Enable variable?.
        /// </summary>
        public static string EnableVarDeleteWarn {
            get {
                return ResourceManager.GetString("EnableVarDeleteWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured reading the file &apos;{0}. The file may be corrupted.
        /// </summary>
        public static string ErrorReadingDocument {
            get {
                return ResourceManager.GetString("ErrorReadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving the document ({0}) !.
        /// </summary>
        public static string ErrorSavingDocument {
            get {
                return ResourceManager.GetString("ErrorSavingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred validating the file &apos;{0}. The file may belong from another project.
        /// </summary>
        public static string ErrorValidatingDocument {
            get {
                return ResourceManager.GetString("ErrorValidatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryDay.
        /// </summary>
        public static string EveryDay {
            get {
                return ResourceManager.GetString("EveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryFriday.
        /// </summary>
        public static string EveryFriday {
            get {
                return ResourceManager.GetString("EveryFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryHour.
        /// </summary>
        public static string EveryHour {
            get {
                return ResourceManager.GetString("EveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryMinute.
        /// </summary>
        public static string EveryMinute {
            get {
                return ResourceManager.GetString("EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryMonday.
        /// </summary>
        public static string EveryMonday {
            get {
                return ResourceManager.GetString("EveryMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverySaturday.
        /// </summary>
        public static string EverySaturday {
            get {
                return ResourceManager.GetString("EverySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverySunday.
        /// </summary>
        public static string EverySunday {
            get {
                return ResourceManager.GetString("EverySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryThursday.
        /// </summary>
        public static string EveryThursday {
            get {
                return ResourceManager.GetString("EveryThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryTuesday.
        /// </summary>
        public static string EveryTuesday {
            get {
                return ResourceManager.GetString("EveryTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EveryWednesday.
        /// </summary>
        public static string EveryWednesday {
            get {
                return ResourceManager.GetString("EveryWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Commands Off.
        /// </summary>
        public static string ExceptionCommandsOff {
            get {
                return ResourceManager.GetString("ExceptionCommandsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Commands On.
        /// </summary>
        public static string ExceptionCommandsOn {
            get {
                return ResourceManager.GetString("ExceptionCommandsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute OFF at startup (weekly plan).
        /// </summary>
        public static string ExecOffAtStartup {
            get {
                return ResourceManager.GetString("ExecOffAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute ON at startup (weekly plan).
        /// </summary>
        public static string ExecOnAtStartup {
            get {
                return ResourceManager.GetString("ExecOnAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLog {
            get {
                return ResourceManager.GetString("GeneralLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to configure HTTP.sys settings :  {0}&apos;newline&apos;The server cannot be run properly if you don&apos;t remove the http transport.&apos;newline&apos;Do you want continue anyway ?.
        /// </summary>
        public static string HttpRegistrationFailed {
            get {
                return ResourceManager.GetString("HttpRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End Time have to be late than Start Time!.
        /// </summary>
        public static string InvalidEndTime {
            get {
                return ResourceManager.GetString("InvalidEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End Time have to be late than Start Time and between work view range!.
        /// </summary>
        public static string InvalidEndTimeInWorkView {
            get {
                return ResourceManager.GetString("InvalidEndTimeInWorkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Time have to be earlier than End Time!.
        /// </summary>
        public static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Time have to be earlier than End Time and between work view range!.
        /// </summary>
        public static string InvalidStartTimeInWorkView {
            get {
                return ResourceManager.GetString("InvalidStartTimeInWorkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Do you really want to delete the Scheduler variable?.
        /// </summary>
        public static string ItemVarDeleteWarn {
            get {
                return ResourceManager.GetString("ItemVarDeleteWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string MonthDayAny_First {
            get {
                return ResourceManager.GetString("MonthDayAny_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string MonthDayAny_Last {
            get {
                return ResourceManager.GetString("MonthDayAny_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoDate.
        /// </summary>
        public static string MonthDayAny_NoDate {
            get {
                return ResourceManager.GetString("MonthDayAny_NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        public static string NewEventAccessLevel {
            get {
                return ResourceManager.GetString("NewEventAccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Mask.
        /// </summary>
        public static string NewEventAccessMask {
            get {
                return ResourceManager.GetString("NewEventAccessMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Role.
        /// </summary>
        public static string NewEventAccessRole {
            get {
                return ResourceManager.GetString("NewEventAccessRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Off .
        /// </summary>
        public static string NewEventActionsOff {
            get {
                return ResourceManager.GetString("NewEventActionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions On .
        /// </summary>
        public static string NewEventActionsOn {
            get {
                return ResourceManager.GetString("NewEventActionsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string NewEventCalendar {
            get {
                return ResourceManager.GetString("NewEventCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Variable.
        /// </summary>
        public static string NewEventEnableTag {
            get {
                return ResourceManager.GetString("NewEventEnableTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string NewEventExceptions {
            get {
                return ResourceManager.GetString("NewEventExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string NewEventFriday {
            get {
                return ResourceManager.GetString("NewEventFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string NewEventMonday {
            get {
                return ResourceManager.GetString("NewEventMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewEventName {
            get {
                return ResourceManager.GetString("NewEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NewEventName1 {
            get {
                return ResourceManager.GetString("NewEventName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string NewEventSaturday {
            get {
                return ResourceManager.GetString("NewEventSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fri.
        /// </summary>
        public static string NewEventShortFriday {
            get {
                return ResourceManager.GetString("NewEventShortFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mon.
        /// </summary>
        public static string NewEventShortMonday {
            get {
                return ResourceManager.GetString("NewEventShortMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satur.
        /// </summary>
        public static string NewEventShortSaturday {
            get {
                return ResourceManager.GetString("NewEventShortSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sun.
        /// </summary>
        public static string NewEventShortSunday {
            get {
                return ResourceManager.GetString("NewEventShortSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thurs.
        /// </summary>
        public static string NewEventShortThursday {
            get {
                return ResourceManager.GetString("NewEventShortThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tues.
        /// </summary>
        public static string NewEventShortTuesday {
            get {
                return ResourceManager.GetString("NewEventShortTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wednes.
        /// </summary>
        public static string NewEventShortWednesday {
            get {
                return ResourceManager.GetString("NewEventShortWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string NewEventSunday {
            get {
                return ResourceManager.GetString("NewEventSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string NewEventTag {
            get {
                return ResourceManager.GetString("NewEventTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string NewEventThursday {
            get {
                return ResourceManager.GetString("NewEventThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Properties.
        /// </summary>
        public static string NewEventTitle {
            get {
                return ResourceManager.GetString("NewEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Properties.
        /// </summary>
        public static string NewEventTitle1 {
            get {
                return ResourceManager.GetString("NewEventTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string NewEventTuesday {
            get {
                return ResourceManager.GetString("NewEventTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NewEventType {
            get {
                return ResourceManager.GetString("NewEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for event Off.
        /// </summary>
        public static string NewEventValueOff {
            get {
                return ResourceManager.GetString("NewEventValueOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for event On.
        /// </summary>
        public static string NewEventValueOn {
            get {
                return ResourceManager.GetString("NewEventValueOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string NewEventWednesday {
            get {
                return ResourceManager.GetString("NewEventWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Plan.
        /// </summary>
        public static string NewEventWeeklyPlan {
            get {
                return ResourceManager.GetString("NewEventWeeklyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string RecurrenceFiledDays {
            get {
                return ResourceManager.GetString("RecurrenceFiledDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string RecurrenceFiledEvery {
            get {
                return ResourceManager.GetString("RecurrenceFiledEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every weekday.
        /// </summary>
        public static string RecurrenceFiledEveryWeekDays {
            get {
                return ResourceManager.GetString("RecurrenceFiledEveryWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to remove all listed items?.
        /// </summary>
        public static string RemoveAllListedWeeklyItems {
            get {
                return ResourceManager.GetString("RemoveAllListedWeeklyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string RemoveAllWeeklyItem {
            get {
                return ResourceManager.GetString("RemoveAllWeeklyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTS.
        /// </summary>
        public static string RuntimeExt {
            get {
                return ResourceManager.GetString("RuntimeExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save {0} ?.
        /// </summary>
        public static string SaveDoc {
            get {
                return ResourceManager.GetString("SaveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime editable.
        /// </summary>
        public static string SelectableRuntime {
            get {
                return ResourceManager.GetString("SelectableRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You manually started the server {0} before. Would you like to stop it now ?.
        /// </summary>
        public static string StopServerStartedManually {
            get {
                return ResourceManager.GetString("StopServerStartedManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time On.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Off.
        /// </summary>
        public static string TimeOff {
            get {
                return ResourceManager.GetString("TimeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly plan.
        /// </summary>
        public static string WeeklyConflict {
            get {
                return ResourceManager.GetString("WeeklyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day event.
        /// </summary>
        public static string WeeklyItemAllDayEvent {
            get {
                return ResourceManager.GetString("WeeklyItemAllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Recurrence.
        /// </summary>
        public static string WeeklyItemApplyRecurrence {
            get {
                return ResourceManager.GetString("WeeklyItemApplyRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WeeklyItemEditFormCancel {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week:.
        /// </summary>
        public static string WeeklyItemEditFormDayOfWeek {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WeeklyItemEditFormDelete {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string WeeklyItemEditFormDescription {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time:.
        /// </summary>
        public static string WeeklyItemEditFormEndTime {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label color:.
        /// </summary>
        public static string WeeklyItemEditFormLabelColor {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormLabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string WeeklyItemEditFormOk {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        public static string WeeklyItemEditFormStartTime {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        public static string WeeklyItemEditFormSubject {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject color:.
        /// </summary>
        public static string WeeklyItemEditFormSubjectColor {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormSubjectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schedule Interval.
        /// </summary>
        public static string WeeklyItemEditFormTitle {
            get {
                return ResourceManager.GetString("WeeklyItemEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every day.
        /// </summary>
        public static string WeeklyItemRepeatEveryDay {
            get {
                return ResourceManager.GetString("WeeklyItemRepeatEveryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeeklyPlan.
        /// </summary>
        public static string WeeklyPlan {
            get {
                return ResourceManager.GetString("WeeklyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of Month.
        /// </summary>
        public static string WeekOfMonth {
            get {
                return ResourceManager.GetString("WeekOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
