//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LacbusPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LacbusPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the frontend established.
        /// </summary>
        public static string ConnectionToFR1000Established {
            get {
                return ResourceManager.GetString("ConnectionToFR1000Established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the frontend broken.
        /// </summary>
        public static string ConnectionToFrontEndBroken {
            get {
                return ResourceManager.GetString("ConnectionToFrontEndBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: already authenticated SCADA.
        /// </summary>
        public static string ErrorAlreadyAuthenticatedSCADA {
            get {
                return ResourceManager.GetString("ErrorAlreadyAuthenticatedSCADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: authentication needed.
        /// </summary>
        public static string ErrorAuthenticationNeeded {
            get {
                return ResourceManager.GetString("ErrorAuthenticationNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: bad RTU number.
        /// </summary>
        public static string ErrorBadRtuNumber {
            get {
                return ResourceManager.GetString("ErrorBadRtuNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag list cannot contain variables of type bit and variables of different types (Tags: {0}).
        /// </summary>
        public static string ErrorBitAndOtherTagTypes {
            get {
                return ResourceManager.GetString("ErrorBitAndOtherTagTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTU Poll Request Failed for RTU {0}.
        /// </summary>
        public static string ErrorCodeRTUPollRequestFailed {
            get {
                return ResourceManager.GetString("ErrorCodeRTUPollRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another station of the channel has been already defined with the &quot;Communication Protocol&quot; set to &quot;LacbusPC&quot;. Please, select a different &quot;Communication Protocol&quot;..
        /// </summary>
        public static string ErrorCommunicationProtocolAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorCommunicationProtocolAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another station of the channel has been already defined with the same &quot;Communication Protocol&quot;, &quot;RTU number&quot; and  &quot;Phone Number&quot;. Please change at least one of these parameters..
        /// </summary>
        public static string ErrorCommunicationProtocolAlreadyExistPhoneAndRTU {
            get {
                return ResourceManager.GetString("ErrorCommunicationProtocolAlreadyExistPhoneAndRTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another station of the channel has been already defined with the same &quot;Communication Protocol&quot; and &quot;RTU number&quot;. Please change at least one of these parameters..
        /// </summary>
        public static string ErrorCommunicationProtocolAlreadyExistRtu {
            get {
                return ResourceManager.GetString("ErrorCommunicationProtocolAlreadyExistRtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection broken.
        /// </summary>
        public static string ErrorConnectionBroken {
            get {
                return ResourceManager.GetString("ErrorConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} connection to the FR1000 fail, error details: {1}.
        /// </summary>
        public static string ErrorConnections {
            get {
                return ResourceManager.GetString("ErrorConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: disabled SCADA number.
        /// </summary>
        public static string ErrorDisabledScadaNumber {
            get {
                return ResourceManager.GetString("ErrorDisabledScadaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: forbidden command.
        /// </summary>
        public static string ErrorForbiddenCommand {
            get {
                return ResourceManager.GetString("ErrorForbiddenCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Failure with frontend.
        /// </summary>
        public static string ErrorGenericCommunicationFailure {
            get {
                return ResourceManager.GetString("ErrorGenericCommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received incomplete LACBUS-PC message.
        /// </summary>
        public static string ErrorIncompleteMessage {
            get {
                return ResourceManager.GetString("ErrorIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message with incorrect LACBUS-PC header.
        /// </summary>
        public static string ErrorIncorrectLacbusPcHeader {
            get {
                return ResourceManager.GetString("ErrorIncorrectLacbusPcHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message with incorrect LACBUS-PC header length.
        /// </summary>
        public static string ErrorIncorrectLacbusPcHeaderLength {
            get {
                return ResourceManager.GetString("ErrorIncorrectLacbusPcHeaderLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received  LACBUS-PC message with incorrect message type.
        /// </summary>
        public static string ErrorIncorrectMessageType {
            get {
                return ResourceManager.GetString("ErrorIncorrectMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received  LACBUS-PC message with incorrect protocol version.
        /// </summary>
        public static string ErrorIncorrectProtocolVersion {
            get {
                return ResourceManager.GetString("ErrorIncorrectProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received  LACBUS-PC message with incorrect or unsupported underlying protocol.
        /// </summary>
        public static string ErrorIncorrectUnderlyingProtocol {
            get {
                return ResourceManager.GetString("ErrorIncorrectUnderlyingProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the Vortex Library Failed.
        /// </summary>
        public static string ErrorInitializationVortexLibrary {
            get {
                return ResourceManager.GetString("ErrorInitializationVortexLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Datum Type requires a task of type &apos;{0}&apos;.
        /// </summary>
        public static string ErrorInputTaskRequired {
            get {
                return ResourceManager.GetString("ErrorInputTaskRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel settings.
        /// </summary>
        public static string ErrorInvalidChannelSettings {
            get {
                return ResourceManager.GetString("ErrorInvalidChannelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The conversion parameters ara invalid.
        /// </summary>
        public static string ErrorInvalidConversionData {
            get {
                return ResourceManager.GetString("ErrorInvalidConversionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid driver settings.
        /// </summary>
        public static string ErrorInvalidDriverSettings {
            get {
                return ResourceManager.GetString("ErrorInvalidDriverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PC Number, please, insert a value between 1 and 4.
        /// </summary>
        public static string ErrorInvalidPCNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid station settings.
        /// </summary>
        public static string ErrorInvalidStationSettings {
            get {
                return ResourceManager.GetString("ErrorInvalidStationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tag object.
        /// </summary>
        public static string ErrorInvalidTagObject {
            get {
                return ResourceManager.GetString("ErrorInvalidTagObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tag type is invalid for its Data Type (Tag: {0} Data Type: {1}).
        /// </summary>
        public static string ErrorInvalidTagType {
            get {
                return ResourceManager.GetString("ErrorInvalidTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job exceed the maximum size (Tags: {0}).
        /// </summary>
        public static string ErrorJobTooBig {
            get {
                return ResourceManager.GetString("ErrorJobTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the driver settings, error &apos;{0}&apos;.
        /// </summary>
        public static string ErrorLoadingDriverSettings {
            get {
                return ResourceManager.GetString("ErrorLoadingDriverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure trying to open a communication channel for sending a request.
        /// </summary>
        public static string ErrorOpeningRequestChannel {
            get {
                return ResourceManager.GetString("ErrorOpeningRequestChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure (authentication failure) trying to open a communication channel for sending a request.
        /// </summary>
        public static string ErrorOpenRequestChannelAuthenticationFailure {
            get {
                return ResourceManager.GetString("ErrorOpenRequestChannelAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure (incorrect syntax) trying to open a communication channel for sending a request.
        /// </summary>
        public static string ErrorOpenRequestChannelIncorrectSyntax {
            get {
                return ResourceManager.GetString("ErrorOpenRequestChannelIncorrectSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Datum Type requires a task of type &apos;{0}&apos; or &apos;{1}&apos;.
        /// </summary>
        public static string ErrorOutputTaskRequired {
            get {
                return ResourceManager.GetString("ErrorOutputTaskRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error preparing the request frame.
        /// </summary>
        public static string ErrorPreparingFrameRequest {
            get {
                return ResourceManager.GetString("ErrorPreparingFrameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering profile {0}.
        /// </summary>
        public static string ErrorRegisterProfile {
            get {
                return ResourceManager.GetString("ErrorRegisterProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTU {0} disconnected.
        /// </summary>
        public static string ErrorRTUDisconnected {
            get {
                return ResourceManager.GetString("ErrorRTUDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending the request.
        /// </summary>
        public static string ErrorSendingFrameRequest {
            get {
                return ResourceManager.GetString("ErrorSendingFrameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: syntax error.
        /// </summary>
        public static string ErrorSyntaxError {
            get {
                return ResourceManager.GetString("ErrorSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: unable to process the command.
        /// </summary>
        public static string ErrorUnableToProcessTheCommand {
            get {
                return ResourceManager.GetString("ErrorUnableToProcessTheCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with unexpected error code.
        /// </summary>
        public static string ErrorUnexpectedErrorCode {
            get {
                return ResourceManager.GetString("ErrorUnexpectedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening a channel: the profile {0} is not supported.
        /// </summary>
        public static string ErrorUnsupportedProfile {
            get {
                return ResourceManager.GetString("ErrorUnsupportedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received reply with error code: unsupported protocol version.
        /// </summary>
        public static string ErrorUnsupportedProtocolVersion {
            get {
                return ResourceManager.GetString("ErrorUnsupportedProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received badly formatted message from RTU {0}.
        /// </summary>
        public static string WarningBadlyFormattedMessage {
            get {
                return ResourceManager.GetString("WarningBadlyFormattedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received unsupported or badly formatted message from RTU {0}.
        /// </summary>
        public static string WarningBadMessageType {
            get {
                return ResourceManager.GetString("WarningBadMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received message from a non managed RTU ({0}).
        /// </summary>
        public static string WarningReceivedMessageFromNonManagedStation {
            get {
                return ResourceManager.GetString("WarningReceivedMessageFromNonManagedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received message for RTU {0} with unexpected underlying protocol ({1} instead of {2}).
        /// </summary>
        public static string WarningReceivedMessageWithUnexpectedUnderlyingProtocol {
            get {
                return ResourceManager.GetString("WarningReceivedMessageWithUnexpectedUnderlyingProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received SMS message from RTU {0} with unknown data format.
        /// </summary>
        public static string WarningUnknownSMSDataFormat {
            get {
                return ResourceManager.GetString("WarningUnknownSMSDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received SMS message from RTU {0} with unknown protocol version {1}.
        /// </summary>
        public static string WarningUnknownSMSProtocolVersion {
            get {
                return ResourceManager.GetString("WarningUnknownSMSProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received SMS message from RTU {0} with protocol version {1} and unknown type {2}.
        /// </summary>
        public static string WarningUnknownSMSType {
            get {
                return ResourceManager.GetString("WarningUnknownSMSType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received SMS message from RTU {0} with unknown archive type.
        /// </summary>
        public static string WarningUnsupportedArchiveType {
            get {
                return ResourceManager.GetString("WarningUnsupportedArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: received SMS message from RTU {0} with unsupported data format for protocol version {1}.
        /// </summary>
        public static string WarningUnsupportedSMSDataFormat {
            get {
                return ResourceManager.GetString("WarningUnsupportedSMSDataFormat", resourceCulture);
            }
        }
    }
}
