//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeUAServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeUAServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated the recipe index &apos;{0}&apos; of the recipe table &apos;{1}&apos;.
        /// </summary>
        public static string AuditTraceMessageActivated {
            get {
                return ResourceManager.GetString("AuditTraceMessageActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added the recipe index &apos;{0}&apos; in the recipe table &apos;{1}&apos;.
        /// </summary>
        public static string AuditTraceMessageAdded {
            get {
                return ResourceManager.GetString("AuditTraceMessageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed the recipe index &apos;{0}&apos; from the recipe table &apos;{1}&apos;.
        /// </summary>
        public static string AuditTraceMessageDeleted {
            get {
                return ResourceManager.GetString("AuditTraceMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed the recipe index &apos;{0}&apos; in the recipe table &apos;{1}&apos;.
        /// </summary>
        public static string AuditTraceMessageModified {
            get {
                return ResourceManager.GetString("AuditTraceMessageModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user cannot call the method &apos;{0}&apos;!.
        /// </summary>
        public static string BadUserAccessDenied {
            get {
                return ResourceManager.GetString("BadUserAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A socket error occured starting the server application, try to change the socket port number in the server settings.&apos;newline&apos;&apos;newline&apos;&apos;{0}&apos;..
        /// </summary>
        public static string CommunciationErrorOnStartingService {
            get {
                return ResourceManager.GetString("CommunciationErrorOnStartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Space Created : Elapsed {0}.
        /// </summary>
        public static string CreatedAddressSpace {
            get {
                return ResourceManager.GetString("CreatedAddressSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Address Space.
        /// </summary>
        public static string CreatingAddressSpace {
            get {
                return ResourceManager.GetString("CreatingAddressSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe &apos;{0}&apos; was not set to handle the read operations, this command will be disable.
        /// </summary>
        public static string DisableReadCommandMessage {
            get {
                return ResourceManager.GetString("DisableReadCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe &apos;{0}&apos; was not set to handle the write operations, this command will be disable.
        /// </summary>
        public static string DisableWriteCommandMessage {
            get {
                return ResourceManager.GetString("DisableWriteCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated NodeId &apos;{0}&apos; for Recipe name &apos;{1}&apos;..
        /// </summary>
        public static string DuplicatedRecipeNodeId {
            get {
                return ResourceManager.GetString("DuplicatedRecipeNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on the inactive server while synchronizing recipes data with the active server &apos;{0}&apos; (&apos;{1}&apos;).
        /// </summary>
        public static string ErrorSynchronizingRecipesDataServer {
            get {
                return ResourceManager.GetString("ErrorSynchronizingRecipesDataServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An arror occurred in the Recipe Server : {0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the plugin &apos;{0}&apos;, error &apos;{1}&apos;.
        /// </summary>
        public static string FailedToInitializePlugin {
            get {
                return ResourceManager.GetString("FailedToInitializePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes Initialized : Elapsed {0}.
        /// </summary>
        public static string InitializedRecipes {
            get {
                return ResourceManager.GetString("InitializedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Recipes.
        /// </summary>
        public static string InitializingRecipes {
            get {
                return ResourceManager.GetString("InitializingRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data value &apos;{0}&apos; belongs to recipe &apos;{1}&apos; will be not read due to a mistake in the communication configuration with the device.
        /// </summary>
        public static string InvalidDataValueDeviceAddressForRead {
            get {
                return ResourceManager.GetString("InvalidDataValueDeviceAddressForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data value &apos;{0}&apos; belongs to recipe &apos;{1}&apos; will be not write due to a mistake in the communication configuration with the device.
        /// </summary>
        public static string InvalidDataValueDeviceAddressForWrite {
            get {
                return ResourceManager.GetString("InvalidDataValueDeviceAddressForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group &apos;{0}&apos; belongs to recipe &apos;{1}&apos; will be not read due to a mistake in the communication configuration with the device.
        /// </summary>
        public static string InvalidGroupDeviceAddressForRead {
            get {
                return ResourceManager.GetString("InvalidGroupDeviceAddressForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group &apos;{0}&apos; belongs to recipe &apos;{1}&apos; will be not write due to a mistake in the communication configuration with the device.
        /// </summary>
        public static string InvalidGroupDeviceAddressForWrite {
            get {
                return ResourceManager.GetString("InvalidGroupDeviceAddressForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the device address configuration for recipe &apos;{0}&apos;, errors in read procedure may occur.
        /// </summary>
        public static string InvalidRecipeDeviceAddressForRead {
            get {
                return ResourceManager.GetString("InvalidRecipeDeviceAddressForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the device address configuration for recipe &apos;{0}&apos;, errors in write procedure may occur.
        /// </summary>
        public static string InvalidRecipeDeviceAddressForWrite {
            get {
                return ResourceManager.GetString("InvalidRecipeDeviceAddressForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server properties loaded.
        /// </summary>
        public static string LoadedServerProperties {
            get {
                return ResourceManager.GetString("LoadedServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Recipe Server properties.
        /// </summary>
        public static string LoadingServerProperties {
            get {
                return ResourceManager.GetString("LoadingServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing project to load or project cannot be loaded !.
        /// </summary>
        public static string MissingProjectFile {
            get {
                return ResourceManager.GetString("MissingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server license execution not found !.
        /// </summary>
        public static string NoSvrLicence {
            get {
                return ResourceManager.GetString("NoSvrLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new server application cannot be started, because this project already running with another server instance or the socket port number is already used by another process  !.
        /// </summary>
        public static string ProjectAlreadyRunning {
            get {
                return ResourceManager.GetString("ProjectAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server Started.
        /// </summary>
        public static string RecipeServerStarted {
            get {
                return ResourceManager.GetString("RecipeServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server Stopped.
        /// </summary>
        public static string RecipeServerStopped {
            get {
                return ResourceManager.GetString("RecipeServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test of the server sockets failed. Retry {0} of {1}, next attempt in {2} ms..
        /// </summary>
        public static string RetryOpenSocketWarningMessage {
            get {
                return ResourceManager.GetString("RetryOpenSocketWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server is Starting, Running a {0} bit process.
        /// </summary>
        public static string ServerStarting {
            get {
                return ResourceManager.GetString("ServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server has been stopped.
        /// </summary>
        public static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Server is Stopping.
        /// </summary>
        public static string ServerStopping {
            get {
                return ResourceManager.GetString("ServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes Started.
        /// </summary>
        public static string StartedRecipes {
            get {
                return ResourceManager.GetString("StartedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Recipes.
        /// </summary>
        public static string StartingRecipes {
            get {
                return ResourceManager.GetString("StartingRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use the discovery behavior in the service host !.
        /// </summary>
        public static string UnableToUseDiscoveryBehaviour {
            get {
                return ResourceManager.GetString("UnableToUseDiscoveryBehaviour", resourceCulture);
            }
        }
    }
}
