//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditDisplay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditDisplay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type.
        /// </summary>
        public static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Display.
        /// </summary>
        public static string EditDisplayLog {
            get {
                return ResourceManager.GetString("EditDisplayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Of Range.
        /// </summary>
        public static string ForegroundError {
            get {
                return ResourceManager.GetString("ForegroundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading stats: {0}.
        /// </summary>
        public static string MissingStatsWarning {
            get {
                return ResourceManager.GetString("MissingStatsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Value.
        /// </summary>
        public static string NullValueWarning {
            get {
                return ResourceManager.GetString("NullValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime error: {0}.
        /// </summary>
        public static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditDisplay.
        /// </summary>
        public static string SessionName {
            get {
                return ResourceManager.GetString("SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin Enabled.
        /// </summary>
        public static string SpinEnabled {
            get {
                return ResourceManager.GetString("SpinEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin Step.
        /// </summary>
        public static string SpinStep {
            get {
                return ResourceManager.GetString("SpinStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlBackground.
        /// </summary>
        public static string TagBackground {
            get {
                return ResourceManager.GetString("TagBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpinBackground.
        /// </summary>
        public static string TagSpinBackground {
            get {
                return ResourceManager.GetString("TagSpinBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimespanFormat was specified in an invalid format.
        /// </summary>
        public static string TimespanFormatInlineError {
            get {
                return ResourceManager.GetString("TimespanFormatInlineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Tag&apos;s Range.
        /// </summary>
        public static string UseEUnit {
            get {
                return ResourceManager.GetString("UseEUnit", resourceCulture);
            }
        }
    }
}
