#region Copyright Syncfusion Inc. 2001 - 2014
// Copyright Syncfusion Inc. 2001 - 2014. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Syncfusion.RDL.DOM
{
    static class ReportConstants
    {
        public const string Report = "Report";
        public const string DataSources = "DataSources";
        public const string DataSource = "DataSource";
        public const string DataSourceID = "DataSourceID";
        public const string Name = "Name";
        public const string DataSourceReference = "DataSourceReference";
        public const string ConnectionProperties = "ConnectionProperties";
        public const string DataProvider = "DataProvider";
        public const string ConnectString = "ConnectString";
        public const string IntegratedSecurity = "IntegratedSecurity";
        public const string Prompt = "Prompt";
        public const string DataSets = "DataSets";
        public const string DataSet = "DataSet";
        public const string Fields = "Fields";
        public const string Field = "Field";
        public const string DataField = "DataField";
        public const string Value = "Value";
        public const string Query = "Query";
        public const string DataSourceName = "DataSourceName";
        public const string CommandType = "CommandType";
        public const string CommandText = "CommandText";
        public const string QueryParameters = "QueryParameters";
        public const string Timeout = "Timeout";
        public const string QueryParameter = "QueryParameter";
        public const string Filters = "Filters";
        public const string Filter = "Filter";
        public const string FilterExpression = "FilterExpression";
        public const string Operator = "Operator";
        public const string FilterValues = "FilterValues";
        public const string FilterValue = "FilterValue";
        public const string DataType = "DataType";
        public const string InterpretSubtotalsAsDetails = "InterpretSubtotalsAsDetails";
        public const string ReportParameters = "ReportParameters";
        public const string ReportParameter = "ReportParameter";
        public const string Values = "Values";
        public const string ValidValues = "ValidValues";
        public const string DefaultValue = "DefaultValue";
        public const string Label = "Label";
        public const string AllowBlank = "AllowBlank";
        public const string Nullable = "Nullable";
        public static string Hidden = "Hidden";
        public const string MultiValue = "MultiValue";
        public const string UsedInQuery = "UsedInQuery";
        public const string DataSetReference = "DataSetReference";
        public const string DataSetName = "DataSetName";
        public const string ValueField = "ValueField";
        public const string LabelField = "LabelField";
        public const string ParameterValues = "ParameterValues";
        public const string ParameterValue = "ParameterValue";
        public const string AutoRefresh = "AutoRefresh";
        public const string Description = "Description";
        public const string Author = "Author";
        public const string Code = "Code";
        public const string Width = "Width";
        public const string DeferVariableEvaluation = "DeferVariableEvaluation";
        public const string ConsumeContainerWhitespace = "ConsumeContainerWhitespace";
        public const string DataTransform = "DataTransform";
        public const string DataSchema = "DataSchema";
        public const string DataElementName = "DataElementName";
        public const string DataElementStyle = "DataElementStyle";
        public const string Language = "Language";
        public const string EmbeddedImages = "EmbeddedImages";
        public const string EmbeddedImage = "EmbeddedImage";
        public const string MIMEType = "MIMEType";
        public const string ImageData = "ImageData";
        public const string Variables = "Variables";
        public const string Variable = "Variable";
        public const string CodeModules = "CodeModules";
        public const string CodeModule = "CodeModule";
        public const string Classes = "Classes";
        public const string Class = "Class";
        public const string ClassName = "ClassName";
        public const string InstanceName = "InstanceName";
        public const string Page = "Page";
        public const string PageHeader = "PageHeader";
        public const string PageFooter = "PageFooter";
        public const string PageHeight = "PageHeight";
        public const string PageWidth = "PageWidth";
        public const string InteractiveHeight = "InteractiveHeight";
        public const string InteractiveWidth = "InteractiveWidth";
        public const string LeftMargin = "LeftMargin";
        public const string RightMargin = "RightMargin";
        public const string TopMargin = "TopMargin";
        public const string BottomMargin = "BottomMargin";
        public const string Columns = "Columns";
        public const string ColumnSpacing = "ColumnSpacing";
        public const string Style = "Style";
        public const string PrintOnFirstPage = "PrintOnFirstPage";
        public const string PrintOnLastPage = "PrintOnLastPage";
        public const string Height = "Height";
        public const string Body = "Body";
        public const string Top = "Top";
        public const string Left = "Left";
        public const string ZIndex = "ZIndex";
        public const string ActionInfo = "ActionInfo";
        public const string Visibility = "Visibility";
        public const string ToolTip = "ToolTip";
        public const string DocumentMapLabel = "DocumentMapLabel";
        public const string Bookmark = "Bookmark";
        public const string RepeatWith = "RepeatWith";
        public const string DataElementOutput = "DataElementOutput";
        public const string ReportItems = "ReportItems";
        public const string ReportItem = "ReportItem";
        public const string Chart = "Chart";
        public const string Textbox = "Textbox";
        public const string Image = "Image";
        public const string Table = "Table";
        public const string Actions = "Actions";
        public const string Action = "Action";
        public const string Hyperlink = "Hyperlink";
        public const string Drillthrough = "Drillthrough";
        public const string BookmarkLink = "BookmarkLink";
        public const string ReportName = "ReportName";
        public const string Parameters = "Parameters";
        public const string Border = "Border";
        public const string TopBorder = "TopBorder";
        public const string BottomBorder = "BottomBorder";
        public const string LeftBorder = "LeftBorder";
        public const string RightBorder = "RightBorder";
        public const string BackgroundColor = "BackgroundColor";
        public const string BackgroundGradientType = "BackgroundGradientType";
        public const string BackgroundGradientEndColor = "BackgroundGradientEndColor";
        public const string BackgroundImage = "BackgroundImage";
        public const string FontStyle = "FontStyle";
        public const string FontFamily = "FontFamily";
        public const string FontSize = "FontSize";
        public const string FontWeight = "FontWeight";
        public const string Format = "Format";
        public const string TextDecoration = "TextDecoration";
        public const string TextAlign = "TextAlign";
        public const string VerticalAlign = "VerticalAlign";
        public const string PaddingLeft = "PaddingLeft";
        public const string PaddingRight = "PaddingRight";
        public const string PaddingTop = "PaddingTop";
        public const string PaddingBottom = "PaddingBottom";
        public const string LineHeight = "LineHeight";
        public const string Direction = "Direction";
        public const string WritingMode = "WritingMode";
        public const string Calendar = "Calendar";
        public const string NumeralLanguage = "NumeralLanguage";
        public const string NumeralVariant = "NumeralVariant";
        public const string TextEffect = "TextEffect";
        public const string BackgroundHatchType = "BackgroundHatchType";
        public const string ShadowColor = "ShadowColor";
        public const string ShadowOffset = "ShadowOffset";
        public const string ToggleItem = "ToggleItem";
        public const string Color = "Color";
        public const string Source = "Source";
        public const string BackgroundRepeat = "BackgroundRepeat";
        public const string TransparentColor = "TransparentColor";
        public const string Position = "Position";
        public const string Line = "Line";
        public const string Rectangle = "Rectangle";
        public const string PageBreak = "PageBreak";
        public const string KeepTogether = "KeepTogether";
        public const string OmitBorderOnPageBreak = "OmitBorderOnPageBreak";
        public const string LinkToChild = "LinkToChild";
        public const string BreakLocation = "BreakLocation";
        public const string Tablix = "Tablix";
        public const string TablixBody = "TablixBody";
        public const string TablixColumnHierarchy = "TablixColumnHierarchy";
        public const string TablixRowHierarchy = "TablixRowHierarchy";
        public const string NoRowsMessage = "NoRowsMessage";
        public const string TablixDataSetName = "DataSetName";
        public const string NoRowMessage = "NoRowMessage";
        public const string TablixColumns = "TablixColumns";
        public const string TablixRows = "TablixRows";
        public const string TablixColumn = "TablixColumn";
        public const string TablixRow = "TablixRow";
        public const string TablixCells = "TablixCells";
    }
}
