<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.14" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Core" Version="1.4.371.50" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HubData\RealTimeData.csproj" />
    <ProjectReference Include="..\Interfaces\Interfaces.csproj" />
  </ItemGroup>

</Project>
