<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
    <RootNamespace>ReportManager.ReportService</RootNamespace>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.6" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.6" />
    <PackageReference Include="DevExpress.Reporting.Core" Version="21.2.6" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Pdf.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Utils.v21.2.UI, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.CodeView.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.ExpressionEditor.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpf.ReportDesigner.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.DataAccess.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v21.2.Extensions, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.XtraPrinting.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Charts.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.XtraCharts.v21.2.Wizard, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.XtraCharts.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.PivotGrid.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Sparkline.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.CodeParser.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Core, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Export, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="CustomUntypedDataSetSerializer.cs" />
    <Compile Include="DefaultSourceType.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="ReportEmptyLayout.cs" />
    <Compile Include="ReportEmptyLayout.Designer.cs">
      <DependentUpon>ReportEmptyLayout.cs</DependentUpon>
    </Compile>
    <Compile Include="ReportServiceHelper.cs" />
    <Compile Include="SqlDataSourceFactory.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="ReportEmptyLayout.resx">
      <DependentUpon>ReportEmptyLayout.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\ConnectionDialog\ConnectionUIDialog\Microsoft.Data.ConnectionUI.Dialog.csproj" />
    <ProjectReference Include="..\..\..\Sources\ConnectionDialog\ConnectionUI\Microsoft.Data.ConnectionUI.csproj" />
    <ProjectReference Include="..\..\..\Sources\ConnectionDialog\SqlCeDataProvider\Microsoft.Data.ConnectionUI.SqlCeDataProvider.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\DataReader\DataReader.csproj" />
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj" />
    <ProjectReference Include="..\ReportParameters\ReportParameters.csproj" />
    <ProjectReference Include="..\ReportSettings\ReportSettings.csproj" />
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj" />
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj" />
  </ItemGroup>
 
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>