<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a">
      <Private>False</Private>
      <SpecificVersion>true</SpecificVersion>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <ProjectReference Include="..\DriverSettingsClassLibrary\DriverSettingsInterfaces.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerScriptManager\ServerScriptManager.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\ExpressionManager\ExpressionManager.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StatDef\StatDef.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.6" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.6" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.7.0" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\ServerInfo\UFUAServerInfo.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Private>true</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="AlarmRuntimeSetting.cs" />
    <Compile Include="ArrayConverter.cs" />
    <Compile Include="BaseTypes\AddressBase.cs" />
    <Compile Include="AlarmType.cs" />
    <Compile Include="ConditionType.cs" />
    <Compile Include="BaseTypes\ConfigurationBase.cs" />
    <Compile Include="Converters\LocalizedEnumConverter.cs" />
    <Compile Include="DriverDynamicSettings.cs" />
    <Compile Include="Extensions\DataTypeExtensions.cs" />
    <Compile Include="Helpers\AssociationHelper.cs" />
    <Compile Include="Helpers\CommunicationDriverInfo.cs" Condition=" '$(TargetFramework)' == 'net48' " />
    <Compile Include="Helpers\DynamicTagsCounter.cs" />
    <Compile Include="Helpers\EngineeringUnitData.cs" />
    <Compile Include="Helpers\KeepReadOnlyProperties.cs" />
    <Compile Include="Helpers\NameValidator.cs" />
    <Compile Include="Helpers\CustomXPCollection.cs" />
    <Compile Include="Helpers\TagComponentsHelper.cs" />
    <Compile Include="ImportServerPrototype.cs" />
    <Compile Include="ImportServerTag.cs" />
    <Compile Include="PhysicalAddresses.cs" />
    <Compile Include="TagEntityReference.cs" />
    <Compile Include="ThreeStateType.cs" />
    <Compile Include="UFUAAlarmThreshold.cs" />
    <Compile Include="DataType.cs" />
    <Compile Include="DeviationType.cs" />
    <Compile Include="ImportObject.cs" />
    <Compile Include="ImportPrototype.cs" />
    <Compile Include="ImportTag.cs" />
    <Compile Include="ModelType.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="TransportDefaultPorts.cs" />
    <Compile Include="UFUAAlarmDefinition.cs" />
    <Compile Include="UFUAAlarmSource.cs" />
    <Compile Include="UFUAArea.cs" />
    <Compile Include="UFUABaseAddress.cs" />
    <Compile Include="UFUACommunicationDriver.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="UFUAConfiguration.cs" />
    <Compile Include="UFUAEngineeringUnit.cs" />
    <Compile Include="UFUAEnumString.cs" />
    <Compile Include="UFUAFolder.cs" />
    <Compile Include="UFUAHistorianSettings.cs" />
    <Compile Include="UFUATag.cs" />
    <Compile Include="XPTagEntityReference.cs" />
    <Compile Include="UFUATagPrototype.cs" />
    <Compile Include="UFUAView.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>