<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\UFSolution\bin\Debug\DocumentManagers\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
	<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\UFSolution\bin\Release\DocumentManagers\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
	<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
   <!-- Multi-Targeting framework definitions -->
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>

  <!-- .NET Standard 2.0 references, compilation flags and build options -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NET_STANDARD</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="DevExpress.Data" Version="21.2.13" />
    <PackageReference Include="DevExpress.Xpo" Version="21.2.13" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.14" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="DevExpress.Data.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Mvvm.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Pdf.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.RichEdit.v21.2.Export, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.CodeView.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="DevExpress.Xpo.v21.2, Version=21.2.13.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">
      <Private>False</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationFramework.Aero" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="UIAutomationProvider" />
    <Reference Include="UIAutomationTypes" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="AttachmentsVisibilityConverter.cs" />
    <Compile Include="BoolToVisibilityConverter.cs" />
    <Compile Include="Converters\RecipientNamesConverter.cs" />
    <Compile Include="Converters\ValueToLocalizedTextConverter.cs" />
    <Compile Include="Helpers\NotificationTreeItemControl.cs" />
    <Compile Include="MenuControls\BarCommonItems.xaml.cs">
      <DependentUpon>BarCommonItems.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\MenuControl.xaml.cs">
      <DependentUpon>MenuControl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
    <Compile Include="..\SharedAssemblyInfo.cs">
      <Link>Properties\SharedAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\WPFUtilities\CryptString\CryptString.cs">
      <Link>CryptString\CryptString.cs</Link>
    </Compile>
    <Compile Include="ComponentService\ADEditorManagerComponent.cs">
      <SubType>Component</SubType>
    </Compile>
	<Compile Include="Document\ADEditorDocument.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="Controls\AvailablePlugins.xaml.cs">
      <DependentUpon>AvailablePlugins.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\GeneralSettings.xaml.cs">
      <DependentUpon>GeneralSettings.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\NewFolder.xaml.cs">
      <DependentUpon>NewFolder.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\NewNotification.xaml.cs">
      <DependentUpon>NewNotification.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\NewTag.xaml.cs">
      <DependentUpon>NewTag.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\NotificationList.xaml.cs">
      <DependentUpon>NotificationList.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\PluginList.xaml.cs">
      <DependentUpon>PluginList.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\SelectUser.xaml.cs">
      <DependentUpon>SelectUser.xaml</DependentUpon>
    </Compile>
    <Compile Include="Controls\StartupControl.xaml.cs">
      <DependentUpon>StartupControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="DivideDoubleByTwoConverter.cs" />
    <Compile Include="ADEditorControl.xaml.cs">
      <DependentUpon>ADEditorControl.xaml</DependentUpon>
    </Compile>
    <Compile Include="MenuControls\ToolbarControl.xaml.cs">
      <DependentUpon>ToolbarControl.xaml</DependentUpon>
    </Compile>
	</ItemGroup>
	<ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\PluginDescriptionResources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PluginDescriptionResources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Properties\Settings.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
	</ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Compile Include="PropertyDataTemplate\AttachmentsPropertyEditor.xaml.cs">
      <DependentUpon>AttachmentsPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\TextBoxNotificationItemPropertyEditor.xaml.cs">
      <DependentUpon>TextBoxNotificationItemPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\NotificationItemPropertyEditor.xaml.cs">
      <DependentUpon>NotificationItemPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\ItemReferenceModel.cs" />
    <Compile Include="PropertyDataTemplate\PluginNamePropertyEditor.xaml.cs">
      <DependentUpon>PluginNamePropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="PropertyDataTemplate\RecipientPropertyEditor.xaml.cs">
      <DependentUpon>RecipientPropertyEditor.xaml</DependentUpon>
    </Compile>
    <Compile Include="Service\ServiceControl.cs" />
    <Compile Include="TreeDocumentManagers\EventListDocumentManager.cs" />
    <Compile Include="TreeDocumentManagers\PluginListDocumentManager.cs" />
    <Compile Include="TreeDocumentManagers\TreeDocumentManager.cs" />
    <Compile Include="Properties\UICommandResource.Designer.cs">
      <DependentUpon>UICommandResource.resx</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Include="UIGeneralCommands.cs" />
    <ProjectReference Include="..\..\..\Sources\MindScape\WPFElements\Src\WpfControls\WpfControls.csproj">
      <Project>{3408467d-89da-407f-9a97-d2f68724c19c}</Project>
      <Name>WpfControls</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NET\Stack\Core\UA Core Library.csproj">
      <Project>{7543AFCB-F5AF-44AF-83C9-23164474C1E9}</Project>
      <Name>UA Core Library</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Sources\WPF Ookii Dialogs\src\Ookii.Dialogs.Wpf\Ookii.Dialogs.Wpf.csproj">
      <Project>{d01b1d20-8f5b-4834-8e5c-c7ec6dd587d4}</Project>
      <Name>Ookii.Dialogs.Wpf</Name>
      <Private>False</Private>
    </ProjectReference>
</ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\ADModel\ADModel.csproj">
      <Project>{F89313C7-19DF-40E2-A368-83E81C0A211A}</Project>
      <Name>ADModel</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADPluginInterfaces\ADPluginInterfaces.csproj">
      <Project>{00b59eaf-08a6-45a0-8070-b0e83323bfce}</Project>
      <Name>ADPluginInterfaces</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADPluginSettingsInterface\ADPluginSettingsInterface.csproj">
      <Project>{84B5F9E9-8047-4500-9989-6A78784F6E2C}</Project>
      <Name>ADPluginSettingsInterface</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADServerInfo\ADServerInfo.csproj">
      <Project>{4947E94A-3446-44A1-B3F7-4D31C8E30485}</Project>
      <Name>ADServerInfo</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\CommonControls\CommonControls.csproj">
      <Project>{4EEAAF2D-D26A-4DFF-8305-5DDB9E50F385}</Project>
      <Name>CommonControls</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Dynamics\MSZ.csproj">
      <Project>{B2A5DD01-EFC9-4457-9D56-964EE3E274E3}</Project>
      <Name>MSZ</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\OPCUAViewModel\OPCUAViewModel.csproj">
      <Project>{AF9C6A65-F33D-4282-86C0-AB017A45D636}</Project>
      <Name>OPCUAViewModel</Name>
      <Private>False</Private>
	</ProjectReference>
    <ProjectReference Include="..\UFUATag\UFUAModel.csproj">
      <Project>{ECFC4277-3F8E-40C6-B212-5850E9FC3C84}</Project>
      <Name>UFUAModel</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\UserModel\UFUserModel.csproj">
      <Project>{2E6C0B4A-549B-4F9B-A18B-9815F9756890}</Project>
      <Name>UFUserModel</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\Utilities.csproj">
      <Project>{80AC49B3-DACD-4A6F-B884-3D618F41CCF6}</Project>
      <Name>Utilities</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>	
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">	
    <ProjectReference Include="..\CrossReferenceHelper\CrossReferenceHelper.csproj">
      <Project>{8c26c622-dd4d-42c3-8a03-25229acebd58}</Project>
      <Name>CrossReferenceHelper</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\ADServerCMS\ADServerCMS.csproj">
      <Project>{70554309-febf-4aa2-9a02-e4411b69cedc}</Project>
      <Name>ADServerCMS</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\LightSharedResources\LightSharedResources.csproj">
      <Project>{ed378efd-8ca7-4e5f-9431-23765228487b}</Project>
      <Name>LightSharedResources</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\TranslatableMenu\TranslatableMenu\TranslatableMenu.csproj">
      <Project>{eb0d67a7-8642-4dc4-9746-669359cbc690}</Project>
      <Name>TranslatableMenu</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFInterfaces\UFInterfaces.csproj">
      <Project>{6B4E6E7C-5844-4EC1-AFBC-D44E13229FA9}</Project>
      <Name>UFInterfaces</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFProcessServiceCMS\UFProcessServiceCMS.csproj">
      <Project>{b0db568f-7439-458f-a3ba-a8d4823c700f}</Project>
      <Name>UFProcessServiceCMS</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\UFUACommonControls\UFUACommonControls.csproj">
      <Project>{c8851e5d-aa9d-4def-9ac9-69171fb82d02}</Project>
      <Name>UFUACommonControls</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\VFS\VFS.csproj">
      <Project>{57E88FCE-D99D-45EE-B36E-3650B7FE4FBE}</Project>
      <Name>VFS</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\ViewModelBase\ViewModelBase.csproj">
      <Project>{7F649688-289A-4EC3-980C-A092628C18B4}</Project>
      <Name>ViewModelBase</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\WPFUtilities\WPFUtilities.csproj">
      <Project>{22DA80CB-E055-4A06-B0DF-2FA4FA752D03}</Project>
      <Name>WPFUtilities</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <ProjectReference Include="..\..\..\Sources\UA SDK\UA-.NETStandard\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\PluginDescriptionResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>PluginDescriptionResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\UICommandResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UICommandResource.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config">
      <SubType>Designer</SubType>
    </None>
    <None Include="packages.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Page Include="MenuControls\BarCommonItems.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MenuControls\MenuControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Controls\AvailablePlugins.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\GeneralSettings.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\NewFolder.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\NewNotification.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\NewTag.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\NotificationList.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Controls\PluginList.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\SelectUser.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Controls\StartupControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="ADEditorControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="MenuControls\ToolbarControl.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="PropertyDataTemplate\AttachmentsPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\TextBoxNotificationItemPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\NotificationItemPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\PluginNamePropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="PropertyDataTemplate\RecipientPropertyEditor.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ADPlugins.xml">
      <SubType>Designer</SubType>
    </Content>
  </ItemGroup>
  <ItemGroup />
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == 'net48' ">
    <Exec Command="XCOPY /Y &quot;$(TargetDir)$(TargetName).*&quot; &quot;$(OutDir)..\&quot;" />
  </Target>  
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>