//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFScreenSink.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFScreenSink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new session.
        /// </summary>
        internal static string CreatingNewSession {
            get {
                return ResourceManager.GetString("CreatingNewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending expired session.
        /// </summary>
        internal static string EndingExpiredSession {
            get {
                return ResourceManager.GetString("EndingExpiredSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating session count: {0}.
        /// </summary>
        internal static string ErrorUpdatingSessionCount {
            get {
                return ResourceManager.GetString("ErrorUpdatingSessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to activate the user on the server : {0}.
        /// </summary>
        internal static string FailedToActivateUserOnServer {
            get {
                return ResourceManager.GetString("FailedToActivateUserOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client License Entered : Active Licenses = &apos;{0}&apos;.
        /// </summary>
        internal static string LicenseClientEntered {
            get {
                return ResourceManager.GetString("LicenseClientEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client License Exceeded : maximum allowed {0}.
        /// </summary>
        internal static string LicenseClientExceeded {
            get {
                return ResourceManager.GetString("LicenseClientExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client License Released : Active Licenses = &apos;{0}&apos;.
        /// </summary>
        internal static string LicenseClientReleased {
            get {
                return ResourceManager.GetString("LicenseClientReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Manager.
        /// </summary>
        internal static string LicenseManager {
            get {
                return ResourceManager.GetString("LicenseManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAABIAAAAKICAIAAACHSRZaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAADxKSURBVHhe7dzZgSs3rgDQicsB3XgcjZNxMO/1ou5WoTaQItEq+ZzPe7mAIFUkxh7/7/8AAAAooQADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogADAAAoogAD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoValidSessionBase64 {
            get {
                return ResourceManager.GetString("NoValidSessionBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient HTML5.
        /// </summary>
        internal static string WebClientHTML5Log {
            get {
                return ResourceManager.GetString("WebClientHTML5Log", resourceCulture);
            }
        }
    }
}
