#region Copyright Syncfusion Inc. 2001 - 2014
// Copyright Syncfusion Inc. 2001 - 2014. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Windows.Tools.Olap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_OlapTools_WPF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_OlapTools_WPF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Windows.Tools.Olap.Resources.Syncfusion.OlapTools.WPF", typeof(Syncfusion_OlapTools_WPF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string CubeDimensionBrowser_RightClick_Edit {
            get {
                return ResourceManager.GetString("CubeDimensionBrowser_RightClick_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string CubeDimensionBrowser_RightClick_Remove {
            get {
                return ResourceManager.GetString("CubeDimensionBrowser_RightClick_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption:.
        /// </summary>
        internal static string OlapTools_CalcMemberEditor_Caption {
            get {
                return ResourceManager.GetString("OlapTools_CalcMemberEditor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression:.
        /// </summary>
        internal static string OlapTools_CalcMemberEditor_Expression {
            get {
                return ResourceManager.GetString("OlapTools_CalcMemberEditor_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string:.
        /// </summary>
        internal static string OlapTools_CalcMemberEditor_Format {
            get {
                return ResourceManager.GetString("OlapTools_CalcMemberEditor_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Member Editor.
        /// </summary>
        internal static string OlapTools_CalcMemberEditor_Title {
            get {
                return ResourceManager.GetString("OlapTools_CalcMemberEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type:.
        /// </summary>
        internal static string OlapTools_CalcMemberEditor_Type {
            get {
                return ResourceManager.GetString("OlapTools_CalcMemberEditor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OlapTools_Editor_Cancel {
            get {
                return ResourceManager.GetString("OlapTools_Editor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OlapTools_Editor_Delete {
            get {
                return ResourceManager.GetString("OlapTools_Editor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string OlapTools_Editor_MoveDown {
            get {
                return ResourceManager.GetString("OlapTools_Editor_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string OlapTools_Editor_MoveUp {
            get {
                return ResourceManager.GetString("OlapTools_Editor_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OlapTools_Editor_Ok {
            get {
                return ResourceManager.GetString("OlapTools_Editor_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string OlapTools_Editor_SplitButton_Delete_ToolTip {
            get {
                return ResourceManager.GetString("OlapTools_Editor_SplitButton_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string OlapTools_Editor_SplitButton_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("OlapTools_Editor_SplitButton_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string OlapTools_Editor_SplitButton_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("OlapTools_Editor_SplitButton_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check/Uncheck All.
        /// </summary>
        internal static string OlapTools_MeasureEditor_CheckAll_UnCheckAll {
            get {
                return ResourceManager.GetString("OlapTools_MeasureEditor_CheckAll_UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string OlapTools_MeasureEditor_Remove_ContextMenu {
            get {
                return ResourceManager.GetString("OlapTools_MeasureEditor_Remove_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Editor.
        /// </summary>
        internal static string OlapTools_MeasureEditor_Title {
            get {
                return ResourceManager.GetString("OlapTools_MeasureEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check / UnCheck All.
        /// </summary>
        internal static string OlapTools_MemberEditor_CheckAll_UnCheckAll {
            get {
                return ResourceManager.GetString("OlapTools_MemberEditor_CheckAll_UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Editor.
        /// </summary>
        internal static string OlapTools_MemberEditor_Title {
            get {
                return ResourceManager.GetString("OlapTools_MemberEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of records to be displayed..
        /// </summary>
        internal static string OlapTools_SubsetFilter_DropDown_Text {
            get {
                return ResourceManager.GetString("OlapTools_SubsetFilter_DropDown_Text", resourceCulture);
            }
        }
    }
}
