//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sending message &apos;{0}&apos; by Method. Plugin not valid..
        /// </summary>
        public static string ADMethodFailed {
            get {
                return ResourceManager.GetString("ADMethodFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing the &apos;{0}&apos; plugin.
        /// </summary>
        public static string ADPluginNotInitiliazed {
            get {
                return ResourceManager.GetString("ADPluginNotInitiliazed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin {0} for the notification &apos;{1}&apos; is not configured. Notification was not loaded..
        /// </summary>
        public static string ADPluginNotLoaded {
            get {
                return ResourceManager.GetString("ADPluginNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient(s) {0} was(were) not found among the defined users. Notification: {1}.
        /// </summary>
        public static string ADRecipientNotFound {
            get {
                return ResourceManager.GetString("ADRecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alarm Dispatcher on the host name &apos;{0}&apos; is active..
        /// </summary>
        public static string ADServerActive {
            get {
                return ResourceManager.GetString("ADServerActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alarm Dispatcher on the host name &apos;{0}&apos; is NOT active..
        /// </summary>
        public static string ADServerNotActive {
            get {
                return ResourceManager.GetString("ADServerNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Dispatcher Service Started.
        /// </summary>
        public static string ADServiceStarted {
            get {
                return ResourceManager.GetString("ADServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Dispatcher Service Stopped.
        /// </summary>
        public static string ADServiceStopped {
            get {
                return ResourceManager.GetString("ADServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Users data! Check Users Connection string..
        /// </summary>
        public static string ADUsersNotLoaded {
            get {
                return ResourceManager.GetString("ADUsersNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Certificate is invalid. Would you create a new one?.
        /// </summary>
        public static string AskForCertificateChecker {
            get {
                return ResourceManager.GetString("AskForCertificateChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application Certificate.
        /// </summary>
        public static string AskForCertificateCheckerCaption {
            get {
                return ResourceManager.GetString("AskForCertificateCheckerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A socket error occured starting the server application, try to change the socket port number in the server settings.&apos;newline&apos;&apos;newline&apos;&apos;{0}&apos;..
        /// </summary>
        public static string CommunciationErrorOnStartingService {
            get {
                return ResourceManager.GetString("CommunciationErrorOnStartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string ConsoleSystemEvent {
            get {
                return ResourceManager.GetString("ConsoleSystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the Node Managers.
        /// </summary>
        public static string CreatingNodeManagers {
            get {
                return ResourceManager.GetString("CreatingNodeManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting culture &apos;{0}&apos; for the message recipient {1}. Error: {2}.
        /// </summary>
        public static string CultureInfoError {
            get {
                return ResourceManager.GetString("CultureInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Message is not defined. Standard message will be used..
        /// </summary>
        public static string CustomMessageUndefined {
            get {
                return ResourceManager.GetString("CustomMessageUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting persistent message: &apos;{0}&apos;.
        /// </summary>
        public static string DeletePersistenceError {
            get {
                return ResourceManager.GetString("DeletePersistenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, preparing Tag for notification &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorPrepareExecution {
            get {
                return ResourceManager.GetString("ErrorPrepareExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, preparing Service Tags for user &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorPreparingServiceTags {
            get {
                return ResourceManager.GetString("ErrorPreparingServiceTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured in the Server : {0}.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HExclusive {
            get {
                return ResourceManager.GetString("HExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High High.
        /// </summary>
        public static string HHExclusive {
            get {
                return ResourceManager.GetString("HHExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High High Active.
        /// </summary>
        public static string HHNonExclusive {
            get {
                return ResourceManager.GetString("HHNonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Active.
        /// </summary>
        public static string HNonExclusive {
            get {
                return ResourceManager.GetString("HNonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized Plugin {0}.
        /// </summary>
        public static string InitializedPlugin {
            get {
                return ResourceManager.GetString("InitializedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Plugin {0}.
        /// </summary>
        public static string InitializingPlugin {
            get {
                return ResourceManager.GetString("InitializingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LExclusive {
            get {
                return ResourceManager.GetString("LExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Manager.
        /// </summary>
        public static string LicenseManager {
            get {
                return ResourceManager.GetString("LicenseManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Low.
        /// </summary>
        public static string LLExclusive {
            get {
                return ResourceManager.GetString("LLExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Low Active.
        /// </summary>
        public static string LLNonExclusive {
            get {
                return ResourceManager.GetString("LLNonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Active.
        /// </summary>
        public static string LNonExclusive {
            get {
                return ResourceManager.GetString("LNonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin {0} ({1}{2}).
        /// </summary>
        public static string LoadedPlugin {
            get {
                return ResourceManager.GetString("LoadedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADServer properties loaded.
        /// </summary>
        public static string LoadedServerProperties {
            get {
                return ResourceManager.GetString("LoadedServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugin {0} ({1}{2}).
        /// </summary>
        public static string LoadingPlugin {
            get {
                return ResourceManager.GetString("LoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ADServer properties.
        /// </summary>
        public static string LoadingServerProperties {
            get {
                return ResourceManager.GetString("LoadingServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlarmDispatcher Server.
        /// </summary>
        public static string LoggerSource {
            get {
                return ResourceManager.GetString("LoggerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server I/O file {0} not found..
        /// </summary>
        public static string MissingProjectFile {
            get {
                return ResourceManager.GetString("MissingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server license execution not found !.
        /// </summary>
        public static string NoSvrLicence {
            get {
                return ResourceManager.GetString("NoSvrLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alarm Name of the &apos;{0}&apos; notification is not valid! .
        /// </summary>
        public static string NotificationErrorAlarmName {
            get {
                return ResourceManager.GetString("NotificationErrorAlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening persistent message queue: &apos;{0}&apos;.
        /// </summary>
        public static string OpenPersistenceError {
            get {
                return ResourceManager.GetString("OpenPersistenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADServer Per.
        /// </summary>
        public static string PersistenceSource {
            get {
                return ResourceManager.GetString("PersistenceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos;: Phone Number Tag connected..
        /// </summary>
        public static string PhoneTagAdded {
            get {
                return ResourceManager.GetString("PhoneTagAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new server application cannot be started, because this project already running with another server instance or the socket port number is already used by another process  !.
        /// </summary>
        public static string ProjectAlreadyRunning {
            get {
                return ResourceManager.GetString("ProjectAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading persistent message queue: &apos;{0}&apos;.
        /// </summary>
        public static string ReadPersistenceError {
            get {
                return ResourceManager.GetString("ReadPersistenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test of the server sockets failed. Retry {0} of {1}, next attempt in {2} ms..
        /// </summary>
        public static string RetryOpenSocketWarningMessage {
            get {
                return ResourceManager.GetString("RetryOpenSocketWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving persistent message: &apos;{0}&apos;.
        /// </summary>
        public static string SavePersistenceError {
            get {
                return ResourceManager.GetString("SavePersistenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ************************* SERVER STARTED ! *******************************.
        /// </summary>
        public static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server is Starting, Running a {0} bit process.
        /// </summary>
        public static string ServerStarting {
            get {
                return ResourceManager.GetString("ServerStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server has been stopped.
        /// </summary>
        public static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Server is Stopping.
        /// </summary>
        public static string ServerStopping {
            get {
                return ResourceManager.GetString("ServerStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Started.
        /// </summary>
        public static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service starting.
        /// </summary>
        public static string ServiceStarting {
            get {
                return ResourceManager.GetString("ServiceStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Stopped.
        /// </summary>
        public static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Stopping.
        /// </summary>
        public static string ServiceStopping {
            get {
                return ResourceManager.GetString("ServiceStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Stopped.
        /// </summary>
        public static string StoppedServer {
            get {
                return ResourceManager.GetString("StoppedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Server.
        /// </summary>
        public static string StoppingServer {
            get {
                return ResourceManager.GetString("StoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone number Tag for recipient {0} is invalid..
        /// </summary>
        public static string TelephonNumberTagInvalid {
            get {
                return ResourceManager.GetString("TelephonNumberTagInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone number Tag for recipient {0} is NOT connected..
        /// </summary>
        public static string TelephonNumberTagNotConnected {
            get {
                return ResourceManager.GetString("TelephonNumberTagNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone number Tag for recipient {0} do NOT exist..
        /// </summary>
        public static string TelephonNumberTagNotExist {
            get {
                return ResourceManager.GetString("TelephonNumberTagNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The telephone number Tag for recipient {0} has NOT Good quality..
        /// </summary>
        public static string TelephonNumberTagNotGood {
            get {
                return ResourceManager.GetString("TelephonNumberTagNotGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string TripActive {
            get {
                return ResourceManager.GetString("TripActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to use the discovery behavior in the service host !.
        /// </summary>
        public static string UnableToUseDiscoveryBehaviour {
            get {
                return ResourceManager.GetString("UnableToUseDiscoveryBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating persistent message: &apos;{0}&apos;.
        /// </summary>
        public static string UpdatePersistenceError {
            get {
                return ResourceManager.GetString("UpdatePersistenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersManager {
            get {
                return ResourceManager.GetString("UsersManager", resourceCulture);
            }
        }
    }
}
